### ISSUE TITLE
How to record desktop screen using this lib?

### ISSUE THREAD

**Issue by SaddamBInSyed** [rosenbjerg/FFMpegCore#1]
How to record desktop screen using this lib in windows 7 and 10.

please advise

**Comment by vladjerca** [comment]
@SaddamBInSyed If you need to record the screen, take a look here. https://trac.ffmpeg.org/wiki/Capture/Desktop

All you need to do is implement the required arguments, by extending the `Argument` class from, and build your own custom `ffmpeg` command 👍
