### ISSUE TITLE
Image2Pipe

### ISSUE THREAD

**Issue by nlem** [rosenbjerg/FFMpegCore#101]
I wrote a class that uses image2pipe that is useful for sending a stream of images to ffmpeg.
It seems like a useful thing to have in your code and seems to work well.
You can pass in (for example) a list of raw byte arrays with each byte array from a jpeg file.

`

    public class Image2PipeDataWriter : IPipeSource
    {
        public int FrameRate { get; set; }

        private readonly IEnumerator<byte[]> _framesEnumerator;

        public Image2PipeDataWriter(IEnumerator<byte[]> framesEnumerator, int framerate = 2)
        {
            FrameRate = framerate;
            _framesEnumerator = framesEnumerator;
        }

        public Image2PipeDataWriter(IEnumerable<byte[]> framesEnumerator, int framerate = 2) : this(framesEnumerator.GetEnumerator(), framerate) { }

        public string GetFormat()
        {
            return $"-f image2pipe -r {FrameRate} ";
        }

        public async Task CopyAsync(System.IO.Stream outputStream, CancellationToken cancellationToken)
        {
            if (_framesEnumerator.Current != null)
            {
                await outputStream.WriteAsync(_framesEnumerator.Current, 0, _framesEnumerator.Current.Length, cancellationToken).ConfigureAwait(false);                
            }

            while (_framesEnumerator.MoveNext())
            {
                await outputStream.WriteAsync(_framesEnumerator!.Current, 0, _framesEnumerator.Current!.Length, cancellationToken).ConfigureAwait(false);
            }
        }
    }
`

**Comment by rosenbjerg** [comment]
@max619 What do you think? Looks similar in functionality to your example

**Comment by nlem** [comment]
Apologies if this was already done somewhere else. I couldn't find it.
More generally, FFMpegCore doesn't seem to support adding arguments to the input specification, only the output?
eg ForceFormat only applies to the output, if a function like  ForceInputFormat were created this could be used to do the same job

**Comment by rosenbjerg** [comment]
I do have plan to support adding arguments to the input specification

**Comment by rosenbjerg** [comment]
Version 3 of this library now support supplying arguments for each input and for the output :)
