### ISSUE TITLE
moov atom not found unix:/tmp/CoreFxPipe_FFMpegCore_1cad9593-a4dd-4e1f-8435-fd92f36a9269: Invalid data found when processing input at FFMpegCore.FFProbe.Analyse(Stream stream, Int32 outputCapacity)

### ISSUE THREAD

**Issue by BenjayLin** [rosenbjerg/FFMpegCore#103]
This is my code:

`var result =await  _httpClient.GetStreamAsync(url);           
 var mediaInfo = FFProbe.Analyse(result);`

When requesting an mp4 file under Linux, an error was reported, but when requesting an m4a file, it was normal. 
Both are normal under the window.

`FFProbe process returned exit status 1: { } ffprobe version 2.8.15 Copyright (c) 2007-2018 the FFmpeg developers built with gcc 4.8.5 (GCC) 20150623 (Red Hat 4.8.5-36) configuration: --prefix=/usr --bindir=/usr/bin --datadir=/usr/share/ffmpeg --incdir=/usr/include/ffmpeg --libdir=/usr/lib64 --mandir=/usr/share/man --arch=x86_64 --optflags='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic' --extra-ldflags='-Wl,-z,relro ' --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libvo-amrwbenc --enable-version3 --enable-bzlib --disable-crystalhd --enable-gnutls --enable-ladspa --enable-libass --enable-libcdio --enable-libdc1394 --enable-libfdk-aac --enable-nonfree --disable-indev=jack --enable-libfreetype --enable-libgsm --enable-libmp3lame --enable-openal --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-libschroedinger --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libvorbis --enable-libv4l2 --enable-libx264 --enable-libx265 --enable-libxvid --enable-x11grab --enable-avfilter --enable-avresample --enable-postproc --enable-pthreads --disable-static --enable-shared --enable-gpl --disable-debug --disable-stripping --shlibdir=/usr/lib64 --enable-runtime-cpudetect libavutil 54. 31.100 / 54. 31.100 libavcodec 56. 60.100 / 56. 60.100 libavformat 56. 40.101 / 56. 40.101 libavdevice 56. 4.100 / 56. 4.100 libavfilter 5. 40.101 / 5. 40.101 libavresample 2. 1. 0 / 2. 1. 0 libswscale 3. 1.101 / 3. 1.101 libswresample 1. 2.101 / 1. 2.101 libpostproc 53. 3.100 / 53. 3.100 [mov,mp4,m4a,3gp,3g2,mj2 @ 0x26383e0] moov atom not found unix:/tmp/CoreFxPipe_FFMpegCore_1cad9593-a4dd-4e1f-8435-fd92f36a9269: Invalid data found when processing input at FFMpegCore.FFProbe.Analyse(Stream stream, Int32 outputCapacity) `

**Comment by rosenbjerg** [comment]
Could you try just passing the url directly as input to .Analyse? ffprobe should handle that no problem

**Comment by bradley-varol** [comment]
I have this same `mov atom` error when using `await FFProbe.AnalyseAsync(new MemoryStream(workItem.SourceBytes))`. I'd like to use FastStart but there doesn't seem to be a way to pass args to ffprobe?
