### ISSUE TITLE
Xamarin.Forms support

### ISSUE THREAD

**Issue by AmSmart** [rosenbjerg/FFMpegCore#104]
Question / Feature Request

Is this supposed to work with Xamarin.Forms(since it;s .NET Standard after all). If it is not supported. what is needed to add the support?

Thanks in advance

**Comment by rosenbjerg** [comment]
I think be problem will be to get an FFMpeg executeable running, though it is technically possible since ffmpeg runs fine on linux on arm.

**Comment by AmSmart** [comment]
Interesting! Thanks for feedback anyway🙏

**Comment by rosenbjerg** [comment]
You're welcome :)
