### ISSUE TITLE
MediaInfo in file

### ISSUE THREAD

**Issue by tqk2811** [rosenbjerg/FFMpegCore#106]
I got exception

Exception on [file](https://drive.google.com/file/d/1lpLnwSpvipyw7pPSL2LYw8MMgQ8p1Vm0/view?usp=sharing) when FFProbe.Analyse: `System.Text.Json.JsonException: 't' is invalid after a value. Expected either ',', '}', or ']'. Path: $.format.tags.title | LineNumber: 0 | BytePositionInLine: 3595.`  

Json:
`{    "streams": [        {            "index": 0,            "codec_name": "mp3",            "codec_long_name": "MP3 (MPEG audio layer 3)",            "codec_type": "audio",            "codec_time_base": "1/44100",            "codec_tag_string": "[0][0][0][0]",            "codec_tag": "0x0000",            "sample_fmt": "fltp",            "sample_rate": "44100",            "channels": 2,            "channel_layout": "stereo",            "bits_per_sample": 0,            "r_frame_rate": "0/0",            "avg_frame_rate": "0/0",            "time_base": "1/14112000",            "start_pts": 353600,            "start_time": "0:00:00.025057",            "duration_ts": 3829063680,            "duration": "0:04:31.333878",            "bit_rate": "320000",            "disposition": {                "default": 0,                "dub": 0,                "original": 0,                "comment": 0,                "lyrics": 0,                "karaoke": 0,                "forced": 0,                "hearing_impaired": 0,                "visual_impaired": 0,                "clean_effects": 0,                "attached_pic": 0,                "timed_thumbnails": 0            },            "tags": {                "encoder": "LAME3.99r"            },            "side_data_list": [                {                    "side_data_type": "Replay Gain"                }            ]        },        {            "index": 1,            "codec_name": "mjpeg",            "codec_long_name": "Motion JPEG",            "profile": "Baseline",            "codec_type": "video",            "codec_time_base": "0/1",            "codec_tag_string": "[0][0][0][0]",            "codec_tag": "0x0000",            "width": 500,            "height": 446,            "coded_width": 500,            "coded_height": 446,            "closed_captions": 0,            "has_b_frames": 0,            "sample_aspect_ratio": "1:1",            "display_aspect_ratio": "250:223",            "pix_fmt": "yuvj420p",            "level": -99,            "color_range": "pc",            "color_space": "bt470bg",            "chroma_location": "center",            "refs": 1,            "r_frame_rate": "90000/1",            "avg_frame_rate": "0/0",            "time_base": "1/90000",            "start_pts": 2255,            "start_time": "0:00:00.025056",            "duration_ts": 24420049,            "duration": "0:04:31.333878",            "bits_per_raw_sample": "8",            "disposition": {                "default": 0,                "dub": 0,                "original": 0,                "comment": 0,                "lyrics": 0,                "karaoke": 0,                "forced": 0,                "hearing_impaired": 0,                "visual_impaired": 0,                "clean_effects": 0,                "attached_pic": 1,                "timed_thumbnails": 0            },            "tags": {                "comment": "Cover (front)"            }        }    ],    "format": {        "filename": "E:\\c.mp3",        "nb_streams": 2,        "nb_programs": 0,        "format_name": "mp3",        "format_long_name": "MP2/3 (MPEG audio layer 2/3)",        "start_time": "0:00:00.025056",        "duration": "0:04:31.333878",        "size": "10893807",        "bit_rate": "321192",        "probe_score": 51,        "tags": {            "album": "border",            "artist": "ClariS",            "comment": "ExactAudioCopy v1.0b3",            "TSRC": "JPU901402151",            "title": "繧ｫ繧､繝・,            "track": "3/4",            "DISCID": "32038304"        }    }}`

`"title": "繧ｫ繧､繝・`
Title show in explorer properties: `カイト`

**Comment by tqk2811** [comment]
Bug from `ffprobe`   
I temporary remove `-show_format` and `if(null != analysis.Format) Format = ParseFormat(analysis.Format);` in `MediaAnalysis`   
(I need duration mp3 only)

**Comment by rosenbjerg** [comment]
Yeah it looks like an ffprobe bug with unicode charaters, specifically the title (`"title": "繧ｫ繧､繝・, "trac..`) isn't ended correctly with a `"`. 
You might want to report this bug to the official ffprobe bug tracker if you experience this bug on the newest stable version of ffprobe

**Comment by tqk2811** [comment]
`ffprobe -print_format json -show_format -show_streams -sexagesimal file.mp3 > text.txt`  
Text file look good, may be problem when read from console stream.
https://trac.ffmpeg.org/ticket/8890#comment:2
