### ISSUE TITLE
Output video unplayable when using FFMpeg.JoinImageSequence to render video.

### ISSUE THREAD

**Issue by ghost** [rosenbjerg/FFMpegCore#107]
I'm attempting to join a sequence of .PNG images to create a .MP4 video, but the resulting file is unplayable. The player returns:
**This file isn't playable. That might be because the file type is unsupported, the file extension is incorrect, or the file is corrupt. 0xc10100be**
I've made sure the resulting file was indeed an MP4 and that I was using .PNG as the frames. The code I'm using is below.

My code:

```
while (assembledFrame != totalNumberOfFrames)
            {
                FFMpeg.JoinImageSequence(
                    videoDumpFolderPath + @"\Output.mp4", frameRate: 1,
                    ImageInfo.FromPath( bitmapDumpFolderPath + @"\" + assembledFrame.ToString() + ".png" ));

                Console.Write("\rAssembled frame " + assembledFrame + " of " + totalNumberOfFrames + "...");

                assembledFrame++;
            }
```

I've also attempted to manually assign the frames. But I get the same result.

```
FFMpeg.JoinImageSequence(
                    videoDumpFolderPath + @"\Output.mp4", frameRate: 1,
                    ImageInfo.FromPath( bitmapDumpFolderPath + @"\0.png" ),
                    ImageInfo.FromPath( bitmapDumpFolderPath + @"\1.png" ),
                    ImageInfo.FromPath( bitmapDumpFolderPath + @"\2.png" )
                    );
```

I'm rather new to FFMpegCore so I'm more likely doing this wrong. And all the help I've found online was for FFMpegSharp.
Thanks in advance!

Edit: Almost forgot to mention that the variables 'videoDumpFolderPath' and 'bitmapDumpFolderPath' are directories.

**Comment by Nilifin** [comment]
It appears that the **System.IO.IOException: 'The file '...\000000000.png' already exists.'** error is completely separate from the inability to play exported video error. During the time of submitting my issue I might have messed something up where System.IO is automatically attempting to read and write to **'C:\Users\[USERNAME]\AppData\Local\Temp\'** instead of the specified directories.

So ignore that issue.

**Comment by SDEBEUL** [comment]
Hi,

I'm facing the same issue.
Actually the mp4 has some frames when i encode 3600 + images. But its skipping a lot of frames.

I think it might be related to this 
[https://stackoverflow.com/questions/24961127/how-to-create-a-video-from-images-with-ffmpeg](https://stackoverflow.com/questions/24961127/how-to-create-a-video-from-images-with-ffmpeg)

this lib seems to implement the -r argument only and not the ftps argument

[https://github.com/rosenbjerg/FFMpegCore/blob/92c1d0f457255dcbc9107832cd6b4f9110bcf3de/FFMpegCore/FFMpeg/Arguments/FrameRateArgument.cs](https://github.com/rosenbjerg/FFMpegCore/blob/92c1d0f457255dcbc9107832cd6b4f9110bcf3de/FFMpegCore/FFMpeg/Arguments/FrameRateArgument.cs)

**Comment by ghost** [comment]
Thank you for your response!

I have played around with this for a bit with no results. I've also attempted to experiment with rendering multiple videos with 5000 frames each. All of which don't play while still returning the same error as before. Other fixes regarding similar issues unfortunately don't seem to change anything.

I'm still attempting to work the problem out and I'll keep this issue updated on any progress I make towards solving it.

**Comment by rosenbjerg** [comment]
It looks like you are only passing the path to a single image? Am I reading it wrong?

**Comment by SDEBEUL** [comment]
Hi, I fixxed it by adding the WithConstantRateFactor arg.
```csharp                
        return FFMpegArguments
                    .FromInputFiles(false, Path.Combine(tempFolderName, "%09d.png"))
                    .Resize(firstImage.Width, firstImage.Height)
                    .WithConstantRateFactor(Convert.ToInt32(frameRate)) 
                    .OutputToFile(output)
                    .ProcessSynchronously();
```

I don't really understand why but this produces a working video for me.

**Comment by rosenbjerg** [comment]
@SDEBEUL Very interesting to hear. Maybe the problem is that without any other arguments, no actual transcoding is done.
But I'm glad to hear you found a reasonable solution.
I have reformatted the code in your comment, containing your fix, to make it easier to read for future reference
Closing since you found this solution. 
@Nilifin Feel free to reopen if your problem cannot be fixed in a similar way to what @SDEBEUL did
