### ISSUE TITLE
Do i need to download anything other than this package ?

### ISSUE THREAD

**Issue by kcvinker** [rosenbjerg/FFMpegCore#111]
Hi,
I just installed this package and import it to my project.  But when i tried the example code, it says that "System can't find the file". So i double check my video file path and everything is ok. Do i need to download anything else ? I can't find anything relate in this page.

**Comment by kcvinker** [comment]
Issue fixed. I figured out that this package need some other executables to work properly. I have dowloaded these three files (ffprobe, ffmpeg, ffplay) and put them inside the file path of my program and now it's working. I humbly request to add this info in the main page so that another person won't be get confused.

**Comment by rosenbjerg** [comment]
It is actually on the main page, but too far down i suppose:
https://github.com/rosenbjerg/FFMpegCore#binaries
