### ISSUE TITLE
How to get a key frame picture from a video by FFMpegCore ?

### ISSUE THREAD

**Issue by quentin-zhang** [rosenbjerg/FFMpegCore#113]
Hi,
    Is it possible to get a key frame picture from a video like the ffmpeg bash:
`ffmpeg -i b.mp4 -vf select='eq(pict_type\,I)' -vsync 2 -s 640*480 -f image2 keyframe-%02d.jpeg` ?
    Thanks for your help.

**Comment by rosenbjerg** [comment]
Yes you can definitely do that with FFMpegCore. You can use `.WithCustomArgument(...)` to pass arguments that aren't directly supported, like the custom video filter you are  applying
