### ISSUE TITLE
Image joining currently suppors only .png file types 

### ISSUE THREAD

**Issue by alllucky1996** [rosenbjerg/FFMpegCore#115]
Hello everyone,
after I get the list of frames (List <Bitmap>) and want to concatenate them using ImageInfo. I get the message "Join image currently only supports .png file types". I want it to be able to use many types of images other than png (bitmap, jpg, Mat-opencv ...) but haven't found a solution yet :( .
Please help me to solve this problem.
Best regards.
Anh Dung.

**Comment by rosenbjerg** [comment]
You could use something like imagemagick, i.e. the Magick.NET nuget package, to convert images of basically any format to png
