### ISSUE TITLE
Plans on expanding Arguments

### ISSUE THREAD

**Issue by raspyweather** [rosenbjerg/FFMpegCore#117]
hey there ^^,
just recently I've been trying to get the equivalent of "-vf fps=1/8" working with this library and ended up simply implementing a class deriving from IArguments and it worked pretty amazing.
I couldn't find documentation here, so I wonder whether it would be a good idea to contribute a couple of these Argument classes or add some documentation for them.
Maybe we might even consider implementing a class which takes an plain string directly parsed to -vf to allow for combining more complex operation. 

Could a contribution in this part help you?

**Comment by rosenbjerg** [comment]
Hello, 
Great to hear that you found it easy to expand the functionality of this library. That is one of the main goals of the current structure, though some areas still need a bit of work.
If you think it is common functionality, a PR that adds these would be appreciated! 👍

**Comment by raspyweather** [comment]
Eww... I kinda screwed up on my side :'D 
Somehow I totally overlooked the existing GenericArgument already included in your library which does exactly what I had implemented on my own. Well yeah, good to know that extending your framework is as easy as using it, great job there ^^
