### ISSUE TITLE
[Question] Why so many references?

### ISSUE THREAD

**Issue by fu-hsi** [rosenbjerg/FFMpegCore#118]
Hi.
I have more than 100 dlls in project after installed FFMpegCore.
Most of them are dlls built in .NET like System.IO.dll, why they are copied?
How change this behavior?

Regards.

**Comment by tiesont** [comment]
This is a .NET Standard project. Depending on the type of project you're installing it into, it's not uncommon for a lot of secondary references to be added. The dotnet compiler is pretty good at only including **used** references, if you publish the project you're working on, so I wouldn't focus too much on those secondary references.
