### ISSUE TITLE
Using ffmpegcore to create hls

### ISSUE THREAD

**Issue by mhamel** [rosenbjerg/FFMpegCore#119]
Hi,

I would like to use it to do this command equivalent and I'm unable to make it work.  Anybody can help!?

-re -i "http://dsdsdsds.sdsds" -c:v copy -c:a copy -f hls -hls_time 4 -hls_playlist_type event "C:\live\7b598221-0140-4437-a43d-edcdd78797e7.m3u8"

So far I have only this:

`       FFMpegArguments
.FromInputFiles(new Uri("http://dddddd"))
                        .CopyChannel(FFMpegCore.Enums.Channel.Both)
                        .WithFastStart()
                        .OutputToFile(System.IO.Directory.GetCurrentDirectory() + "\\test.m3u8",true)
                        .ProcessSynchronously();`

thank you!

**Comment by rosenbjerg** [comment]
You can use
```chsarp
...
.ForceFormat("hls")
.WithCustomArgument("-hls_time 4")
.WithCustomArgument("-hls_playlist_type event")
...
```
 to cover the remaining arguments from your original ffmpeg args. You have added .WithFastStart() which you do not have in the original args, so that could also be a problem.
Please try to keep question on stackoverflow. This is for issues
