### ISSUE TITLE
Allow extensions to FFMpegArguments

### ISSUE THREAD

**Issue by 9ParsonsB** [rosenbjerg/FFMpegCore#121]
Hi, I am trying to write support for capturing the screen to a file using FFMpegCore, I have written an implementation of `IArgument` that should pass the correct commandline parameters however, I have just noticed that there is no way to extend or derive from `FFMpegArguments`, so there is no way for me to test my code without forking.

Please consider either making the class constructor internal or some other way to create an `FFMpegArguments` without being restricted to the `IArguments` provided.

I am happy to contribute the `ScreenCaptureArguments` should this be fixed.

**Comment by rosenbjerg** [comment]
The .WithArgument(..) actually takes an IArgument instance as input to allow for creating custom classes implementing IArgument.

**Comment by rosenbjerg** [comment]
https://github.com/rosenbjerg/FFMpegCore/blob/76107fb93e305a6eb500361f24aced4229b4d415/FFMpegCore/FFMpeg/FFMpegArguments.cs#L94

**Comment by 9ParsonsB** [comment]
To use `.WithArgument(..)` I need an instance, but to create an instance I need to use one of the static methods, however, from what I can tell, each of the static methods adds arguments to the FFMpeg command line which I dont want to do. How do I create an empty `FFMpegArguments` instance?

**Comment by rosenbjerg** [comment]
What do you mean by empty? You are supposed to initialize an instance using one of the .From* methods:
https://github.com/rosenbjerg/FFMpegCore/blob/76107fb93e305a6eb500361f24aced4229b4d415/FFMpegCore/FFMpeg/FFMpegArguments.cs#L28-L37

**Comment by rosenbjerg** [comment]
Sounds like what you need is to create an class that derives from IInputArgument, and then create a static FromScreenCapture() method.
I'd gladly accept a PR that adds such functionality if that is where you are going :)

**Comment by 9ParsonsB** [comment]
Thanks for pointing me in the right direction! I'll get back to you if I have any other questions or with the PR 😁

**Comment by 9ParsonsB** [comment]
@rosenbjerg I have an initial implementation over at https://github.com/9ParsonsB/FFMpegCore/ 
It is not done, but I am looking for feedback. 
Should I open a PR?
