### ISSUE TITLE
How do you get the size?

### ISSUE THREAD

**Issue by dreadune** [rosenbjerg/FFMpegCore#124]
When using  FFProbe.AnalyseAsync(); It returns a MediaAnalysis object. I cannot find a size on it like there is on this FFProbeAnalysis class. I haven't been able to find a method that returns a FFProbeAnalysis either. Any help is appreciated!

**Comment by xancenl** [comment]
```
MediaAnalysis mediaInfo = await FFProbe.AnalyseAsync(pathFromVideoFile);

int width = mediaInfo.PrimaryVideoStream.Width;
int height = mediaInfo.PrimaryVideoStream.Height;

Size size = new Size(width, height);
```
