### ISSUE TITLE
Audio no included in  FFMpeg.Join

### ISSUE THREAD

**Issue by pfuentes1402** [rosenbjerg/FFMpegCore#125]
Hi, I have recently started using the FFMpegCore library. I am trying to join two videos, but the final result of the union does not include the audio of the videos where it belongs. My code is: 

FFMpeg.Join("result.mp4", "video1.mp4", "video2.mp4");

Thanks...

**Comment by rosenbjerg** [comment]
Hi.
I am not sure what you mean by the audio not being where it belongs.
Could you elaborate?

**Comment by rosenbjerg** [comment]
Closing to due inactivity. Feel free to reopen
