### ISSUE TITLE
How to fade-in/out

### ISSUE THREAD

**Issue by mlhyyl** [rosenbjerg/FFMpegCore#127]
Hi guys,

I'm trying to pull together a program where ffmpeg creates a disclaimer video out of a png file and joins it with a trimmed video with fade-in and fade-out. Plus a logo on the trimmed video. The code below runs without any problem via command line but how can get this done in FFMpegCore? Do I pass all parameters through `.WithCustomArgument` or is there another way?

Here my command line code:

`ffmpeg -i input.mp4 -i logoFrame.png -i disclaimer.jpg -f lavfi -t 1 -i anullsrc -filter_complex "[2:v]fps=fps=30,loop=loop=450:size=30:start=0[v2];[v2]fade=t=in:st=0:d=1,fade=t=out:st=14:d=1[vv2];[0:v]trim=start=31:end=333,setpts=PTS-STARTPTS,scale=1920:1080[v0];[0:a]atrim=start=31:end=333,asetpts=PTS-STARTPTS[a0];[v0][1:v]overlay=0:0[vv0];[vv0]fade=t=in:st=0:d=1,fade=t=out:st=301:d=1[vvv0];[a0]afade=t=in:st=0:d=1,afade=t=out:st=301:d=1[aa0];[vv2][3:a][vvv0][aa0]concat=n=2:v=1:a=1[vv][aa]" -map [vv] -map [aa] -c:a aac -vcodec libx264 -s 1920x1080 output.mp4`

Thanks

**Comment by rosenbjerg** [comment]
You could add the input arguments using the methods for that, but most of this ffmpeg argument list isn't supported directly by this wrapper library, so using .WithCustomerArgument for most would be the way.
You could also use WithAudioCodec and WithVideoCodec for the codec part, but still.

Hope that helps
