### ISSUE TITLE
Chinese random code error

### ISSUE THREAD

**Issue by 3400442579** [rosenbjerg/FFMpegCore#129]
await FFProbe.AnalyseAsync(@“C:\Users\jxw\Desktop\新建 文件夹\SampleVideo_1280x720_1mb.mp4”);

error Chinese random code

` public Instance(ProcessStartInfo startInfo)
        {
            _startInfo = startInfo;
            _startInfo.CreateNoWindow = true;
            _startInfo.StandardOutputEncoding = System.Text.Encoding.UTF8; ////////////////////////
        }`

**Comment by rosenbjerg** [comment]
Are you suggesting changing the _startInfo.StandardOutputEncoding = System.Text.Encoding.UTF8 ?

**Comment by 3400442579** [comment]
yes
