### ISSUE TITLE
Fix the abysmal documentation please

### ISSUE THREAD

**Issue by edgib102** [rosenbjerg/FFMpegCore#132]
Seriously it's like a major barrier for entry

**Comment by tiesont** [comment]
> Seriously it's like a major barrier for entry

So is posting rude comments as issues on a free and open source project. There are a lot of different ways you could have asked for help that aren't insulting.

**Comment by renanrcp** [comment]
I disagree, any people that already used FFMpeg understand this library without problems

**Comment by rosenbjerg** [comment]
The documentation for this library is not supposed to teach you how to use ffmpeg
There are excellent resources available for that online
