### ISSUE TITLE
NullReferenceException in FFMpegBase.IsWorking.get()

### ISSUE THREAD

**Issue by Duke02** [rosenbjerg/FFMpegCore#14]
What I'm doing is I am recording my WPF application, saving screenshots of the program to a temp directory. Once we are finished recording, we join all of the saved images in the temp directory to an ImageSequence using `FFMPEG.JoinImageSequence`. We get a NullReferenceException when we call JoinImageSequence, which points to the get for IsWorking within FFBase as the root cause.

Here's the call stack. 
```
FFMpegCore.dll!FFMpegCore.FFMPEG.FFBase.IsWorking.get()
FFMpegCore.dll!FFMpegCore.FFMPEG.FFBase.CreateProcess(string args, string processPath, bool rStandardInput, bool rStandardOutput, bool rStandardError)
FFMpegCore.dll!FFMpegCore.FFMPEG.FFMpeg.RunProcess(FFMpegCore.FFMPEG.Argument.ArgumentContainer container, System.IO.FileInfo output)
FFMpegCore.dll!FFMpegCore.FFMPEG.FFMpeg.JoinImageSequence(System.IO.FileInfo output, double frameRate, FFMpegCore.ImageInfo[] images)
```

I'm not sure but I believe doing 
```cs
if(Process != null) {
    return Process.HasExited
} else {
    return false;
}
```
might be a better solution than what is currently happening, as I think the `Process.Id` in `Process.GetProcesses().Any(x => x.Id == Process.Id)` in the return statement might be what's causing the problem. I would be happy to do a pull request myself and figure it out if y'all would like.

**Comment by vladjerca** [comment]
@Duke02 feel free to open a PR, they're always welcome! Thanks a bunch 🥳

**Comment by rosenbjerg** [comment]
This has been fixed in later versions. At least 1.4.0 and up
