### ISSUE TITLE
filw not found error

### ISSUE THREAD

**Issue by taula50** [rosenbjerg/FFMpegCore#142]
adding nuget package ffmpegCore (last version) and using FFProbe.Analyse(filename), this throw an exception of type file not found, but the filename is the fullpath to a mp4 video.

**Comment by taula50** [comment]
here is the complete error
![2020-12-09](https://user-images.githubusercontent.com/16879805/101628016-7cf8a800-3a1f-11eb-9a8b-297391f97a69.png)

**Comment by rosenbjerg** [comment]
It looks like ffprobe isn't installed on your environment. You can configure the folder it attempts to open ffprobe (and ffmpeg) from using this, as shown in the readme:
```csharp
FFMpegOptions.Configure(new FFMpegOptions { RootDirectory = "C:\Dir\Containing\FFProbe.exe" });
```
