### ISSUE TITLE
file not found yet

### ISSUE THREAD

**Issue by taula50** [rosenbjerg/FFMpegCore#144]
this is setting options:
 file1 = Properties.Settings.Default.DirBase + @"\exe";
            FFMpegOptions.Configure(new FFMpegOptions { RootDirectory = file1, TempDirectory= Properties.Settings.Default.DirBase + @"\temp" });

In directory Properties.Settings.Default.DirBase + @"\exe";
i have ffmpeg.exe and ffprobe.exe
And the use of FFProbe is:
 using (var stream = File.OpenRead(openDialog1.FileName))
                { 
                var mediainfo = FFProbe.Analyse(stream);
                }
it still throws the same ERROR fille not found

**Comment by taula50** [comment]
in fact now there is no error, but it never goes out of FFProbe.Analyse..... you can wait forever

**Comment by rosenbjerg** [comment]
Why do you use File.OpenRead instead of just passing the file path directly?

**Comment by taula50** [comment]
if i use durect the path to the file, it works. but when i use:

 var bitmap = FFMpeg.Snapshot(mediainfo, new System.Drawing.Size(Convert.ToInt32(ws), Convert.ToInt32(hs)), TimeSpan.FromMilliseconds(mymillisecons));
ws is the width and hs is the height... This function never end;
and if i use:
var donet=FFMpeg.Snapshot(mediainfo, DirBase+@"\images\o.jpg" , new System.Drawing.Size(Convert.ToInt32(ws), Convert.ToInt32(hs)), TimeSpan.FromMilliseconds(mymilliseconds));
returns a true but there is NO FILE in the directory DirBase+@"\images\o.jpg", that file not exists..
it is very curious.

**Comment by rosenbjerg** [comment]
I think your problem is that after the analysis, the stream containing the data's position will be at the end. So when Snapshot continues reading from that stream, there is no data. You would have to seek to the beginning in between the two operations

**Comment by taula50** [comment]
hmmmm and how i do that?.. shouldnt analyse fuction to reset the stream position?... what function resets thepsosition?if i do:
var mediainfo = FFProbe.Analyse(FileName);
//reset the stream here HOW?
var donet=FFMpeg.Snapshot(mediainfo, DirBase+@"\images\o.jpg" , new System.Drawing.Size(Convert.ToInt32(ws), Convert.ToInt32(hs)), TimeSpan.FromMilliseconds(mymilliseconds));
i dont have seen andy function to reset the stream pointer to cero.

**Comment by gabilan** [comment]
@taula50 Use a Seek method invocation or set Position on the Stream instance. In general it's not usually good practice to Seek on a provided stream. Seeking to the beginning of the stream provided to a library may seek to an unintended location. What if a seek isn't necessary at all because the file/data segment in the stream is a valid file? Also a stream may not be seek enabled at all. All these complexities can be worked out by the caller.

**Comment by rosenbjerg** [comment]
Thank you (once again) for helping with answering issues and giving very good descriptions, @gabilan
