### ISSUE TITLE
FromPipeInput to OutputToPipe leads to Exception

### ISSUE THREAD

**Issue by IsidorosT** [rosenbjerg/FFMpegCore#145]
Hi,
We try to pass native(h264)'s memory stream FromPipeInput and extract result from OutputToPipe . We want as a result a converted for mp4 container memory stream. We think that the problem is at pipe handling. Any thoughts???
Code:
MemoryStream Mp4Vid = new MemoryStream();
            StreamPipeSink MP4Stream = new StreamPipeSink(Mp4Vid);
            var processor = FFMpegArguments
                .FromPipeInput(new StreamPipeSource(nativeVideo),options => {
                    options.WithFramerate(framerate);
                    //.WithVideoCodec(VideoCodec.LibX264)*/;
                })
                .OutputToPipe(MP4Stream, opt =>
                {
                    //opt.ForceFormat("mp4");
                    //opt.WithVideoCodec(VideoCodec.LibX264);
                })
                .ProcessSynchronously();
We got Exception on Pipe.WaitForConnectionAsync(token).ConfigureAwait(false) (OutputPipeArgument.cs line:21)
that System.Threading.Tasks.TaskCanceledException: 'A task was canceled.'

**Comment by rosenbjerg** [comment]
The exception should be caught. Which version are you using?
Btw ffmpeg cannot output mp4 to a stream. So even if it werent for that exception, you use-case would not be possible. You would instead get the ffmpeg error: muxer does not support non seekable output

**Comment by IsidorosT** [comment]
Version is 4.3.1
So ffmpeg can output other formats in stream but not mp4??

**Comment by gabilan** [comment]
@IsidorosT MP4/MOV atoms require a seekable stream. For example, the "moov" atom contains all the movie information. You can't fully generate it until you've ended encoding. But it's **_usually_** the first atom, so it's at the beginning of the output. If you can't seek (such as with a pipe) you'd never be able to generate many legacy formats that have this limitation (AVI, MP4/MOV). The only alternative would be for the encoder to write the entire output to memory first (which might not even be possible) and then output that to your pipe -- obviously a non-starter. Some container formats (ex: Matroska) don't have this limitation.

MOV Atom Reference: https://developer.apple.com/library/archive/documentation/QuickTime/QTFF/QTFFChap2/qtff2.html

**Comment by rosenbjerg** [comment]
Thank you @gabilan for giving such a nice description of the problem he is facing.
@IsidorosT; depending on your needs, webm might be a suitable format for you, as gabilan also mentioned

**Comment by IsidorosT** [comment]
Yes i saw that other types like flv or ogv can do the work. Thank you
