### ISSUE TITLE
Missing #EXT-X-ENDLIST using hls_playlist_type event and CancellableThrough

### ISSUE THREAD

**Issue by MichaelScherf** [rosenbjerg/FFMpegCore#146]
When I try to record an RTSP stream using this parameter text:
-i rtsp://xxx.xxx.xxx.xxx/stream -f hls -hls_playlist_type event -hls_time 1 -vcodec copy ./video.m3u8
I have an issue with the resulting playlist.

After cancelling the recording using the CancellableThrough action, the written playlist's type is correctly set to #EXT-X-PLAYLIST-TYPE:EVENT, but there is a missing #EXT-X-ENDLIST. In this case, VLC isn't able to play the playlist, I have to add the end tag manually, then it's working

when I start the recording in console and quit the process hitting "Q", the playlist is correct.

**Comment by MichaelScherf** [comment]
here is my code:

`var options = new FFMpegOptions {RootDirectory = "D:\\video"};
FFMpegOptions.Configure(options);
var arguments = FFMpegArguments.FromUrlInput(new Uri("rtsp://x.x.x.x/stream1"))
			                               .OutputToFile("D:\\video\\output\\tmp.m3u8", true, AddOutputArguments);
_cancelRecording = Target;
arguments.CancellableThrough(out _cancelRecording).ProcessAsynchronously();`

the cancel:
`_cancelRecording.Invoke();`

**Comment by TFleury** [comment]
I have a similar issue capturing from a device with output to an mp4 file.

The `cancel` action sends 'q' to input but setting `Started` to false kills FFMpeg instance before it can exit. It results with a non finalized mp4 file which is unreadable.

In my case, commenting out `instance.Started = false;` solves the problem.

I think it needs a timeout before killing the process, or a distinct handler to initiate a clean stop.

**Comment by rosenbjerg** [comment]
I will release v 4.0.0 of this library soon, which will include @TFleury 's fix to cancellation with timeout
