### ISSUE TITLE
Getting black video that can't play

### ISSUE THREAD

**Issue by veler** [rosenbjerg/FFMpegCore#149]
Hello,

Thank you for this wrapper :) I was looking for a while for one that supports streaming to `ffmpeg.exe` without passing through `avcodec.dll`.

Sadly, I'm hitting an issue with it. I'm trying to create an MP4 from a set of screenshots took with the [Desktop Duplication API](https://docs.microsoft.com/en-us/windows/win32/direct3ddxgi/desktop-dup-api).

**Here is what my program does:**
1. Do a screenshot. I receive a SharpDX's Texture2D object. It's basically a DirectX texture that contains all the pixels of the screenshot in `B8G8R8A8 unsigned integer`.
2. I extract all the pixels of this texture to a byte array. Alternatively, I can also generate a Bitmap from it.
3. I send this byte array to a custom `IPipeSource` and `IVideoFrame` I made because I need to be able to "wait for the next frame to be capture by DirectX".

But the final MP4 file seems to be corrupt. When I open in Windows Media Player or Movie & TV on Windows 10, the screen stays black and pressing Play doesn't play. The video length showed by the player seems accurate though.

I'm trying to understand what I messed up but don't find it. Maybe it's a bug in the wrapper, or there's definitely something wrong I'm doing but I don't find what. Can you please help me? :)

**A few additional notes:**
1. Converting the Texture2D to a byte array, then generating a Bitmap from this byte array and saving it on the hard drive works like a charm, which means the byte array is probably fine.
2. Encoding a video through `avcodec.dll` actually works :) (with another open source wrapper). This confirms again that my input is probably good (at least with this other wrapper).

**Some of my code**
```chsarp
 var screenCaptureVideoPipeSource
    = ScreenCaptureVideoPipeSource(
        _screenRecord /* a class that let me know when a new frame has been captured. */);

var ffmpegArguments
    = FFMpegArguments.FromPipeInput(screenCaptureVideoPipeSource);

 var ffmpegArgumentProcessor
    = ffmpegArguments.OutputToFile(
        filePath,
        overwrite: true);

await ffmpegArgumentProcessor.ProcessAsynchronously(throwOnError: true).ConfigureAwait(false);
```

I also tried with various arguments on the OutputToFile:

```
(FFMpegArgumentOptions fFMpegArgumentOptions) =>
                    {
                        fFMpegArgumentOptions
                        .WithVideoCodec(VideoCodec.LibX264)
                        .WithConstantRateFactor(21)
                        .WithAudioCodec(AudioCodec.Aac)
                        .WithVariableBitrate(4)
                        .WithFastStart()
                        .Scale(VideoSize.Original);
                    });
```

(I tried to play with these arguments and change values).

`GetStreamArguments` returns the following:
```
return $"-f rawvideo -r 30 -pix_fmt bgra -s 800x600";
```

Note that the string isn't hardcoded this way but I show it this way so it's simplified :) I chose `bgra` since it's the format I'm using in DirectX and when I encode to a Bitmap that I'm saving on the hard drive.

In my `IPipeSource.WriteAsync` implementation, I sometimes do a `await Task.Delay` between 100 and 200ms. I wonder if it can have an impact.
To write the data, I'm doing a simple `await pipe.WriteAsync(byteArray, 0, byteArray.Length, token);`.

No exception is thrown anywhere.
I tried using ffmpeg 4.2, 4.2.1 and 4.3.1.
I also tried to convert my byte array to a Bitmap and use the same implementation than in `BitmapVideoFrameWrapper` to write the data to the pipe, but the result is the same.

Any idea of what's going on, or what I should try to debug?

Thank you in advance :)

**Comment by veler** [comment]
Forgot to mention something else: it seems like the `NamedPipeServerStream` get broken when using hardware acceleration for some reason. Is that by design? (I admit I'm very new at ffmpeg ^^)

**Comment by rosenbjerg** [comment]
Hello veler, sounds like an interesting use-case :)
Could you try to output your raw content into a temporary file and then use that file as input to ffmpeg? Just to find out if the problem is related to the use of `NamedPipeServerStream ` or not.
I wouldn't think that the await Task.Delay is the source of the problem though.
And no, I did not know there was a problem with NamedPipeServerStream when using hardware acceleration, please tell me more.

**Comment by veler** [comment]
Hello,
Sure, I can try that later today.
For the hardware acceleration, I don't know how related it is to the pipe but every time I was enabling either hardware acceleration and was writing to the pipe stream (in SerializeAsync), I was getting an exception saying "The pipe has been closed" without further helpful information (no inner exception, nothing special in the stack trace) and `ffmpeg.exe` stopped. Sounds like a crash in ffmpeg for some reason.

**Comment by max619** [comment]
@veler Hello,

I have seen use of same technique in [Captura](https://github.com/MathewSachin/Captura) if you can take look at it and implement support in this library it would be very appreciated :)

**Comment by rosenbjerg** [comment]
@veler Hi again,
I have just uploaded v. 4.1.0 of this library to nuget containing #177 and #191, the first of which might be relevant due to it enabling the use of screen recording using ffmpeg. I'm not sure if that is actually suited for your usecase though

**Comment by rosenbjerg** [comment]
Closed due to inactivity

**Comment by GF-Huang** [comment]
Same issue for me.

In general, `WgcCapturer` is a desktop capture tool. `FrameCaptured` will be called every time a frame is captured.

The final `1.mp4` was broken, windows media player said it is bad. But its video length seems right.



```cs
using System.Diagnostics;
using System.Drawing;
using System.Drawing.Imaging;
using FFMpegCore;
using FFMpegCore.Extensions.System.Drawing.Common;
using FFMpegCore.Pipes;
using System.Collections.Concurrent;

var videoFrames = new BlockingCollection<IVideoFrame>();

using var capturer = new WgcCapturer { NumberOfFramePoolBuffers = 2 };

if (OperatingSystem.IsWindowsVersionAtLeast(10, 0, 19041))
    capturer.IsCursorCaptureEnabled = false;

int frames = 0;
var watch = Stopwatch.StartNew();

capturer.FrameCaptured += (WgcCapturer capturer, ReadOnlySpan<byte> frameData, Size frameSize) => {
    frames++;

    using var bitmap = new Bitmap(frameSize.Width, frameSize.Height, PixelFormat.Format32bppArgb);
    var data = bitmap.LockBits(new Rectangle(Point.Empty, frameSize), ImageLockMode.WriteOnly, PixelFormat.Format32bppArgb);

    unsafe {
        frameData.CopyTo(new Span<byte>(data.Scan0.ToPointer(), frameData.Length));
    }

    bitmap.UnlockBits(data);

    videoFrames.Add(new BitmapVideoFrameWrapper((Bitmap)bitmap.Clone()));

    if (watch.Elapsed.TotalSeconds >= 1) {
        //bitmap.Save(Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.Desktop), "1.png"));

        Console.WriteLine($"FPS: {frames / watch.Elapsed.TotalSeconds:N1}");
        frames = 0;
        watch.Restart();
    }
};
capturer.Start();
Console.WriteLine("Capturer running...");

Console.Read();
capturer.Stop();
videoFrames.CompleteAdding();

Console.WriteLine("Waiting FFMpeg...");

await FFMpegArguments.FromPipeInput(new RawVideoPipeSource(videoFrames.GetConsumingEnumerable()) { FrameRate = 30 })
                     .OutputToFile(Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.Desktop), "1.mp4"),
                                   addArguments: o => o.WithVideoCodec(FFMpegCore.Enums.VideoCodec.LibX264))
                     .NotifyOnProgress(ts => Console.WriteLine(ts))
                     .ProcessAsynchronously();

```

**Comment by GF-Huang** [comment]
I solve this issue by myself. It seems because the `BitmapVideoFrameWrapper` convert `PixelFormat.Format32bppArgb` to `bgra` rather than `yuv420p`.

![image](https://github.com/rosenbjerg/FFMpegCore/assets/4510984/f036be43-0aba-4316-926e-9cdf1a44461f)

So I convert the app-generated `1.mp4` to `2.mp4` with `yuv420p` format by `ffmpeg.exe -i 1.mp4 -c:v libx264 -pix_fmt yuv420p 2.mp4`. `2.mp4` now can playable by windows media player.
