### ISSUE TITLE
No file found with URL specified

### ISSUE THREAD

**Issue by chticer** [rosenbjerg/FFMpegCore#150]
I am trying to analyze some videos of mine that are hosted on the cloud and keep getting a FFMpegException thrown with the message `'No file found at 'http://somewebsite.com/somefile.mp4''` using `FFProbe.Analyse("http://somewebsite.com/somefile.mp4").Duration;`. I have gotten it to work in the past but I only use this program once a year so I was unable to detect this issue earlier. The videos are accessible on the Internet as I can view them with Chrome and even tested a hardcoded link of a video from a public test video bank. I went back to try earlier versions and see which version broke this and it seems that v3.0.0 was the last version that worked as I get the exception on v3.1.0.

**Comment by rosenbjerg** [comment]
You need use pass an Uri instead of a string. So basically `new Uri("http://somewebsite.com/somefile.mp4")`

When passing a string, a file path is assumed, and existance is checked.
When passing a Uri, existance is not checked
