### ISSUE TITLE
怎么采集声卡?

### ISSUE THREAD

**Issue by fgh345** [rosenbjerg/FFMpegCore#153]
请问支持dshow吗?

**Comment by tiesont** [comment]
FFMpegCore只是ffmpeg的.NET包装器-无论支持什么，这都可以。 https://trac.ffmpeg.org/wiki/DirectShow似乎表明会。

请注意，这是来自Google翻译的文字，对于任何语法错误，我们深表歉意。

**Comment by fgh345** [comment]
FromFileInput,FromPipInput 等等 这些好像都不能填入 dshow参数 (ffmpeg -f dshow -i audio="virtual-audio-capturer" 例如这个)




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Tieson Trowbridge"<notifications@github.com&gt;; 
发送时间: 2021年1月4日(星期一) 中午12:06
收件人: "rosenbjerg/FFMpegCore"<FFMpegCore@noreply.github.com&gt;; 
抄送: "君值韶华莫等闲"<1145073867@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [rosenbjerg/FFMpegCore] 怎么采集声卡? (#153)





 
FFMpegCore只是ffmpeg的.NET包装器-无论支持什么，这都可以。 https://trac.ffmpeg.org/wiki/DirectShow似乎表明会。
 
请注意，这是来自Google翻译的文字，对于任何语法错误，我们深表歉意。

**Comment by tiesont** [comment]
您将需要使用https://github.com/rosenbjerg/FFMpegCore/blob/master/FFMpegCore/FFMpeg/Arguments/CustomArgument.cs 创建一个自定义参数-DirectShow没有任何预定义的参数

**Comment by fgh345** [comment]
好的 谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Tieson Trowbridge"<notifications@github.com&gt;; 
发送时间: 2021年1月4日(星期一) 下午5:26
收件人: "rosenbjerg/FFMpegCore"<FFMpegCore@noreply.github.com&gt;; 
抄送: "君值韶华莫等闲"<1145073867@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [rosenbjerg/FFMpegCore] 怎么采集声卡? (#153)





 
您将需要使用https://github.com/rosenbjerg/FFMpegCore/blob/master/FFMpegCore/FFMpeg/Arguments/CustomArgument.cs创建一个自定义参数-DirectShow没有任何预定义的参数

**Comment by rosenbjerg** [comment]
Closing this one since the inquiry seems resolved
Thank you @tiesont
