### ISSUE TITLE
Snapshots from stream-data fails

### ISSUE THREAD

**Issue by BetaD** [rosenbjerg/FFMpegCore#155]
Taking snapshots from stream-data fails. Here is an simple example.
```c#
using FFMpegCore;
using System;
using System.Drawing;
using System.IO;

namespace SnapshotFromStreamsource {
    class Program {
        static void Main(string[] args) {
            //Set Directory for ffmpeg-Binaries
            FFMpegOptions.Configure(new FFMpegOptions() {
                RootDirectory= @"D:\Software\ffmpeg\3.4"
            });
            //Read Example-File. In real-life the stream comes from a Zip-archive.
            Stream stream = File.OpenRead(@"D:\Tests\input_3sec.mp4");

            var mediaFileAnalysis = FFProbe.Analyse(stream);
            // process the snapshot in-memory and use the Bitmap directly
            var bitmap = FFMpeg.Snapshot(mediaFileAnalysis, new Size(200, 400), TimeSpan.FromSeconds(1));
        }
    }
}
```
The program crashes at `FFMpeg.Snapshot`. Error message says:

ffmpeg version 3.4 Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 7.2.0 (GCC)
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-bzlib --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-cuda --enable-cuvid --enable-d3d11va --enable-nvenc --enable-dxva2 --enable-avisynth --enable-libmfx
  libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100
**\\.\pipe\FFMpegCore_4b5c1c8a-33bb-40ea-812d-1e33c6f74336: No such file or directory**

Maybe the problem occurs, because `FFProbe.Analyse` closed the pipe. If this is right, a possible solution can be a opening of a new pipe with same name and stream-data.

**Comment by rosenbjerg** [comment]
Yeah I'm considering removing the overload that accepts a IMediaAnalysis to avoid having to answer issues about it. There are several reasons why it won't work. One being that the stream is closed, so the "file" is gone. Even if the stream would stay open, so the "file" kept existing, it still would need to be seeked back to the beginning.
So yes, I know of this issue, you are not the first one to have it. The only good solution I see is to remove the overload or throw an exception to inform users that this is unsupported and will remain so.
You can use the stream, but you would have to seek it to the beginning before passing the Stream it self as an argument to Snapshot
