### ISSUE TITLE
Status of operation

### ISSUE THREAD

**Issue by RiccardoManzan** [rosenbjerg/FFMpegCore#156]
Hi,
I am building a console application, i would like to show a status bar, or a percent during encode/decode processes.
Is there any way?

Thankyou

**Comment by rosenbjerg** [comment]
See `NotifyOnProgres`
https://github.com/rosenbjerg/FFMpegCore/blob/master/FFMpegCore/FFMpeg/FFMpegArgumentProcessor.cs#L32
