### ISSUE TITLE
[Question] Check if a file is a video

### ISSUE THREAD

**Issue by Hona** [rosenbjerg/FFMpegCore#157]
Is there a way to check if any given file is a video?

I attempted this but it seems to work, is there another way? The end goal is to transcode every non mp4 file into mp4

```cs
var mediaAnalysis = await FFProbe.AnalyseAsync(filePath);

// TODO: Does this work (check if file is video)
return mediaAnalysis.VideoStreams.Any() ? filePath : null;
```

**Comment by tiesont** [comment]
You would check the "magic bytes" at the beginning of the file, which would tell you what format you're working with. The signature of each format varies, so it's not really practical to include that in this library, I think.

I would assume the primary video stream is null if the file analyzed is not a video, so something like this is a quick and dirty check:

```cs
var mediaInfo = FFProbe.Analyse(filePath);
var videoInfo = mediaInfo.PrimaryVideoStream;
```

`videoInfo` will be null for anything not a video.

I've had success extending the https://github.com/neilharvey/FileSignatures project to add the video formats that are relevant to me, if that's the route you want to go. For example, these are the first four bytes for a WEBM container video:

```cs
0x1A 0x45 0xDF 0xA3
```

MP4 is typically this,

```cs
0x66 0x74 0x79 0x70
```

so you could just look for that and convert anything that doesn't match.

**Comment by Hona** [comment]
Interesting. Thanks for the response. 

As a temporary workaround I blindly checked file extensions, but thanks for the insight on a better way

**Comment by rosenbjerg** [comment]
See the `Format` property of the media analysis object

**Comment by tiesont** [comment]
@rosenbjerg Figures that I would miss the obvious. Thanks.

**Comment by rosenbjerg** [comment]
@tiesont Using the "magic bytes" would be a faster solution if no file extension filtering is performed I bet, and all files in a directory needs to be processed no matter what file extension, with non-media files just being ignored. 
Just based on the fact that ffprobe will read much more that just the magic bytes at the start of the file
