### ISSUE TITLE
Resize Error

### ISSUE THREAD

**Issue by alllucky1996** [rosenbjerg/FFMpegCore#158]
I want to change the size of the video from hd to full hd. with this command is ok but using the library as the following code get the exception message : "FFMpegCore.Exceptions.FFMpegException: FFMpeg exited with non-zero exitcode."
the command line
// ffmpeg -i in.mp4 -vf scale=1920:1080,setsar=1:1 out3.mp4
run code throw excepton: 
` string inFile = @"E:\Rac\bachung\in.mp4";
  string outputFile = @"E:\Rac\bachung\out3.mp4";
 var result =   FFMpegArguments
.FromFileInput(inFile)
.OutputToFile(outputFile, true, opt => opt
    .Resize(1920, 1080))
.ProcessSynchronously(true);
Assert.IsFalse(result);
 }
`

**Comment by rosenbjerg** [comment]
It very rarely makes sense to upscale an image like that. It will just take up more space without any real visual improvement.
Could you include the content of the FfmpegErrorOutput prop on the exception?

**Comment by rosenbjerg** [comment]
Anyway, .Scale(..) does not include `setar=1:1` so you might have to replace that with `.WithCustomArgument("-vf scale=1920:1080,setsar=1:1")`

Then the arguments for ffmpeg through FFMpegCore will be exactly the same as the command line arguments
