### ISSUE TITLE
Get all frames

### ISSUE THREAD

**Issue by Almeonamy** [rosenbjerg/FFMpegCore#16]
Hi. How can I enumerate all frames? Frame by frame. There is method `Stapshot`, but this method get snapshot by TimeSpan. I need all frames without TimeSpans.

**Comment by ryanlin1986** [comment]
I need this feature as well.

**Comment by vladjerca** [comment]
The library is built on top of an [ArgumentBuilder](https://github.com/vladjerca/FFMpegCore#argumentbuilder).

Arguments can be implemented locally to suite your projects needs. If you want to integrate that Argument into the lib, feel free to open a `Pull Request`.

Here's a `gist` with some frame extraction examples 👌

https://gist.github.com/loretoparisi/a9277b2eb4425809066c380fed395ab3
