### ISSUE TITLE
mp4 to hls

### ISSUE THREAD

**Issue by RobertoGemo** [rosenbjerg/FFMpegCore#160]
hi,
i can't find how to convert mp4 to hls.
Could you provide an example please?

using ffmpeg.exe from console with this command:
ffmpeg -i input\xxxxx.mp4 -vf scale=w=1000:h=1000:force_original_aspect_ratio=decrease -c:a aac -ar 48000 -c:v h264 -profile:v main -crf 20 -sc_threshold 0 -g 48 -keyint_min 48 -hls_time 2 -hls_playlist_type vod -b:v 1400k -maxrate 1498k -bufsize 2100k -b:a 128k -hls_segment_filename xxxxx_%%d.ts xxxxx.m3u8 

i obtain an mru8 file and the *.ts file correctly splitted
thank you

**Comment by tiesont** [comment]
Pretty much anything that isn't predefined can be run as a custom argument, using https://github.com/rosenbjerg/FFMpegCore/blob/master/FFMpegCore/FFMpeg/Arguments/CustomArgument.cs

There are examples of how to use CustomArgument in the test suite. For example, https://github.com/rosenbjerg/FFMpegCore/blob/89fdef4766dc1a921fe58c9dfe784bfcd6080722/FFMpegCore.Test/ArgumentBuilderTest.cs#L301

**Comment by RobertoGemo** [comment]
hi @tiesont and thanks for the answer.
i tried to user custom argument, but the main problem is that converting an mp4 to an hls stream does not genete only one file.
WIth the example string i posted yesterday i should obtain an .m3u8 playlist and several *.ts file.
that is the format in which mp4 can be converted to make them "streamable" over internet.
in this case, even managing to use correctly the customargument property... what should i use as first parameter of OutputToFile("output.mp4"..... ?

**Comment by rosenbjerg** [comment]
You should easily be able to piece together the exact same ffmpeg arguments using custom arguments. 
I.e. `[...].WithCustomArgument("-hls_segment_filename xxxxx_%%d.ts").OutputToFile("xxxxx.m3u8")`

As @tiesont also mentions; any ffmpeg argument that isn't directly supported through named methods are still indirectly supported though CustomArgument
