### ISSUE TITLE
System.Text.Json.JsonException: '0xE9' is an invalid escapable character within a JSON string. 

### ISSUE THREAD

**Issue by 3400442579** [rosenbjerg/FFMpegCore#163]
**await FFMpegCore.FFProbe.AnalyseAsync(fn);**

System.Text.Json.JsonException: '0xE9' is an invalid escapable character within a JSON string. The string should be correctly escaped. **Path: $.format.filename** | LineNumber: 0 | BytePositionInLine: 3158. ---> System.Text.Json.JsonReaderException: '0xE9' is an invalid escapable character within a JSON string. The string should be correctly escaped. LineNumber: 0 | BytePositionInLine: 3158.
   在 System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   在 System.Text.Json.Utf8JsonReader.ConsumeStringAndValidate(ReadOnlySpan`1 data, Int32 idx)
   在 System.Text.Json.Utf8JsonReader.ConsumeString()
   在 System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
   在 System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   在 System.Text.Json.Utf8JsonReader.Read()
   在 System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   在 System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   在 System.Text.Json.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   在 System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   在 System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   在 System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
   在 System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   在 System.Text.Json.JsonSerializer.ReadCore[TValue](Utf8JsonReader& reader, Type returnType, JsonSerializerOptions options)
   在 System.Text.Json.JsonSerializer.Deserialize[TValue](String json, Type returnType, JsonSerializerOptions options)
   在 FFMpegCore.FFProbe.ParseOutput(String filePath, Instance instance)
   在 FFMpegCore.FFProbe.<AnalyseAsync>d__3.MoveNext()

json:
[err.txt](https://github.com/rosenbjerg/FFMpegCore/files/5892295/err.txt)

**Comment by rosenbjerg** [comment]
Maybe you need to set encoding through `FFMpegOptions.Encoding`?
