### ISSUE TITLE
Input piping approach hanging?

### ISSUE THREAD

**Issue by chelseatools48** [rosenbjerg/FFMpegCore#164]
Hi, I am trying to test out this library to process in memory images into an output video file. I have been following the Input Piping section of the readme, though when I try and run it, my program simply hangs after ProcessSynchronously(). It seems to create the initial output video, but that's all. No exceptions are thrown either, so I'm not sure what's wrong. Any pointers to what I'm missing/doing wrong would be great.

This is the code I'm using (for now just loading 100 images from my local drive as a test):

```
            ICollection<IVideoFrame> frames = new List<IVideoFrame>();
            foreach (var file in Directory.GetFiles(@"D:\images\"))
            {
                frames.Add(new BitmapVideoFrameWrapper(new Bitmap(file)));
            }

            var videoFramesSource = new RawVideoPipeSource(frames)
            {
                FrameRate = 20
            };
            try
            {
                var processor = FFMpegArguments
                    .FromPipeInput(videoFramesSource)
                    .OutputToFile("temporary.mp4", true)
                    .NotifyOnProgress(o => Log.Debug(o.ToString()))
                    .ProcessSynchronously();
            }
            catch (Exception ex)
            {
                Log.Error(ex.StackTrace);
            }

            Log.Debug($"Done");
            Console.ReadKey();
```
There's no exceptions and no log outputs from NotifyOnProgress.

I am using ffmpeg 4.2, with FFMpegCore version 3.3 in a NET Core 3.1 console app.

**Comment by chelseatools48** [comment]
I figured it out - might be a potential bug. It seems that if the input images are not all the same size, this causes the hanging issue. I had a few that were 1280x960 with the majority being 1280x720. Removin the 960 width images, it works perfectly. Should this throw some form of error when this happens?

**Comment by rosenbjerg** [comment]
Interesting find. Maybe that could be solved by adding a resize argument? So that hopefully ffmpeg will resize each image to the specified size, which would allow for creating a video from them?

**Comment by chelseatools48** [comment]
That could be useful and would hopefully remedy the issue - perhaps with a note to use the resize argument if the input images cannot be guaranteed to all be the same size? If the resize failed, perhaps ffmpeg would throw up a potentially helpful error at least.

I wonder what ffmpeg is actually doing under the hood, I might try and run the equivalent commands directly with the ffmpeg binary on these images and see what happens out of curiosity.

**Comment by rosenbjerg** [comment]
@cameron2134 have you seen Max's answer, where he mentions this issue?

**Comment by rosenbjerg** [comment]
Closing this one since you found the source of the problem. Please keep me posted if you find out which ffmpeg seemingly stops but doesn't quit. Then I'll try to harden the library against that :)
