### ISSUE TITLE
Win32Exception: The system cannot find the file specified.

### ISSUE THREAD

**Issue by simonjpearson** [rosenbjerg/FFMpegCore#166]
Hello!

Using FFMpegCore I'm looking to see if I can take an mp4 from an IFormFile upload, and convert to HLS (m3u8) format.  For testing purposes, I'm going to store the file locally on my PC.

- ASP.NET Core 5.0 - Web Application using MVC
- Webserver is Kestrel
- IDE is Visual Studio 2019 on Windows 10
- I've installed FFMpegCore through NuGet (v3.3.0)

I'm getting an error when calling `.OutputToFile` ...

**_Win32Exception: The system cannot find the file specified.
System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)_**

Here is my controller code:
`
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UploadVideo(IFormFile FormFile)
        {
            var currentDirectory = Path.GetDirectoryName(Assembly.GetEntryAssembly().Location);
            var destination = Path.Combine(currentDirectory, "videos\\\record.m3u8");

            using (var memoryStream = new MemoryStream())
            {
                //Copy the FormFile into a memory stream
                await FormFile.CopyToAsync(memoryStream);

                await FFMpegArguments
                    .FromPipeInput(new StreamPipeSource(memoryStream))
                    .OutputToFile(destination, true, options => options
                        .WithVideoCodec(VideoCodec.MpegTs)
                        .WithConstantRateFactor(21)
                        .WithAudioCodec(AudioCodec.Aac)
                        .WithVariableBitrate(4)
                        .WithFastStart()
                        .Scale(VideoSize.Hd))
                    .ProcessAsynchronously();
            }
            return View();
        }
`

Did I do something wrong, or is there something you can suggest to check?

Thank you!

**Comment by simonjpearson** [comment]
Didn't have FFMpeg installed

**Comment by rosenbjerg** [comment]
One problem that I also see with your example is that you don't Seek the memorystream back to the beginning before passing, and secondly, ffmpeg does not support encoding/decoding mp4 from stream. It must be able to seek.
A solution to both would be to save the FormFile to a temp file, pass that path to ffmpeg for processing, and then delete the temp file afterwards

**Comment by simonjpearson** [comment]
Thanks Malte, yes I figured out much today - and storing the stream to file was the second thing (the first being that I hadn't installed FFMpeg on my new PC ... duh!)

**Perhaps you can help once more though?**

I want to take the input video and output the m3u8 manifest, along with multiple .ts files.

1. Do I need to recursively call the Convert() function with the various sizes to get the multiple .ts files?
2. Which function would create the m3u8 manifest file?

Thank you for any response here!

Simon

**Comment by rosenbjerg** [comment]
Hi again Simon,
Your goal could possible be achieved with a ffmpeg command similar to [this](https://gist.github.com/lukebussey/4d27678c72580aeb660c19a6fb73e9ee), which should be possible with FFMpegCore as well, though not all of those arguments are directly supported, but indirectly supported through WithCustomArgument(..)
