### ISSUE TITLE
Streaming processed frames

### ISSUE THREAD

**Issue by martingra** [rosenbjerg/FFMpegCore#168]
Hi.

I have a quite particular scenario, that I can't figure out how to solve.
I have a C# WPF App that takes frames from a camera, process them using EmguCV, and at the end, needs to send the frames to a web app in real time.

It is the same as a video-conference, with the only difference, that the video frames are "changed" in the WPF app using Emgu.
My main question is how to handle real time encoding of frames, to send them with no delay, since the solution I found in the samples consist of creating an Out Pipe with a set of frames, which may not be a good approach if I have to wait to collect a set of frames before sending them:

```
using var resStream = new MemoryStream();
var reader = new StreamPipeSink(resStream);
var writer = new RawVideoPipeSource(CreateFrames(30));

FFMpegArguments
    .FromPipeInput(writer)
    .OutputToPipe(reader, opt => opt
        .WithVideoCodec("vp9")
        .ForceFormat("webm"))
    .ProcessSynchronously();
```
My idea is to integrate this with webRTC to be able to stream the frames in real time, but I am not sure if I am in the correct path. I would like to create a solution with a WPF serving frames to a encoded stream, which are received in the web client.

Thanks

**Comment by rosenbjerg** [comment]
Since you are encoding to webm, you should be able to stream directly to the response body stream of the web request you want to respond with video to. The webm format is designed to be streamed directly without no client-side seeking, like the mp4 format requires.
So maybe something like `new StreamPipeSink(Response.Body)` as destination, so that you don't wait until the frames have been processed before sending.

**Comment by martingra** [comment]
Thanks for your answer!

Does it make sense to work with the RawVideoPipeSource input with a certain amount of frames  (e.g. 30)?

I mean, I have a live transmission, so I have an undetermined number of frames that are being generated after processing with EmguCV my camera input. Following max619 comment on  #56, I wanted to create a BlockingCollection<IVideoFrame> of "frames to send", and then, consume them in batches of for example, 30 frames.

So, the idea is, keep frames in my collection, when I have 30 of them, encode and send those 30, remove them from the collection, send the following 30, and so on. Is this correct? Or should I add frames in that collection, and do var writer = new RawVideoPipeSource(CreateFrames()); consuming all the frames (those already there and the ones that are being added) without encoding in batches?

Thanks!

**Comment by martingra** [comment]
Thanks for you answer! It has been very helpful!

I am not able to stream the webm stream to my <video> tag, but it is very slow.

I am implementing something like a video-conference software, with the EmguCV processor in the middle, so it is very important for me to have a close to real time stream.

I think I may be doing something wrong with my parameters. This is the method I am calling as source of the video tag:

```
private void GetVideoStream()
{
    _framesToStream = new BlockingCollection<IVideoFrame>();

    _cameraTask = ConectToCamera(); // run a background task that takes frames from the input, process them with EmguCV and add all the frames to the _framesToStream BlockingCollection.

    var reader = new StreamPipeSink(Response.Body);
    var writer = new RawVideoPipeSource(_framesToStream.GetConsumingEnumerable())
    {
        FrameRate = 40
    };
    
    FFMpegArguments
        .FromPipeInput(writer)
        .OutputToPipe(reader, opt => opt
            .WithVideoCodec("vp8")
            .ForceFormat("webm")
            .WithFramerate(40)
            .WithFastStart()
            .WithVideoBitrate(5000)
            .WithSpeedPreset(FFMpegCore.Enums.Speed.UltraFast)
            //.WithVariableBitrate(4)
            //.Scale(FFMpegCore.Enums.VideoSize.Ld)
            )
        .ProcessSynchronously();
}
```

I am using 40 as FrameRate for both, input and output, since that is the FPS of my frames processor, but I don't know if it makes sense.

I think I have a bottleneck in the encoder, but I am not sure, since the BlockingCollection is not growing too much, so there is no reason to think that the producer is much faster than the producer.

Another question: is there is any way to avoid streaming all the frames, and give priority to stream only the new frames, to avoid delays in the viewer?

What is the meaning of the FrameRate parameters for both, the input and the output pipes?

**Comment by rosenbjerg** [comment]
Have you set the content type header for the response? That is also quite important for the browser recognize it as playable

**Comment by martingra** [comment]
Yes, I set the content type to video/webm, and I am able to get the video in the browser, but I have a huge latency (close to 20 seconds) and the video hangs easily.  

I was thinking in changin the codec from vp8 to h264, but it is not working. Can h264 be used when using a RawVideoPipeSource?

**Comment by max619** [comment]
@martingra I think it would be better to use rtmp (#179) for lower latency streaming. 
Or even better if you would use WebRTC, it designed for video-conference applications.
