### ISSUE TITLE
FFMpeg.Snapshot() hanging in WPF

### ISSUE THREAD

**Issue by SkylerA** [rosenbjerg/FFMpegCore#169]
### Steps to reproduce
(I'm using visual studio 2019 community on a win64 machine and my projects seem to default to .net framework 4.7.2 when applicable):

- File > New > Project
- Type WPF into the search field
- Select WPF App (.Net Framework) or (.Net), both will hang with slightly different results.
- Add the FFMPegCore nuget package (Tools > Nuget > Package Manager Console,  Install-Package FFMpegCore)
- Add the following code to your main block, filling in the ffmpeg and video paths of your system

```
FFMpegCore.FFMpegOptions.Configure(new FFMpegCore.FFMpegOptions { RootDirectory = @"", TempDirectory = @"" });
string filePath = @"";
var mediaAnalysis = FFMpegCore.FFProbe.Analyse(filePath);
var bitmap = FFMpegCore.FFMpeg.Snapshot(mediaAnalysis);
```

### Outcome
A WPF .net console app will hang in SynchronizationContext.WaitHelper(). My personal project is a WPF .net framework and when i installed a debug copy of FFMPegCore, i found the hang in
FFMpegArgumentProcessor.ProcessSynchronously() although i couldn't go deeper as the C# task system is a bit foreign to me
```
Task.WaitAll(instance.FinishedRunning().ContinueWith(t =>
{
    errorCode = t.Result;
    cancellationTokenSource.Cancel();
    _ffMpegArguments.Post();
}), _ffMpegArguments.During(cancellationTokenSource.Token));
```

In contrast, doing these steps for a non-wpf .net or .net framework console application seems to work fine.

### Clues and Guesses
One thing i noticed was that when running the Video_Snapshot_InMemory() test included with the source, it outputs this:
```
Disconnecting NamedPipeServerStream on OutputPipeArgument
Disposing NamedPipeServerStream on OutputPipeArgument
```

Where as my project that hangs only seemed to output:
``` 
Disposing NamedPipeServerStream on OutputPipeArgument`
```

So my very uneducated guess is the Task.WaitAll is stuck waiting for a Disconnection of the OutputPipe that's failing for some reason.

At one point i got the impression it might be something about firing in a gui thread altho i wasn't able to find anything concrete.

Sorry if I'm missing something obvious, i was only able to find the main read.me on the github for documentation.

### Thanks!
Really appreciate your work on this! I'm looking forward to integrating ffmpegCore into my project!

**Comment by rosenbjerg** [comment]
I have added ConfigureAwait(false) several places in v4.0.0, since I suspected that this might be what is causing your issue since you are using WPF. Could you try upgrading?

**Comment by roman-miniailov** [comment]
I have the same issue, but in WinForms app, button click event.

> Exception thrown: 'System.OperationCanceledException' in mscorlib.dll
> Disposing NamedPipeServerStream on OutputPipeArgument

Source code is pretty simple.
`var bitmap = FFMpeg.Snapshot(inputPath, new Size(200, 400), TimeSpan.FromMinutes(1));`

MP4 file on source.

**Comment by SkylerA** [comment]
> I have added ConfigureAwait(false) several places in v4.0.0, since I suspected that this might be what is causing your issue since you are using WPF. Could you try upgrading?

I updated my project and tried a fresh copy and both are still hanging. Try the steps in the original filing for the hang. Note that with 4.0 syntax appears to have changed a bit so here is my new code. README still mentions old syntax so I could be missing a step:

```
FFOptions options = new FFOptions();
options.BinaryFolder = @"your path";
options.TemporaryFilesFolder = @"your path";
GlobalFFOptions.Configure(options);

var mediaAnalysis = FFProbe.Analyse(@"your path");
var bitmap = FFMpeg.Snapshot(@"your path", captureTime: new TimeSpan(0,0,4));
```

**Comment by rosenbjerg** [comment]
@SkylerA  do you get the same behavior when using the async version: `FFMpeg.SnapshotAsync` ?

**Comment by SkylerA** [comment]
Looks like it at least completed the operation w/ Async, didn't test the output as i've had to move away from this project for the time being.

**Comment by rosenbjerg** [comment]
Thank you for that result. It think this is related to the synchronization context in WPF since `FFMpeg.SnapshotAsync` seems to be working. `FFMpeg.SnapshotAsync` uses `ConfigureAwait(false)` internally.
I'll close this issue for now due to inactivy, but please reopen if you continue on your project where you need `FFMpeg.Snapshot`
