### ISSUE TITLE
Help needed

### ISSUE THREAD

**Issue by mcopur** [rosenbjerg/FFMpegCore#171]
Hi,

I am trying to extract audio from a video from ".m3u8" URL. It works with this command which is stated below but I could not find how can I do that with your library. Is that possible? If so, could you please help me with that?

`ffmpeg -i "https://blablabla/playlist.m3u8" -acodec mp3 -ab 128k test.mp3`

**Comment by gillonba** [comment]
From the readme:

Save audio track from video:
FFMpeg.ExtractAudio(inputVideoFilePath, outputAudioFilePath);

**Comment by rosenbjerg** [comment]
thank you @gillonba
