### ISSUE TITLE
Join with parameter

### ISSUE THREAD

**Issue by kazmie** [rosenbjerg/FFMpegCore#172]
Hai

How i want to pass parameter to join function

-safe 0 -f concat -segment_time_metadata 1 -i D:\\video_list.txt -vf select=concatdec_select -af aselect=concatdec_select,aresample=async=1 D:\\ResultNoSound.mp4");

**Comment by rosenbjerg** [comment]
You can use `.WithCustomArgument` for any ffmpeg argument not directly supported through a specific extension method. That will allow you to execute your example ffmpeg command
