### ISSUE TITLE
RawVideoPipeSource FrameRate int or double?

### ISSUE THREAD

**Issue by gillonba** [rosenbjerg/FFMpegCore#173]
Is there a reason the FrameRate property of RawVideoPipeSource is an int instead of a double?  I am doing some video manipulation that involves splitting a video into its component frames, modifying each frame, and recombining them, and am running into issues where videos with a fractional frame rate ex: 23.5 fps do not recombine correctly since I can only re-encode at 23 or 24 fps.  It is especially noticeable since I am re-inserting the audio track.  Otherwise, great library!

**Comment by rosenbjerg** [comment]
I have changed FrameRate from int to double in v4.0.0, which will be released very soon
