### ISSUE TITLE
Output file not created, but no error is shown

### ISSUE THREAD

**Issue by asafweiss** [rosenbjerg/FFMpegCore#175]
I'm using the following code:
(frames is a List<Bitmap>)

var videoFramesSource = new RawVideoPipeSource(frames)
                {
                    FrameRate = 20,
                };
var a = FFMpegArguments.FromPipeInput(videoFramesSource)
            .OutputToFile(fileName, false)
            .ProcessSynchronously();

No exception is thrown and an error is nowhere to be seen, but no video file is created.

Hope you can help :)

**Comment by rosenbjerg** [comment]
@max619 have you had this kind of problem with `RawVideoPipeSource`?

**Comment by max619** [comment]
It's hard to tell what is the problem. @asafweiss if you can provide ffmpeg output, we would look at it. And will try to help you.

**Comment by asafweiss** [comment]
@max619 I’d be happy to, I just don’t know how. Is there an output stream I can read to retrieve it?

**Comment by max619** [comment]
You can try adding output handler this way:
```csharp

var a = FFMpegArguments.FromPipeInput(videoFramesSource)
.OutputToFile(fileName, false)
.NotifyOnOutput(outputHandlerHere) // <<<<
.ProcessSynchronously();
```

**Comment by max619** [comment]
Also, can you make sure your problem isn't the same as described at #164? If you are using images of different size it can lead to simillar behaviour.

**Comment by rosenbjerg** [comment]
@asafweiss Have you seen max' response(s)?

**Comment by rosenbjerg** [comment]
Closed due to inactivity
