### ISSUE TITLE
Issues with StreamPipeSource

### ISSUE THREAD

**Issue by phosphato-web** [rosenbjerg/FFMpegCore#176]
Hey Rosenbjerg,

First of all, I would like to thank you for your FFMpeg wrapper!
It will probably help to bring an old video streaming system into the browser.

The old video streaming system only offers frame callbacks from which H.264 Annex B byte[] frames come out.
My idea was to write them to a memory stream and then transfer it to your wrapper to get an (f)mp4 stream back.

```
//... inside the framecallback

memoryStream.Write(frameH264AnnexB, offset, f.Length);

//... after the first frame is writte onto the stream


FFMpegArguments
	.FromPipeInput(new StreamPipeSource(memoryStream))
	.OutputToPipe(new StreamPipeSink(ctx.Response.OutputStream), options => options
        .WithVideoCodec("h264")
        .ForceFormat("mp4"))
.ProcessAsynchronously();

```

The problem is that either an Invalid Argument Error (ffmpegErrorOutput) arises [], or nothing happens at all.

```
ffmpeg version 4.2 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 9.1.1 (GCC) 20190807
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
\\.\pipe\FFMpegCore_a6f2d6d8-3cbf-48fe-babe-05f6a3b13327: Invalid argument
```

How can I activate debugging in your wrapper or read out the <verbose> log output from ffmpeg?
Can I still write to the input stream after calling FFMpegArguments or does the length of the stream have to be fixed in advance?
Does the input have to be seekable?

**Comment by rosenbjerg** [comment]
Sounds like an interesting use-case, but sady I don't think that will be possible with ffmpeg since it support transcoding mp4/x264 to nor from a stream, since ffmpeg requires seeking support for that format. It might be possible with gstreamer however, so maybe have a look at that. But you maybe also be able to work around that problem by saving those byte[] to temporary files and let ffmpeg read from there and to another temporary file. 
I hope you find a fitting solution :)
