### ISSUE TITLE
Preview

### ISSUE THREAD

**Issue by visioforge** [rosenbjerg/FFMpegCore#178]
I want to add a preview to an application based on your library,

I'm not sure that's easy but, maybe it's possible by using 2 outputs, one with real file output and the second with pushing BMP images to the pipe? What do you think? Is it real?

**Comment by muradibrahimli** [comment]
videoCapture1.Stop(); method runs endless and does not respond when spamming. Tried to install beta version, still the same result
Please fix @visioforge

System:
SDK: dotnet 5.0
Project type: WPF

**Comment by rosenbjerg** [comment]
@visioforge if I undestand you correctly, you could use the FFMpeg.Snapshot static method for creating a preview image for a videofile
@muradibrahimli I have no idea what the method videoCapture1.Stop() does, nor do I see how this is related?

**Comment by muradibrahimli** [comment]
@muradibrahimli I have no idea what the method videoCapture1.Stop() does, nor do I see how this is related?
Yes problem is this
