### ISSUE TITLE
support blazor

### ISSUE THREAD

**Issue by behroozbc** [rosenbjerg/FFMpegCore#182]
hi
I want use this nuget package in blazor but get this error
please support blazor
[localhost-1614828067061.log](https://github.com/rosenbjerg/FFMpegCore/files/6080715/localhost-1614828067061.log)

**Comment by behroozbc** [comment]
I found this unsupported api in blazor 
 
[FFMpegCoreBlazor.xlsx](https://github.com/rosenbjerg/FFMpegCore/files/6081928/FFMpegCoreBlazor.xlsx)

**Comment by rosenbjerg** [comment]
Since this library depends on ffmpeg and ffprobe being installed and available in PATH or through path to executable file, that is not possible

**Comment by behroozbc** [comment]
@rosenbjerg hi 
do you have any library can help me in blazor?
