### ISSUE TITLE
Temp files not seem to exist

### ISSUE THREAD

**Issue by Yannick-DG** [rosenbjerg/FFMpegCore#183]
Hey there,

I've wrote an upload tool that makes from video a .tmp file so it can temporarily be stored. Now that I use extractAudio on this path, I get this exception:

```
Internal server error: System.TypeInitializationException: The type initializer for 'FFMpegCore.Enums.FileExtension' threw an exception.
 ---> System.ComponentModel.Win32Exception (2): The system cannot find the file specified.
```

I've got the following paths and they exist in my explorer:

Input file path
```
C:\Users\Yannick\AppData\Local\Temp\tmp9491.tmp
```
Output file path
```
C:\Users\Yannick\AppData\Local\Temp\tmp9492.tmp
```

Got a clue why this tells me it does not exist while they are existing in Explorer?

**Comment by rosenbjerg** [comment]
Looks like you don't have ffmpeg/ffprobe installed (and in PATH), or haven't set the FFMpegOptions

**Comment by ADefWebserver** [comment]
On Windows it worked fine when running directly, but it threw that error when I ran it as a service. I used code like this to fix the error:

```
string BinFolder = Path.Combine(System.AppDomain.CurrentDomain.BaseDirectory, "bin");
string ProcessingFolder = Path.Combine(System.AppDomain.CurrentDomain.BaseDirectory, "!Processing");
GlobalFFOptions.Configure(new FFOptions { BinaryFolder = BinFolder, TemporaryFilesFolder = ProcessingFolder });
```
