### ISSUE TITLE
Fix minor Readme issue

### ISSUE THREAD

**Issue by RinLovesYou** [rosenbjerg/FFMpegCore#186]
Change the readme to reflect the `Scale()` option being renamed to `Resize()`
took me way too long to figure out and made me lose a hair or two thinking I got some broken version

**Comment by rosenbjerg** [comment]
Scale has not been renamed. Scale is a videofilter argument, and has been moved into that in 4.0. Resize has always existed and uses a different ffmpeg arg to accomplish it.
But yes, I haven't had time to update the readme yet.
