### ISSUE TITLE
Wrong Code in readme...

### ISSUE THREAD

**Issue by jogibear9988** [rosenbjerg/FFMpegCore#187]
You Removed FFMPEGOptions, but in readme there is still this code:

      FFMpegOptions.Configure(new FFMpegOptions { RootDirectory = "./bin", TempDirectory = "/tmp" });

**Comment by jogibear9988** [comment]
see pull #188

**Comment by rosenbjerg** [comment]
I have updated all remaining examples in the readme now
Thanks for the PR
