### ISSUE TITLE
BlockingCollection and on-the-fly frame processing

### ISSUE THREAD

**Issue by chelseatools48** [rosenbjerg/FFMpegCore#194]
Hi, Ii'm trying to get video frames received from an IP camera processed out into a video file as they are being received, though I'm having some trouble figuring out how to do this. Using some snippets I found on other issues and some Microsoft documentation on BlockingCollection (running the consumer in a task), I have the following code in my video creation class:

        public BlockingCollection<IVideoFrame> VideoFrames { get; private set; }

        public VideoCreator()
        {
            VideoFrames = new BlockingCollection<IVideoFrame>();
            Task.Run(() => ProcessFrames());
        }

        private async Task ProcessFrames()
        {
            RawVideoPipeSource writer = new RawVideoPipeSource(VideoFrames.GetConsumingEnumerable()) { FrameRate = 20 };

            await FFMpegArguments
                .FromPipeInput(writer)
                .OutputToFile("test.webm", false, opt => opt
                    .WithVideoCodec("vp9")
                    .ForceFormat("webm"))
                    .NotifyOnProgress((progress) => Log.Logger.Debug("Encode Progress: {0}", progress))
                .ProcessAsynchronously();
        }

Outside of this class in my camera class, the following code is used to populate the collection:

        private void FrameReady(object sender, FrameReadyEventArgs args)
        {
            if (!_videoCreator.VideoFrames.IsAddingCompleted)
                _videoCreator.VideoFrames.Add(new BitmapVideoFrameWrapper((Bitmap)args.BitmapImage.Clone()));
        }

However, I cannot get this approach to work. The FFMPeg arguments do not seem to trigger, even as the BlockingCollection is being populated with frames from the camera.

If I add in a for loop on GetConsumingEnumerable in ProcessFrames, it works as expected printing out each of the frames received by the camera class. E.g if I replace  that code in ProcessFrames with this:

            foreach (var test in VideoFrames.GetConsumingEnumerable())
            {
                Log.Logger.Debug("Receiving");
            }

This works without any issues, it prints out a message every time a frame is added to the collection so the collection side of things seems to be OK, it's just getting it to work with the PipeSource that I'm having trouble with.

Other snippets seem to be doing a similar thing, for example in [this issue ](https://github.com/rosenbjerg/FFMpegCore/issues/168#issuecomment-774264040), which looks almost identical to what I want to do, but I'm not entirely sure what is wrong with my approach.

**Comment by chelseatools48** [comment]
**Update**: I updated my version of FFMpegCoreand I now seem to be getting an exception thrown, which is a bit more useful: 
Inner exception message: "One or more errors occurred. (A generic error occurred in GDI+.)"

FFMPegErrorOutput: 
![image](https://user-images.githubusercontent.com/10586799/112960451-55e3f480-913c-11eb-8924-f234cbb12a9d.png)

It seems to think the arguments are invalid, though I can't quite see what the issue is

**Comment by chelseatools48** [comment]
Ah! I figured it out, the video code is fine, it's my bitmap source that was the issue. Turns out the Bitmap cast on the Clone() method was causing this problem. I've fixed this and it's now writing to the video file as frames are being received.

I'll close this now.

**Comment by rosenbjerg** [comment]
@cameron2134 Great to hear that you got it working!
Was it a problem with this library, or was the image data actually corrupt or invalid?

**Comment by chelseatools48** [comment]
@rosenbjerg It turns out it was just my source image data that was the problem, originally I had thought it was an issue with my usage of the library as no exceptions were being thrown, but once I updated FFMpegCore to the latest version, I got the above exception and realised it may actually be my own code elsewhere that was the root issue.

Shame I didn't think to update first and save myself all the time trying to investigate it!
