### ISSUE TITLE
FFMpegCache Not Working 

### ISSUE THREAD

**Issue by DaGooseYT** [rosenbjerg/FFMpegCore#197]
Thanks for making this tool, it is very useful! I've placed FFMpeg/FFProbe in the default path (\root\x64\) and FFMpegCore appears to detect the binaries ok. However, when attempting to start a test conversion, in the FFMpegCache class, FFMpegCore can't find values for `_pixelFormats` , `_codecs` , nor `_containers` . All remain null which appears to interrupt the initialization of FFMpeg. I've confirmed that the video file paths are correct and that the correct FFMpeg binaries and versions are used. Any help regarding this issue is appreciated!

Exception details:
`System.IO.FileNotFoundException: 'Could not load file or assembly 'Instances, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.'` in line 34 in `FFMpegCache.cs`

**Comment by rosenbjerg** [comment]
Could you please an example of what you have tried?

**Comment by DaGooseYT** [comment]
Thank you for the quick reply. I am simply testing the functionality of FFMpegCore as I'm planning to use it with a windows form application I'm currently developing. I've debugged FFMpegCore into a class library DLL so that the integration with the windows form app can be possible and easy. I used the following code (very similar to sample code in README) to attempt the encoding process (I made no changes to FFMpegCore itself):

public void StartEncodeBttn_Click(object sender, EventArgs e)
        {
            string inputPath = InTxtBox.Text;
            string outputPath = SaveOutTxtBox.Text;
            FFMpegArguments
        .FromFileInput(inputPath)
        .OutputToFile(outputPath, false, options => options
        .WithVideoCodec(VideoCodec.LibX264)
        .WithConstantRateFactor(21)
        .WithAudioCodec(AudioCodec.Aac)
        .WithVariableBitrate(4)
        .WithVideoFilters(filterOptions => filterOptions
        .Scale(VideoSize.Hd))
        .WithFastStart())
        .ProcessSynchronously();
        }

Where at the time of attempting to encode, `InTextBox.Text = E:\testin.mp4` and `SaveOutTxtBox.Text = E:\testout.mp4`.
I've confirmed that the video using to test FFMpegCore is valid and not corrupt.  Attached below is a screenshot containing the exception that I'm facing. Thanks.

![exception](https://user-images.githubusercontent.com/72713589/113360998-f262ee00-9318-11eb-837c-29db1c33c1ae.PNG)

**Comment by rosenbjerg** [comment]
It just looks like ffmpeg wasn't found where it was expected. The path `\root\x64` is not the default path (where did you get that?) and so you need to specify that in the GlobalFFOptions

**Comment by DaGooseYT** [comment]
Under path configuration in README, the directions stated the following for setting FFMpeg binaries: 

"By doing so, the library will attempt to use either `/root/{ARCH}/(ffmpeg|ffprobe).exe`.
If these folders are not defined, it will try to find the binaries in `/root/(ffmpeg|ffprobe.exe)`"

I had also attempted create an `ffmpeg.config.json` file with the following contents and still no luck (also moved ffmpeg binaries to /bin):

{
  "BinaryFolder": "./bin",
  "TemporaryFilesFolder": "/tmp"
}

**Comment by rosenbjerg** [comment]
The `BinaryFolder` prop must point to folder on your machine that contains the ffmpeg and ffprobe binaries
