### ISSUE TITLE
How to set BitStreamFilter(Hevc_mp4ToannexB) ?

### ISSUE THREAD

**Issue by SenvenQi** [rosenbjerg/FFMpegCore#20]

**Comment by SenvenQi** [comment]
I want to rewrite it, but I don't know how to do it. 
Do you have any good suggestions?

**Comment by SenvenQi** [comment]
case VideoType.Ts:
                    container.Add(
                        new InputArgument(source),
                        new CopyArgument(),
                        new BitStreamFilterArgument(Channel.Video, Filter.Hevc_mp4ToannexB),
                        new ForceFormatArgument(VideoCodec.MpegTs),
                        new OutputArgument(output)
                    );
Like this

**Comment by vladjerca** [comment]
@SenvenQi I'll look into the matter.

**Comment by vladjerca** [comment]
@SenvenQi You don't have to rewrite the default. I built that argument collection as a shorthand for easy conversion.

If you want something more complex, we have support to convert using an argument collection:

https://github.com/vladjerca/FFMpegCore#argumentbuilder

``` csharp
var container = new ArgumentsContainer();
container.Add(new VideoCodecArgument(VideoCodec.LibX264));
container.Add(new ScaleArgument(VideoSize.Hd));

var ffmpeg = new FFMpeg();
var result = ffmpeg.Convert(container, new FileInfo("input.mp4"), new FileInfo("output.mp4"));
```
