### ISSUE TITLE
Feature: improved transcoding progress events

### ISSUE THREAD

**Issue by bankoViktor** [rosenbjerg/FFMpegCore#200]
The `ffmpeg.exe` has a `-progress` parameter to get information about the conversion progress.

**Comment by rosenbjerg** [comment]
Yes? Are you interested in creating a PR that utilise that information?

**Comment by bankoViktor** [comment]
Off course, I implemented it, i used a [`IProgress`](https://docs.microsoft.com/ru-ru/dotnet/api/system.iprogress-1?view=net-5.0) interface (as a function parameter ) to reporting about progress. In my opinion it will be great if it implemented in this library.

I have not time to implemented this feature by self in this repo, but i have my simple libary for example: [FFmpeg](https://github.com/bankoViktor/FFmpeg)

**Comment by rosenbjerg** [comment]
You mean more detailed progress than what's currently supported with `.NotifyOnProgress(..)`?

**Comment by rosenbjerg** [comment]
Closed due to inactivity
