### ISSUE TITLE
Stopping/interrupting ffmpeg

### ISSUE THREAD

**Issue by joakimobstfelder** [rosenbjerg/FFMpegCore#203]
Firstly: great wrapper! 

I am using FFMpegCore on a Raspberry Pi 4, streaming from a camera and feeding the stream to an endpoint, which works fine. 
(converting from MJPEG to Matroska)
The only problem I have, is that I can't find a way to stop ffmpeg "on demand".
As you can see, my FFMpegArguments process is pretty much never ending, due to the continuous video stream from my camera source (which is fine). So, my problem is that I can't find the correct way of interrupting and stop the process gracefully whenever I want (such as a command from elsewhere in the code). I wonder if anyone could point me in the right direction? 

Code is as follows: 

                `await FFMpegArguments
                        .FromPipeInput(new StreamPipeSource(cameraStream))
                        .OutputToPipe(new StreamPipeSink(async (data,cancellationToken) =>
                            {
                                var streamContent = new StreamContent(data);
                                streamContent.Headers.ContentType = new MediaTypeWithQualityHeaderValue("multipart/x-mixedreplace");
                                await http.PostAsync(url,streamContent,cancellationToken);
                            })  , opt => opt
                                .WithVideoCodec(_config.DefaultCodec)
                                .ForceFormat(_config.DefaultVideoFormat)
                                .WithVideoFilters(filterOptions => filterOptions
                                    .Scale(VideoSize.Hd))
                                .WithFastStart()
                        )
                        .NotifyOnOutput((e,r)=> Log.Debug(">>>>>> {e}",e))
                        .ProcessAsynchronously();`

Best regards, Joakim Obstfelder

**Comment by rosenbjerg** [comment]
Hi Joakim, interesting use-case :)
Have you tried using [`.CancellableThrough(..)`](https://github.com/rosenbjerg/FFMpegCore/blob/master/FFMpegCore/FFMpeg/FFMpegArgumentProcessor.cs#L48) just after (or before) your `.NotifyOnOutput(..)`?

**Comment by joakimobstfelder** [comment]
Hi, appreciate the reponse!

Yes, I did try to insert that (both before and after), but I am not quite sure how to deal with it - I mean, how can I hit that Action outside the main process (I do realize I might be asking stupid questions here)? 

For example : 

`.NotifyOnOutput((e,r)=> Log.Debug(">>>>>> {e}",e))
                        .CancellableThrough(out var cancel,1000)
                        .ProcessAsynchronously();`

I kind of image what I really want is to trigger cancel.Invoke() from somewhere outside the body. But maybe I am wrong?

**Comment by joakimobstfelder** [comment]
Oh no, my bad. 
Don't know what I was thinking...didn't really look close enough. The out param. 

Introduced a global Action var, and presto - works like charm. Thanks anyway, shutting down gracefully at will :)

**Comment by rosenbjerg** [comment]
Hi again @joakimobstfelder 
Glad to hear you got it working :)
I'll close this issue

**Comment by renanaragao** [comment]
@joakimobstfelder please, show me the code
