### ISSUE TITLE
PosterWithAudio creates empty video ouput

### ISSUE THREAD

**Issue by rosolam** [rosenbjerg/FFMpegCore#206]
Steps I am taking to replicate:

1. Create new C# project (.NET Framework 4.7.2 although also experiencing Core project)

2. Add FFMpegCore from Nuget (4.1.0)

3. Download MP3 and PNG used in FFMpegCore GIT test resources (just to make sure not my sources)

4. Download FFMpeg (ffmpeg-N-101969-g6c65e49990-win64-gpl-shared.zip) and copy files from bin folder to test_project\bin\debug folder

5. Add just the following snippet to the Main proc:

```
            string pngFile = Directory.GetCurrentDirectory() + @"\test.png";
            string audioFile = Directory.GetCurrentDirectory() + @"\test.mp3";
            string videoFile = Directory.GetCurrentDirectory() + @"\test.mp4";
            FFMpeg.PosterWithAudio(pngFile, audioFile, videoFile);
```

Code runs without error but I get a 10kb mp4 created (see attached) that VLC and Windows Media Player can open but appears to be 0 seconds long. 

Appreciate any help you can offer, thanks!
Michael

https://user-images.githubusercontent.com/7362534/115145239-8bcf1700-a01e-11eb-9c54-f89cba88d1eb.mp4

**Comment by rosolam** [comment]
I think I isolated the root cause looking at the command line arguments generated by the library vs running it by hand.  It looks like the order of the arguments is important and FFMpegCore is putting the '-loop 1' argument in the middle instead of at the beginning of the command it generates which seems to mean it gets ignored by FFMpeg:

This works:  ffmpeg **-loop 1** -i a.png -i a.wav -c:v libx264 -c:a aac -shortest a.mp4

This does not work: ffmpeg -i a.png -i a.wav **-loop 1** -c:v libx264 -c:a aac -shortest a.mp4

**Comment by rosenbjerg** [comment]
Sorry about the late answer. I will definitely look into reproducing and fixing the issue with your suggested fix

**Comment by rosenbjerg** [comment]
I have moved the Loop argument to the image input file, based on your feedback and some web searches.
Next version of this library will contain this fix
