### ISSUE TITLE
Could not load file or assembly 'System.Text.Json, Version=5.0.0.1

### ISSUE THREAD

**Issue by himpatel** [rosenbjerg/FFMpegCore#208]
Any clues why this assembly error? System.Text.Json exists in the bin folder of the site. My asp.net site is developed in .net 4.8

Exception:System.TypeInitializationException: The type initializer for 'FFMpegCore.GlobalFFOptions' threw an exception. ---> System.IO.FileLoadException: Could not load file or assembly 'System.Text.Json, Version=5.0.0.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040) ---> System.IO.FileLoadException: Could not load file or assembly 'System.Text.Json, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   --- End of inner exception stack trace ---
   at FFMpegCore.GlobalFFOptions..cctor()
   --- End of inner exception stack trace ---
   at FFMpegCore.FFMpegArgumentProcessor.ProcessSynchronously(Boolean throwOnError, FFOptions ffMpegOptions)

**Comment by tiesont** [comment]
.NET Core/Standard projects store package references differently than the default method used by .NET Framework projects (you probably have a packages.config file?). So, the transitive dependencies (in this case, JSON.NET) from FFMpegCore are not being loaded via your ASP.NET project.

You can get around this by following the suggestion shown here, https://stackoverflow.com/a/53654690/534109

**Comment by rosenbjerg** [comment]
Closing this since it's not an issue with the library, but with project references
