### ISSUE TITLE
Cant execute any ffmpeg command directly

### ISSUE THREAD

**Issue by Barshan-Mandal** [rosenbjerg/FFMpegCore#209]
Please add support to execute any ffmpeg command directly

**Comment by tiesont** [comment]
Not really sure what you're asking for. You can execute anything that's valid for ffmpeg via a CustomArgument, as shown here: https://github.com/rosenbjerg/FFMpegCore/blob/89fdef4766dc1a921fe58c9dfe784bfcd6080722/FFMpegCore.Test/ArgumentBuilderTest.cs#L301

If that's not what you're after, it might be helpful to elaborate on what you're asking for.

**Comment by rosenbjerg** [comment]
Thank you tiesont for answering this one :)
