### ISSUE TITLE
How to set temporary files location?

### ISSUE THREAD

**Issue by Primtek-Dev** [rosenbjerg/FFMpegCore#21]
How to set temporary files location?

**Comment by vladjerca** [comment]
@Primtek-Dev There's no option currently available. I'll try to add support for customizing the temp directory.

**Comment by joseazevedo** [comment]
Hi, its possible to hide the black windows(processs) when we create a Snapshot fro a video ?

**Comment by rosenbjerg** [comment]
The new version just released supports setting the temp directory used in Join and similar functions
