### ISSUE TITLE
Black Frame Detect Function

### ISSUE THREAD

**Issue by leta-lpb** [rosenbjerg/FFMpegCore#211]
Would there be a chance a ffprobe-based black frame detection function could be created? The ffprobe command I use looks like:

ffprobe -f lavfi -i movie="input.mp4,blackdetect[out0]" -show_entries tags=lavfi.black_start,lavfi.black_end -of default=nw=1

and it would generate output similar to this:

TAG:lavfi.black_start=35.7691
TAG:lavfi.black_start=35.7691
TAG:lavfi.black_end=37.0704
TAG:lavfi.black_end=37.0704
TAG:lavfi.black_start=53.9205
TAG:lavfi.black_start=53.9205
TAG:lavfi.black_end=54.1207
TAG:lavfi.black_end=54.1207
TAG:lavfi.black_start=68.9689
TAG:lavfi.black_start=68.9689
TAG:lavfi.black_end=69.4694
TAG:lavfi.black_end=69.4694
TAG:lavfi.black_start=75.7423
TAG:lavfi.black_start=75.7423
TAG:lavfi.black_end=76.2095
TAG:lavfi.black_end=76.2095

Thanks!

**Comment by rosenbjerg** [comment]
I don't think that would be too difficult with the current codebase. A PR would be welcomed :)
