### ISSUE TITLE
Feature request: Stream In- and output

### ISSUE THREAD

**Issue by Toemsel** [rosenbjerg/FFMpegCore#213]
I would like to request a feature whereas one would be able to stream data into and from ffmpeg. Currently you can define a stream in- and output, but it is a one-time streaming implementation. (Stream.CopyToAsync,...) However, what I would like to see is a permanent stream where one can provide updates to the stream which will be converted on demand. E.g.: delegating a via IP received packet directly to the Lib, forwarding it to ffmpeg and outputing it again on the output stream. That would enable real stream conversion and wouldn't represent the current byte array wrappers.

**Comment by max619** [comment]
Hi, @Toemsel!

It can be implemented with bufferred Stream that will block (if buffer is empty) read and write operations untill it will be closed. E.g.: Pipe and network streams work this way.

I don't think that such Stream implementation should be added to the library. @rosenbjerg what do you think about it?

Byte array wrappers such as `IVideoFrame` and so on are used to provide abstraction over images, and to get appropriate format settings to pass to ffmpeg. You can still use 'endless streams' if you know it's format, or stream contains some metadata that ffmpeg will accept.

**Comment by rosenbjerg** [comment]
@Toemsel I agree with max in that I don't see how that isn't already possible? You can provide a `Stream` as input source and another `Stream` as output destination. Have you tried that?

**Comment by Toemsel** [comment]
No, it isn't possible. As already mentioned, you "CopyToAsync" from A to B. No blocking or waiting, a simple state copy.

**Comment by rosenbjerg** [comment]
I'm not sure what you mean by "no blocking or reading".
CopyToAsync works like this: https://referencesource.microsoft.com/#mscorlib/system/io/stream.cs,162
Which means that as long as there is bytes to read in the input stream, it will keep reading those into the buffer and writing them to the output stream.
I don't see what you would want different for your example to work?
Secondly, I see how your idea with a "permanent stream" would make sense? If data is available continuously, use a regular stream, and if not, why even want to output them to the same continuous stream?
Again, I don't see how that currently isn't possible. A `Stream` can by definition always be endless, and using CopyToAsync makes no difference to that. Of course, CopyToAsync from and endless source stream will never terminate (at least not before cancellation is triggered)

**Comment by Toemsel** [comment]
When the src stream has no bytes available anymore, CopyTo terminates. See your Link line 259. Construct following example:

Open and feed a stream from any binary source. Feed it slowly, such that after a successful copy new bytes are available on your stream. I can point the LOC in your src tomorrow when I have access to a PC.

**Comment by rosenbjerg** [comment]
Yes, when all bytes in source stream is copied, it terminates. That is exactly what I understand copying the content of one stream to another to mean.

Sounds like what you need is a custom class that inherits from `Stream`, but has custom behaviour when read from. F.x. slowing/throttling reads until more data is available, to avoid returning 0 bytes preemptively, which would end the copy operation.

**Comment by Toemsel** [comment]
You are right in terms of "Yes, when all bytes in source stream is copied, it terminates. That is exactly what I understand copying the content of one stream to another to mean."

However, if you offer to convert a stream input to an output, I expect a continuous behaviour. Because it isn't supported, I asked for its support. Hence this ticket.

I did already branch your src and adjusted a lot of stuff, so I dont require it anymore. You can close it, even though other ppl might still expect this behaviour.

**Comment by yedajiang44** [comment]
@rosenbjerg  I have the same needs

I implemented `BlockStream`, but it doesn't seem to be decoding continuously as expected. Instead, after reading the readable data from BlockStream, it will be read again instead of decoding.

Hey @Toemsel Can you contribute your code? It would be better if possible.

**Comment by Toemsel** [comment]
@yedajiang44 Due to time constraints we did drop this feature. Here is our [non-stream](https://github.com/Toemsel/dji-wifi-tools/blob/main/Dji.Camera/DjiCamera.cs) impl. However, that isn't what you want. 😞

**Comment by yedajiang44** [comment]
@Toemsel Yes, this is not suitable for me, because writing the file and then reading it will increase the delay. I need to achieve as low a delay as possible, but your method is also great, thank you for your code~

@rosenbjerg Is there any way to achieve this?

this is my test

```c#
        var input = new BlockStream();// block read and write
        var inputPipe = new StreamPipeSource(input);
        var output = new MemoryStream();
        var outputPipe = new StreamPipeSink(output);

        Task.Run(async () =>
        {
            foreach (var item in File.ReadAllLines("data.txt").Select(x => x.ToHexBytes()))
            {
                input.Write(item);
                await Task.Delay(TimeSpan.FromMicroseconds(10));
            }
        });
        FFMpegArguments.FromPipeInput(inputPipe, x => x.WithFramerate(15))
        .OutputToPipe(outputPipe, x => x.WithVideoCodec(VideoCodec.LibX264).WithCustomArgument("-f mp4 -movflags frag_keyframe+empty_moov"))
        .ProcessSynchronously();
```
