### ISSUE TITLE
get thumbnail, image become stretched

### ISSUE THREAD

**Issue by Primtek-Dev** [rosenbjerg/FFMpegCore#22]
How to get thumbnail from mp4?

I try C# code below:

 var video = FFMpegCore.VideoInfo.FromFileInfo(_mp4_fi);
Bitmap _bmp = encoder.Snapshot(video, outputFile, new Size(video.Height, video.Width), TimeSpan.FromSeconds(_i), false);
                    
but produced image become stretched..

what I missed?

please help

**Comment by vladjerca** [comment]
@Primtek-Dev The `Size` constructor takes in `Width, Height`, not `Height, Width`.

https://docs.microsoft.com/en-us/dotnet/api/system.drawing.size.-ctor?view=netframework-4.8
