### ISSUE TITLE
[Question] multiple output files

### ISSUE THREAD

**Issue by h-c-a** [rosenbjerg/FFMpegCore#220]
Hi 

thanks for a fantastic library!. We appreciate it.

I have a question, is it possible to have multiple outputs defined for a given input. Or im trying to achieve the following

`ffmpeg -hide_banner -y -i file_example_MP4_640_3MG.mp4 \
  -vf scale=w=640:h=360:force_original_aspect_ratio=decrease -c:a aac -ar 48000 -c:v h264 -profile:v main -crf 20 -sc_threshold 0 -g 48 -keyint_min 48 -hls_time 4 -hls_playlist_type vod  -b:v 800k -maxrate 856k -bufsize 1200k -b:a 96k -hls_segment_filename beach/360p_%03d.ts beach/360p.m3u8 \
  -vf scale=w=842:h=480:force_original_aspect_ratio=decrease -c:a aac -ar 48000 -c:v h264 -profile:v main -crf 20 -sc_threshold 0 -g 48 -keyint_min 48 -hls_time 4 -hls_playlist_type vod -b:v 1400k -maxrate 1498k -bufsize 2100k -b:a 128k -hls_segment_filename beach/480p_%03d.ts beach/480p.m3u8 \
  -vf scale=w=1280:h=720:force_original_aspect_ratio=decrease -c:a aac -ar 48000 -c:v h264 -profile:v main -crf 20 -sc_threshold 0 -g 48 -keyint_min 48 -hls_time 4 -hls_playlist_type vod -b:v 2800k -maxrate 2996k -bufsize 4200k -b:a 128k -hls_segment_filename beach/720p_%03d.ts beach/720p.m3u8 \
  -vf scale=w=1920:h=1080:force_original_aspect_ratio=decrease -c:a aac -ar 48000 -c:v h264 -profile:v main -crf 20 -sc_threshold 0 -g 48 -keyint_min 48 -hls_time 4 -hls_playlist_type vod -b:v 5000k -maxrate 5350k -bufsize 7500k -b:a 192k -hls_segment_filename beach/1080p_%03d.ts beach/1080p.m3u8`

**Comment by rosenbjerg** [comment]
While not directly supported, it is indirectly supported through .WithCustomArgument(..) which will allow you to pass all the arguments not directly supported. I.e. `... .WithCustomArgument("-hls_segment_filename beach/1080p_%03d.ts") ...`
Does that make sense for you?

**Comment by rosenbjerg** [comment]
And great to hear that you find the library useful :)
