### ISSUE TITLE
Possible to run with external docker container?

### ISSUE THREAD

**Issue by ElliottBrand** [rosenbjerg/FFMpegCore#224]
I haven't found it in any documentation, so is it possible to run FFMpegCore in my C# app as a wrapper to build the necessary ffmpeg commands, then configure them to send them to an external linux docker container that's running an ffmpeg image? I'm wanting to pass a video (as a Stream) over to be converted or evaluated, then receive the stream/result back.

**Comment by rosenbjerg** [comment]
Sure, the easiest way is probably just to create an OS-wide alias for ffmpeg and ffprobe. The only annoyance will be the volume mounting, since you need to mount both the dir containing the input file(s) and the one for the output file(s), though that could be the same folder
