### ISSUE TITLE
CustomArgument

### ISSUE THREAD

**Issue by eslamo** [rosenbjerg/FFMpegCore#225]
I'm Trying to use CustomArgument to add watermark
The exception only appears when I use -filter_complex \\"overlay=x=main_w-overlay_w-(main_w*0.01):y=main_h-overlay_h-(main_h*0.01)\\"
I tried it with command line and it works fine

FFMpegArguments
                .FromFileInput("video.tmp", true, options => options
                    .WithCustomArgument("-i logo.png -filter_complex \\"overlay=x=main_w-overlay_w-(main_w*0.01):y=main_h-overlay_h-(main_h*0.01)\\"")
                )
                .OutputToFile("video.mp4", true, options => options
                    .WithVideoCodec(VideoCodec.LibX264)
                    .WithConstantRateFactor(21)
                    .WithAudioCodec(AudioCodec.Aac)
                    .WithAudioSamplingRate(44100)
                    .WithAudioBitrate(96)
                    .WithVariableBitrate(4)
                )
                .ProcessSynchronously();

but I have an exception

`FMpegCore.Exceptions.FFMpegException: 'ffmpeg exited with non-zero exit-code (1 - ffmpeg version 4.4-essentials_build-www.gyan.dev Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 10.2.0 (Rev6, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-lzma --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-sdl2 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-libass --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libgme --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libtheora --enable-libvo-amrwbenc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-librubberband
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, png_pipe, from 'logo.png':
  Duration: N/A, bitrate: N/A
  Stream #0:0: Video: png, rgba(pc), 250x125, 25 fps, 25 tbr, 25 tbn, 25 tbc
Input #1, mov,mp4,m4a,3gp,3g2,mj2, from 'video.tmp':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.29.100
  Duration: 00:03:24.64, start: 0.000000, bitrate: 311 kb/s
  Stream #1:0(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p, 640x360 [SAR 1:1 DAR 16:9], 177 kb/s, 30 fps, 30 tbr, 90k tbn, 60 tbc (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
  Stream #1:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 125 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
Codec AVOption vbr (Variable bit rate mode) specified for output file #0 (video.mp4) has not been used for any stream. The most likely reason is either wrong type (e.g. a video option with no video streams) or that it is a private option of some encoder which was not actually used for any stream.
Stream mapping:
  Stream #0:0 (png) -> overlay:main (graph 0)
  Stream #1:0 (h264) -> overlay:overlay (graph 0)
  overlay (graph 0) -> Stream #0:0 (libx264)
  Stream #1:1 -> #0:1 (aac (native) -> aac (native))
Press [q] to stop, [?] for help
[libx264 @ 0000024e2d2e8180] height not divisible by 2 (250x125)
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
[aac @ 0000024e2d58e480] Qavg: 54623.656
[aac @ 0000024e2d58e480] 2 frames left in the queue on closing
Conversion failed!)'

**Comment by rosenbjerg** [comment]
There is line in your error saying "height not divisible by 2 (250x125)", so my guess is that that is your problem?

**Comment by rosenbjerg** [comment]
Closing since this doesn't seem related to this library. Please re-open if it turns out that it is

**Comment by nsmithdev** [comment]
https://stackoverflow.com/questions/20847674/ffmpeg-libx264-height-not-divisible-by-2

**Comment by nsmithdev** [comment]
I had a similar error message when scaling down to HD and based on link above this works for scaling in many situations.
```
                   //Before
                   options.WithVideoFilters(filterOptions => {
                        filterOptions.Scale(VideoSize.HD);
                    });
                   //After
                    options.WithVideoFilters(filterOptions => {
                        filterOptions.Scale(-2, (int)VideoSize.HD);
                    });
```
