### ISSUE TITLE
Subtitle stream support

### ISSUE THREAD

**Issue by alex6dj** [rosenbjerg/FFMpegCore#232]
Hello. Just a question. This library actually support subtitles or not (internalls or in .srt files). I think it could be a good addition.

**Comment by rosenbjerg** [comment]
I have merged both your PRs on subtitle support, so thanks to you that is now supported :)
I'll release next version soon, which will include both your contributions. I hope to get #110 merged and included in that version as well

**Comment by alex6dj** [comment]
Thanks for that. In a near future I will try to add subtitle support but by stream, in case any one need to include one or several subtitles with video file like .mkv format. And subtitle extraction too. :)

**Comment by rosenbjerg** [comment]
That sounds great. Looking forward to those additions! :)

**Comment by SebulbaSe** [comment]
Any progress on this one, I would be interested to be able to extract subtitles.

**Comment by rosenbjerg** [comment]
Who are you asking @SebulbaSe ?
