### ISSUE TITLE
Pipe is broken

### ISSUE THREAD

**Issue by spektor56** [rosenbjerg/FFMpegCore#234]
I'll close this issue now. Please reopen if the problem persists even after this fix

_Originally posted by @rosenbjerg in https://github.com/rosenbjerg/FFMpegCore/issues/128#issuecomment-862084465_

I still have issue with "Pipe is broken" with the exact same code, the png does export though, my filestream is being read from a HEVC file:

FFMpegArguments
.FromPipeInput(test)
.OutputToPipe(new StreamPipeSink(ms), options => options
.ForceFormat("rawvideo")
.WithVideoCodec(VideoCodec.Png)
.WithFrameOutputCount(1))
.ProcessSynchronously()

if i take out the WithFrameOutputCount(1) it's fine. The code also works fine if i use FromFileInput instead of FromPipeInput.

**Comment by rosenbjerg** [comment]
Do you see anything in the `FFMpegErrorOutput` prop of the exception?

**Comment by spektor56** [comment]
Right now i've just been swallowing the exception because the PNG does output as expected it's just that it throws the error when reading from an open stream.  If I read data into a buffer first then try to get the PNG it's fine.  Problem is, i dont know how much data i need to read to get a single frame :), its not always the same.  The input stream is 20fps, i dont know if that has anything to do with the issue.

ffmpeg version 4.2.1 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 9.1.1 (GCC) 20190807
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Input #0, hevc, from '\\.\pipe\FFMpegCore_d778900c-6ce3-4282-9521-d0a445608ff1':
  Duration: N/A, bitrate: N/A
    Stream #0:0: Video: hevc (Main), yuv420p(tv), 1164x874, 25 fps, 25 tbr, 1200k tbn, 25 tbc
Stream mapping:
  Stream #0:0 -> #0:0 (hevc (native) -> png (native))
Press [q] to stop, [?] for help
Output #0, rawvideo, to '\\.\pipe\FFMpegCore_7ee01f51-df64-4e94-92e3-15a39cb03d28':
  Metadata:
    encoder         : Lavf58.29.100
    Stream #0:0: Video: png, rgb24, 1164x874, q=2-31, 200 kb/s, 20 fps, 20 tbn, 20 tbc
    Metadata:
      encoder         : Lavc58.54.100 png
frame=    1 fps=0.0 q=-0.0 Lsize=     700kB time=00:00:00.05 bitrate=114640.3kbits/s speed=0.178x    
video:700kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.000000%

**Comment by KarolStosik** [comment]
Pipe also doesn't work for me:

FFMpegCore 4.5.0
FFMpeg binary: 4.4.0

Code:
```
var isSuccess = await FFMpegArguments
                    .FromPipeInput(new StreamPipeSource(inputStream), options => options
                        .Seek(time))
                    .OutputToPipe(new StreamPipeSink(ms), options =>
                        options.WithVideoCodec(VideoCodec.Png)
                        .ForceFormat("rawvideo"))
                        .ProcessAsynchronously()
                    .ConfigureAwait(false);
```

FFMpeg error:
```
'ffmpeg exited with non-zero exit-code (1 - ffmpeg version N-103457-g9abf0e0419-20210831 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 10-win32 (GCC) 20210408
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-w64-mingw32- --arch=x86_64 --target-os=mingw32 --enable-version3 --disable-debug --disable-w32threads --enable-pthreads --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --enable-libvmaf --enable-vulkan --disable-libxcb --disable-xlib --enable-amf --enable-libaom --disable-avisynth --enable-libdav1d --disable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --disable-frei0r --enable-libglslang --enable-libgme --enable-libass --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librav1e --disable-librubberband --enable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --disable-libdrm --disable-vaapi --disable-libvidstab --disable-libx264 --disable-libx265 --disable-libxavs2 --disable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags= --extra-libs=-lgomp --extra-version=20210831
  libavutil      57.  4.101 / 57.  4.101
  libavcodec     59.  6.100 / 59.  6.100
  libavformat    59.  4.102 / 59.  4.102
  libavdevice    59.  0.101 / 59.  0.101
  libavfilter     8.  7.100 /  8.  7.100
  libswscale      6.  0.100 /  6.  0.100
  libswresample   4.  0.100 /  4.  0.100
[mov,mp4,m4a,3gp,3g2,mj2 @ 00000269db3a4dc0] Could not find codec parameters for stream 0 (Video: h264 (avc1 / 0x31637661), none, 360x360, 275 kb/s): unspecified pixel format
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '\\.\pipe\FFMpegCore_9e4b53c3-2a74-435b-8772-f62378d30f84':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf56.25.101
  Duration: 00:00:10.01, start: 0.000000, bitrate: N/A
  Stream #0:0[0x1](und): Video: h264 (avc1 / 0x31637661), none, 360x360, 275 kb/s, 30 fps, 30 tbr, 15360 tbn (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
  Stream #0:1[0x2](und): Audio: aac (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 96 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> png (native))
Press [q] to stop, [?] for help
[mov,mp4,m4a,3gp,3g2,mj2 @ 00000269db3a4dc0] stream 0, offset 0x2bfb6: partial file
\\.\pipe\FFMpegCore_9e4b53c3-2a74-435b-8772-f62378d30f84: Invalid argument
Cannot determine format of input stream 0:0 after EOF
Error marking filters as finished
Conversion failed!)'
```

**Comment by rosenbjerg** [comment]
@KarolStosikPowel Looks like ffmpeg was unable to determine the format. You may need to specify it using ForceFormat on the input stream

**Comment by rosenbjerg** [comment]
Closed due to inactivity

**Comment by spektor56** [comment]
no solution for this one?

**Comment by jeroenvanderschoot** [comment]
I get on version 4.7.0 executing in docker image mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim:

[NULL @ 0x55d325e45c80] Unable to find a suitable output format for 'unix:/tmp/CoreFxPipe_FFMpegCore_5555885e-ceb3-4552-b645-53bcc2aad7ef'
