### ISSUE TITLE
Why trim video file get only at most 10 seconds in Windows 10?

### ISSUE THREAD

**Issue by zydjohnHotmail** [rosenbjerg/FFMpegCore#235]
Hello:
I tried to use this repo to trim/cut one video file (mp4 format) into 2 parts.  The original video file has duration of 11 minutes.
I want to cut it into 2 parts, the first part is 61 seconds from the begging, and the second part is 30 seconds from 3:30 to 4:00.
The following command line works:
C:\Vidoes\> ffmpeg -i 1.mp4 -ss 00:00 -to 01:01 cut1.mp4
C:\Vidoes\> ffmpeg -i 1.mp4 -ss 03:30 -to 04:00 cut2.mp4
I created one C# console project (Visual Studio 2019) target .net 5.0, and install nuget package:
PM> Install-Package FFMpegCore -Version 4.4.0
The following is my C# code:
using FFMpegCore;
using System;
using System.Threading.Tasks;

namespace FfmpegCoreTrimVideo1
{
    class Program
    {
        public const string XVidoe1_File =
            @"C:\Videos\1.mp4";
        public const string XVideo1_Cut1_File =
            @"C:\Videos\Cut1.mp4";
        public const string XVideo1_Cut2_File =
            @"C:\Videos\Cut2.mp4";
        public const string Ffmpeg_Binary =
            @"C:\Program Files\ffmpeg-4.4-full_build\bin\";

        public static async Task Cut_Video1_File_Into2_Parts()
        {
            FFMpegArguments.FromFileInput(XVidoe1_File, false,
                opt => opt.WithCustomArgument("-ss 00:00 -t 01:01"))
                          .OutputToFile(XVideo1_Cut1_File, false).ProcessSynchronously();
            await Task.Delay(10000);
            Console.Beep();
            FFMpegArguments.FromFileInput(XVidoe1_File, false,
                opt => opt.WithCustomArgument("-ss 03:30 -t 04:00"))
                          .OutputToFile(XVideo1_Cut2_File, false).ProcessSynchronously();
            await Task.Delay(30000);
            Console.Beep();
            Console.WriteLine("Cut two parts of one XVideo file is done!");
        }

        static async Task Main(string[] args)
        {
            GlobalFFOptions.Configure(new FFOptions 
            { BinaryFolder = Ffmpeg_Binary, TemporaryFilesFolder = "/tmp" });
            await Cut_Video1_File_Into2_Parts();
            Console.Beep();
        }
    }
}

I can compile my code, but when I run it, I saw the results:
The first file (cut1.mp4) has duration of only 10 seconds, and the second file (cut2.mp4) has nothing, and its length is only 1KB.
Let me know if I made any mistake.
PS: I install FFMEPG from https://github.com/BtbN/FFmpeg-Builds/releases
And unzip the folder and add the binary folder to system Path.

**Comment by rosenbjerg** [comment]
One key difference between your console commands and the FFMpegCore calls is whether the arguments are arguments to the input file, or the output file. In your console examples, you specify -ss and -t as arguments to the **output file**. But in your FFMpegCore snippet, you supply those arguments (using WithCustomArgument) as arguments to the **input file**. Move the arguments (options lamba) to the OutputToFile call

**Comment by rosenbjerg** [comment]
It migth make sense to provide -ss as an argument to the input file, for more efficient seeking. Not sure if that applies for your usecase though

**Comment by zydjohnHotmail** [comment]
Hello:
I changed my code according to your advice, so it looks like this:
        public static async Task Cut_Video1_File_Into2_Parts()
        {
            await FFMpegArguments.FromFileInput(XVidoe1_File, false)
                           .OutputToFile(XVideo1_Cut1_File, false,
                            opt => opt.WithCustomArgument("-ss 00:00 -t 01:01")).ProcessAsynchronously();
            await Task.Delay(61000);
            Console.Beep();
            FFMpegArguments.FromFileInput(XVidoe1_File, false)
                           .OutputToFile(XVideo1_Cut2_File, false,
                            opt => opt.WithCustomArgument("-ss 03:30 -t 04:00")).ProcessSynchronously();
            await Task.Delay(30000);
            Console.Beep();
            Console.WriteLine("Cut two parts of one XVideo file is done!");
        }
The first one, I used async processing, the second one I used sync processing. I got the same results: the first one is 10 seconds, the second one is nothing. (File size is only 1KB).
As my code is not complicated: only less than 20 lines of code.
Can you find any video file (mp4 format) and do a simple test on any Windows 10 PC, to see if you get the same result as I did?
As long as your video has more than 1 minute, and you can cut more than 10 seconds, you will see if you can cut at most 10 seconds of the original video.
Thanks,
