### ISSUE TITLE
InvalidOperationException: Pipe hasn't been connected yet.

### ISSUE THREAD

**Issue by djex** [rosenbjerg/FFMpegCore#237]
Hello. This is driving me nuts. I'm not sure if this is a bug or something dumb on my part. Any ways I'm trying to encode a Bitmap from a pipe to x264 output pipe with the code below. However when I execute the code it throws "AggregateException: One or more errors occurred." and then also"InvalidOperationException: Pipe hasn't been connected yet.". Both of which don't help much to solve the issue. Any idea why does not work?

```
public void FFMPEGEncode(Bitmap bitmap)
{
	IEnumerable<IVideoFrame> CreateFrame()
	{
		BitmapVideoFrameWrapper bitmapVideoFrameWrapper = new BitmapVideoFrameWrapper(bitmap);
	 
		yield return bitmapVideoFrameWrapper;
	}

	RawVideoPipeSource videoFramesSource = new RawVideoPipeSource(CreateFrame());

	MemoryStream outputStream = new MemoryStream();
	StreamPipeSink reader = new StreamPipeSink(outputStream);

	FFMpegArguments
		.FromPipeInput(videoFramesSource)
		.OutputToPipe(reader, opt => opt
			.WithVideoCodec(VideoCodec.LibX264)
			.WithFrameOutputCount(1))
		.ProcessSynchronously();
}
```

**Comment by rosenbjerg** [comment]
afaik, ffmpeg cannot encode/decode mp4 from non-seekable streams.
Are you able to run your conversion successfully if you output to a file?

**Comment by djex** [comment]
Yes it works fine if I output to a file. Unfortunately that's not what I'm looking for though. I want to be able to encode a bitmap and then get the encoded bytes. Is this possible? I don't want to have to save to a file and then read the file into a stream. That would be very slow for what I need. Maybe FFMpegCore won't work for what I need.

**Comment by rosenbjerg** [comment]
Just to understand your problem correclty; you want to encode a single bitmap to h264 video? 
Would vp9 (mkv) maybe be usable? ffmpeg has better support for "streaming" vp9 afaik

**Comment by djex** [comment]
Well to explain my situation in more detail I'm working on a remote desktop application. I'm currently grabbing the screen using Windows API to a Bitmap then encoding the bitmap to H264 using OpenH264. I then take the encoded H264 byte array and send it off over UDP to the client viewer which uses OpenH264 to decode back to a bitmap and then I'm using Direct2D to render on screen. This works however OpenH264 is a bit slow. Currently taking about 40ms to encode and about the same to decode a 1920x1080 image.  I've read that FFMpeg has a faster more optimized encoder / decoder so I'm trying to work out an easy way to integrate ffmpeg for what I need. I might need to use something like FFMpeg.Autogen to do what I want. The reason I want to use H264 is from my research it seems it's faster than VP8. I have not looked into VP9. Any suggestion you might have are welcome for sure.

**Comment by rosenbjerg** [comment]
The ffvp9 encoder looks to be slightly faster according to this (old) [article](https://blogs.gnome.org/rbultje/2015/09/28/vp9-encodingdecoding-performance-vs-hevch-264/).
So I think VP9 is a candidate for this, but I'm not sure if that will fix the problem.
Based on what you describe, it sounds like it may make more sense to remove the WithFrameOutputCount(1), and keep it as a continuous stream, to avoid the time overhead in reopening an ffmpeg process for each frame. 
That may also be what you intended :)
But it sounds like an interesting use-case, I hope some of my suggestions can help

**Comment by rosenbjerg** [comment]
Closing this one
