### ISSUE TITLE
How I can use this repo to reset video starting and ending time?

### ISSUE THREAD

**Issue by zydjohnHotmail** [rosenbjerg/FFMpegCore#238]
Hello:
I have downloaded quite a number of videos, all the videos are in M3U8 format, and I have saved them as MP4 format videos.
But I found that almost all the videos, their starting time is not 0.
For example, I have one video file (C:\Videos\1.mp4), its duration is 2 hours, but when I used VLC player to play this mp4 video file, I can see that the starting time is: 01:00:00, and ending time is: 03:00:00. It has actual duration of 2 hours, but not from 00:00:00 to 02:00:00.
Can I use the repo to convert this mp4 video using the same format (not changing other parameter), but change the starting time to 00:00:00 and ending time to its duration?
If yes, please let me know where I can find code sample (C#) to do this?
Thanks,

**Comment by rosenbjerg** [comment]
You can use .Seek(..) to specify amount of time to skip at the beginning and .Duration(..) to specify how much of the remaining you want processed
