### ISSUE TITLE
Need codec_tag and codec_tag_string values from FFProbe to analyse files for acceptability

### ISSUE THREAD

**Issue by GuyWithDogs** [rosenbjerg/FFMpegCore#239]
I've got an older video playback system that requires a specific type of AVI file - it needs to have an XVID video stream and an optional MP3 audio stream (among other things). I was creating a "playlist generator" for this device and found that FFProbe.Analyse() would return the codec name as "mpeg4", but the video stream subtype that was stored in the codec_tag_string value in the JSON output of ffprobe was not available. I'd like to have access to that.

**Comment by rosenbjerg** [comment]
Your PR has been merged :)
