### ISSUE TITLE
How I can use -stream_loop parameter in this repo?

### ISSUE THREAD

**Issue by zydjohnHotmail** [rosenbjerg/FFMpegCore#241]
Hello:
I have made one small mp4 video with duration of only 1 second, it was made of many images.  And I want to make one big mp4 video with duration of 1 minute, I think I can repeat the 1 second video 60 times, to make one minute mp4 video.
And I tried the following ffmpeg command directly in my PC (Windows 10), it works:
C:\Videos>ffmpeg -stream_loop 60 -i Second1.mp4 -c copy Minute1.mp4
I want to know how I can do the same using this repo?
Thanks,

**Comment by rosenbjerg** [comment]
Hello,
That is currently not supported, but a PR on that feature would be welcomed :)

**Comment by zydjohnHotmail** [comment]
Hi,
How I can raise a PR?

**Comment by rosenbjerg** [comment]
You could just use .WithCustomArgument("-stream_loop 60') on the input file options for now.
All arguments that are not directly supported by this library with a fluent builder method, is supported indirectly using `WithCustomArgument`
