### ISSUE TITLE
FFMpegCore is not working in azure web app

### ISSUE THREAD

**Issue by sparrowhawk26** [rosenbjerg/FFMpegCore#244]
I have a .net core web api application that try to convert 3gp to mp3. Its work fine locally but when i publish it to my azure web app i get this error : 
FFMpegCore.Exceptions.FFMpegException: ffmpeg was not found on your system
   at FFMpegCore.Helpers.FFMpegHelper.VerifyFFMpegExists(FFOptions ffMpegOptions)
   at FFMpegCore.FFMpegArgumentProcessor.PrepareInstance(FFOptions ffMpegOptions, CancellationTokenSource& cancellationTokenSource)
   at FFMpegCore.FFMpegArgumentProcessor.ProcessAsynchronously(Boolean throwOnError, FFOptions ffMpegOptions)

my code is : 

```
using (MemoryStream m = new())
                        {
                            await FFMpegArguments.FromFileInput(tempFile)
                                                     .OutputToPipe(new StreamPipeSink(m), options =>
                                                            options.WithAudioCodec("mp3").ForceFormat("mp3"))
                                                     .ProcessAsynchronously(true, new FFOptions() { BinaryFolder = $"{AppDomain.CurrentDomain.BaseDirectory}ffmpeg" });

                            m.Position = 0;

                            await blob.UploadAsync(m);
                        }
```

and i have my ffmpeg folder with all ffmpeg files copied in azure

thanks for your help

**Comment by rosenbjerg** [comment]
If ffmpeg is available in the environment PATH variable, you must specify the path to the folder containing the ffmpeg executable using FFOptions

**Comment by rosenbjerg** [comment]
[readme](https://github.com/rosenbjerg/FFMpegCore#path-configuration)

**Comment by sparrowhawk26** [comment]
Hi

Sorry i don t understand your answer. I already had Ffoptions in my code as
you can see and it s worked locally but not in azure. I had left something
? I don t had path i had set the environtmentbin variable in my ffoptions
it s all ?

Regards


בתאריך יום ה׳, 12 באוג׳ 2021, 23:30, מאת Malte Rosenbjerg ‏<
***@***.***>:

**Comment by rosenbjerg** [comment]
Hadn't noticed you specified FFOptions in your example. Are your ffmpeg executables placed in a folder with the path `{AppDomain.CurrentDomain.BaseDirectory}ffmpeg`? Looks like you are either missing the directory separator just before the ffmpeg folder in the path, or have specified the path to the executable instead of the path to the folder containing the executable.

**Comment by rosenbjerg** [comment]
Could also be that you are hosting on linux but have provided ffmpeg.exe (windows build) or the other way round?

**Comment by sparrowhawk26** [comment]
Yes {AppDomain.CurrentDomain.BaseDirectory}ffmpeg is the path to the folder
i also tried with separator it s the same.



בתאריך יום ו׳, 13 באוג׳ 2021, 12:24, מאת Malte Rosenbjerg ‏<
***@***.***>:

**Comment by sparrowhawk26** [comment]
hi,

I solved the issue, in fact I don't know why but in the azure web app when
I deploy the ffmpeg folder into d:\home\site\wwwroot\ffmpeg it's not
working, seems to be an azure restriction.
So i moved the ffmpeg folder in the d:\home which is outside the
application folder

Regards

‫בתאריך יום ו׳, 13 באוג׳ 2021 ב-12:35 מאת משה חייט <‪
***@***.***‬‏>:‬
