### ISSUE TITLE
FFMpeg.Snapshot hangs forever when calling from WinForms Net5 app.

### ISSUE THREAD

**Issue by Muhomorik** [rosenbjerg/FFMpegCore#246]
Hello,

I am trying to reference project in a .NET 5 WinForms app and create a bitmap.

Unfortunately, FFMpeg.Snapshot hangs forever than.

I have checked the source and found that test:

https://github.com/rosenbjerg/FFMpegCore/blob/04ebdb1907b9569bc43f7dc9744eb05f760f4cc4/FFMpegCore.Test/VideoTest.cs#L397

        [TestMethod, Timeout(10000)]
        public void Video_Snapshot_InMemory()
        {
            var input = FFProbe.Analyse(TestResources.Mp4Video);
            using var bitmap = FFMpeg.Snapshot(TestResources.Mp4Video);
            
            Assert.AreEqual(input.PrimaryVideoStream!.Width, bitmap.Width);
            Assert.AreEqual(input.PrimaryVideoStream.Height, bitmap.Height);
            Assert.AreEqual(bitmap.RawFormat, ImageFormat.Png);
        }

It is green and I have also verified results with the debugger. Also added .Net 5 full framework project to the solution and verified that same test is green.
Creating snapshot as file works as expected.

But somehow it fails when added to WinForms app :/

**Comment by rosenbjerg** [comment]
It seems to be related to how thread synchronization is handled in the GUI framework
[Previous issue with WPF](https://github.com/rosenbjerg/FFMpegCore/issues/169#issuecomment-812893951) got past the hanging by using SnapshotAsync()

**Comment by rosenbjerg** [comment]
Could you try with SnapshotAsync instead?

**Comment by Muhomorik** [comment]
Yes, sorry


        private void BtnFFMpegSnapshot_Click(object sender, EventArgs e)
        {
            // ! hangs !
            var path = @"E:\MediaSamples\icc_grundfiler\filmer\input_3sec.mp4";
            var bitmap = FFMpeg.Snapshot(path);
            var x = 1;
        }

        private void BtnFFMpegSnapshot_Click(object sender, EventArgs e)
        {
            // ! hangs !
            var path = @"E:\MediaSamples\icc_grundfiler\filmer\input_3sec.mp4";
            var bitmap = FFMpeg.SnapshotAsync(path).GetAwaiter().GetResult();
            var x = 1;
        }

        private async void btnFFMpegSnapshotAsync_Click(object sender, EventArgs e)
        {
            // works
            var path = @"E:\MediaSamples\icc_grundfiler\filmer\input_3sec.mp4";
            var bitmap = await FFMpeg.SnapshotAsync(path);
            var x = 1;
        }


I've also tried to pull code out and find where it hangs, but lost it :/ will try again. Never used TaskCompletionSource and it is kind of fun :)

This works both with with async and with GetAwaiter.GetResult(). What i have seen, the library does something like that and it is strange that it hangs :/


        private Task ProcessWithTaskCompletionSource(string input, string outputPath)
        {
            var tcs = new TaskCompletionSource<object>(TaskCreationOptions.RunContinuationsAsynchronously);

            using var process = new Process();

            process.StartInfo.FileName = @"E:\ICCMS\ffmpeg-win32-shared\bin\ffmpeg.exe";
            process.StartInfo.Arguments = $"-i \"{input}\" -vf fps=1 \"{outputPath}\"";

            process.StartInfo.WindowStyle = ProcessWindowStyle.Hidden;
            process.StartInfo.UseShellExecute = false;
            process.StartInfo.CreateNoWindow = true;

            process.StartInfo.RedirectStandardOutput = true;
            process.StartInfo.RedirectStandardError = true;

            var output = new StringBuilder();
            var error = new StringBuilder();

            using (var outputWaitHandle = new AutoResetEvent(false))
            using (var errorWaitHandle = new AutoResetEvent(false))
            {
                process.OutputDataReceived += (sender, e) =>
                {
                    if (e.Data == null)
                    {
                        outputWaitHandle.Set();
                    }
                    else
                    {
                        output.AppendLine(e.Data);
                    }
                };
                process.ErrorDataReceived += (sender, e) =>
                {
                    if (e.Data == null)
                    {
                        errorWaitHandle.Set();
                    }
                    else
                    {
                        error.AppendLine(e.Data);
                    }
                };

                process.Start();

                process.BeginOutputReadLine();
                process.BeginErrorReadLine();

                var timeout = 500;
                if (process.WaitForExit(timeout) &&
                    outputWaitHandle.WaitOne(timeout) &&
                    errorWaitHandle.WaitOne(timeout))
                {
                    // Seems to be writing to Error all the time.
                    var consoleOutput = string.Empty;
                    if (output.Length != 0)
                    {
                        consoleOutput = output.ToString();
                    }
                    else if (error.Length != 0)
                    {
                        consoleOutput = error.ToString();
                    }

                    if (process.ExitCode == 0)
                    {
                        tcs.SetResult(consoleOutput);
                    }
                    else
                    {
                        var ex = new Exception(consoleOutput);
                        tcs.SetException(ex);
                    }

                    // Process completed. Check process.ExitCode here.
                }
                else
                {
                    // Timed out.
                    tcs.SetCanceled();
                }
            }

            return tcs.Task;
        }

**Comment by TSKHot** [comment]
Getting exactly the same. Have tried with several framework versions 4.5+

**Comment by rosenbjerg** [comment]
I have added ConfigureAwait(false) in a number of places it was missing, changed a bit in how the sync processing is done. Could you please try again with version 4.6.0?

**Comment by TSKHot** [comment]
Yep, these changes appear to have fixed the problem - both the synchronous and async calls return and produce in-memory bitmaps.

**Comment by rosenbjerg** [comment]
Lovely! Thank you for reporting back
