### ISSUE TITLE
JoinImageSequence make readable but broken file.

### ISSUE THREAD

**Issue by ghost** [rosenbjerg/FFMpegCore#248]
OS - windows 10
ffmpeg version - 4.4
.net version - 5.0

Firstly program divide downloaded from youtube videos by frames.
`
FFMpegArguments.FromFileInput(LastVideoFullPath).OutputToFile("Temp/Video/Frame%05d.png", true, Options =>
                {
                    Options.WithVideoCodec(VideoCodec.Png);
                })
                .ProcessSynchronously();
`

After i add some random text on random frames (no time to explain) using bitmap. I don't change encoder params, so i think it should be like in file. 

And in the end (with this part i have problem) i trying to make video from edited frames.
`            FFMpeg.JoinImageSequence("Temp/Cheese.mp4", LastVideoInfo.VideoQuality.Framerate,
                Frames.Select(x => ImageInfo.FromPath(x)).ToArray());`
                
![In original](https://user-images.githubusercontent.com/23528003/131233214-5ffe92e1-a662-4b0b-960d-ef9c377e8c75.png)
![After](https://user-images.githubusercontent.com/23528003/131233210-9d734ed3-0759-4c75-8179-bb39066f7975.png)

**Comment by rosenbjerg** [comment]
Fixed in #319
Will release next version containing this fix soon

**Comment by rosenbjerg** [comment]
Version 4.8 has just been released, and contains fix for this issue :)
