### ISSUE TITLE
Files are left open after JoinImageSequence() ends

### ISSUE THREAD

**Issue by JoyfulReaper** [rosenbjerg/FFMpegCore#249]
Files are left open after JoinImageSequence() ends

After the JoinImageSequence() method runs the images are left open. This can be verified by using Process Explorer

**Comment by JoyfulReaper** [comment]
I checked the tests in the project cloned from github and can confirm that the issue is not with my program as it occurs in the test public void Video_Join_Image_Sequence() as well.

**Comment by rosenbjerg** [comment]
Thank you for reporting this. I'll have a look at the problem soon

**Comment by rosenbjerg** [comment]
This problem is fixed in v.4.6.0 where the Image instances are opened with a `using` to ensure disposal
