### ISSUE TITLE
Saving M3U8 stream

### ISSUE THREAD

**Issue by duci95** [rosenbjerg/FFMpegCore#254]
When I try to save m3u8 stream I get System.TypeInitializationException: The type initializer for 'FFMpegCore.Enums.FileExtension' threw an exception.

**Comment by rosenbjerg** [comment]
You need to configure `GlobalFFOptions` since initialization of `VideoType` uses the global options to run ffmpeg to probe for information from the currently installed version. 

I'm not a big fan of how that is put together either
