### ISSUE TITLE
Audio filters usage

### ISSUE THREAD

**Issue by alex6dj** [rosenbjerg/FFMpegCore#257]
Is there any equivalent for using audio filters like video filters counterpart.

`.WithVideoFilters(videoFilter => videoFilter.Scale(preset.Resolution.Width, preset.Resolution.Height))`

Something like

`.WithAudioFilters(audioFilter => audioFilter.Pan("1c|c0=0.9*c0+0.1*c1"))`

Or it needs to be implemented

**Comment by rosenbjerg** [comment]
It isn't supported yet, but I'm not against supporting AudioFilters :)
