### ISSUE TITLE
Video file damage after screen recording

### ISSUE THREAD

**Issue by li-zhixin** [rosenbjerg/FFMpegCore#258]
## Environment

- ffmpeg : 4.4(Official)
- FFMpegCore: 4.5.0(latest)
- OS: windows

## Reproduction code

```c#
FFMpegArguments.FromDeviceInput("desktop", options =>
{
    options.WithFramerate(60d);
    options.ForceFormat("gdigrab");
}).OutputToFile(@"D:\test.mp4")
    .CancellableThrough(out var cancelAction)
    .ProcessAsynchronously();
Console.WriteLine("Start record");
Console.WriteLine("Type enter to end recording");
Console.ReadLine();
cancelAction();
```

## Comments

- Perhaps the problem is caused by killing the ffmpeg process.

- I have tested this manually using the command line and everything works fine.

**Comment by rosenbjerg** [comment]
Try setting timeout to 1000 or something like that to allow for ffmpeg to stop gracefully
![image](https://user-images.githubusercontent.com/11181960/135575815-6f2c7d01-3ff5-4124-b4b5-6994b107a125.png)

**Comment by nikeee** [comment]
Could this be the same issue as in #256?

**Comment by li-zhixin** [comment]
Now, the issue can be closed because the solution is worked.
