### ISSUE TITLE
You need to fix this lib.

### ISSUE THREAD

**Issue by AaronAnz** [rosenbjerg/FFMpegCore#26]
Terrible documentation, a copyargument uses 90% cpu and takes AGES to complete, progress doesnt report right. Ditching this LIB immediately. 

Using params "-c copy -bsf:a aac_adtstoasc" get through a 2gb .ts file in like 10 seconds with regular ffmpeg. It takes a literal eternity even if you use the following with your lib:
    public class RealCopyArgument : Argument
    {
        public override string GetStringValue()
        {
            return "-c copy -bsf:a aac_adtstoasc";
        }
    }

**Comment by vladjerca** [comment]
Yeah, feel free to contribute to it or take it as it is :)
