### ISSUE TITLE
How to add custom args right after ffmpeg?

### ISSUE THREAD

**Issue by TahaBerkay** [rosenbjerg/FFMpegCore#267]
When I use WithCustomArgument and then call Arguments, it prints out the generated ffmpeg command. But this customarg is written between input and output command as written below:
`-i \"rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov\" -c:v vp9 -f webm -rtsp_transport tcp \"\\\\.\\pipe\\FFMpegCore_096e7a41-cb71-4f3f-a07c-473450cb1b65\" -y`

How can I force to add "-rtsp_transport tcp" at the beginning of FFmpeg command? Expected:
`-rtsp_transport tcp -i \"rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov\" -c:v vp9 -f webm \"\\\\.\\pipe\\FFMpegCore_096e7a41-cb71-4f3f-a07c-473450cb1b65\" -y`

[As shown here](https://stackoverflow.com/a/23302601/2528884)

Not sure, but may be custom argument support needed in WithGlobalOptions?

**Comment by rosenbjerg** [comment]
Add the custom argument to the input file arguments instead of the output file arguments
