### ISSUE TITLE
Problem with copying RTSP input stream to output pipe (without encoding)

### ISSUE THREAD

**Issue by TahaBerkay** [rosenbjerg/FFMpegCore#269]
Anyone to help me here?

Trying to create this command in ffmpegcore:
`ffmpeg -rtsp_transport tcp -i rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov -acodec copy -vcodec  copy -preset ultrafast -t 20  d:/x.mp4`

Ignore the mp4 at the end, I'd like to stream into pipe and then web player like in video tag in html.

This is what I have written:
```
                await FFMpegArguments
                    .FromUrlInput(url, options => options.WithCustomArgument("-rtsp_transport tcp"))
                    .OutputToPipe(new StreamPipeSink(outputStream), options => options
                    .CopyChannel()
                    .WithFastStart()
                    .WithCustomArgument("-preset ultrafast")
                    .WithCustomArgument("-t 20") )
                    .ProcessAsynchronously(true);
```

**Even** I change/add the available/new codecs or format (WithCustomArgument,WithVideoCodec,ForceFormat) , didn't help me.

**And** any help to improve the speed of ffmpeg to stream from rtsp to web player? Any way to do it without encoding?

**Comment by TahaBerkay** [comment]
The following gives me a missing output format. After I add any format, it gives me an incorrect codec.

```
                await FFMpegArguments
                    .FromUrlInput(url, options => options
                        .WithCustomArgument("-rtsp_transport tcp")
                        )
                    .OutputToPipe(new StreamPipeSink(outputStream), options => options
                        .WithVideoCodec("copy")
                        .WithAudioCodec("copy")
                        .WithSpeedPreset(Speed.UltraFast)
                        .WithDuration(TimeSpan.FromSeconds(20))
                        )
                    .ProcessAsynchronously(true);
```

**Comment by rosenbjerg** [comment]
You may need to specify format, with ForceFormat, for the input

**Comment by rosenbjerg** [comment]
Closed due to inactivity
