### ISSUE TITLE
how to add an background image to a phone video?

### ISSUE THREAD

**Issue by FlameskyDexive** [rosenbjerg/FFMpegCore#27]
how to add an background image to a phone video?
for example, i have a video that is 720*1280  portrait, then i want to convert it to a wide video 1280*720, the black part will filled with a background image, how should i do?

**Comment by rosenbjerg** [comment]
This seems more like a question belonging [here](https://stackoverflow.com/questions/tagged/ffmpeg)?

**Comment by rosenbjerg** [comment]
Closing this issue as this question doesn't seem to be related this library but rather ffmpeg in general. Please reopen if you do know how to do it with ffmpeg, but just not with this library.
