### ISSUE TITLE
Unit test Image_AddAudio which uses JoinImageSequence produces synthetic audio and pictures are all in black.

### ISSUE THREAD

**Issue by JiangTaoShi** [rosenbjerg/FFMpegCore#270]
Unit test Image_AddAudio for this method,Synthetic audio and pictures are all in black.

**Comment by rosenbjerg** [comment]
Fixed in #319
Will release next version containing this fix soon

**Comment by rosenbjerg** [comment]
Version 4.8 has just been released, and contains fix for this issue :)
