### ISSUE TITLE
Add possibility to configure a working directory for FFMpeg

### ISSUE THREAD

**Issue by BobSilent** [rosenbjerg/FFMpegCore#272]
**My Problem:**
I have multiple folder where each folder contains a m3u8 playlist and the media files. e.g. a master.m3u8 with references to some ts or mp4 files located in the same folder.
the files are all referenced relative to the m3u8 file.

When calling ffmpeg from within the directory ffmpeg can find the media files of the playlist.
but if the working directory is somewhere else ffmpeg searches the relative file in the current working directory.

**Solution**
Provide the [WorkingDirectory](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.processstartinfo.workingdirectory?view=net-5.0#System_Diagnostics_ProcessStartInfo_WorkingDirectory) property via `ffMpegOptions` (i can create a PR if this is a wanted change)

https://github.com/rosenbjerg/FFMpegCore/blob/5107ef0ec64c2a7530eaaacb12225f3384250cee/FFMpegCore/FFMpeg/FFMpegArgumentProcessor.cs#L152-L159

this would allow setting the working directory for each run.

**Comment by rosenbjerg** [comment]
Support for specifying working directory seems like a great idea. I'd gladly accept a PR adding that functionality :)

**Comment by rosenbjerg** [comment]
I have added support for specifying working directory because I'm plan on publishing the next version of this library soon, to get all the other nice features that has been added out

**Comment by rosenbjerg** [comment]
This is now supported in version 4.6.0 of this library :)
