### ISSUE TITLE
H.265 Codec support?

### ISSUE THREAD

**Issue by ElrohirGT** [rosenbjerg/FFMpegCore#276]
Hi, I just started using your wrapper for ffmpeg, I find it really cool but I couldn't find a way to use the H.265 codec instead of the H.264 when converting a video. Ffmpeg added support for this codec back in 2014, I hope is not much of an issue to implement.

**Comment by rosenbjerg** [comment]
Yes, it was extremely easy.
It will be included in next version of this library

**Comment by ElrohirGT** [comment]
Ok, thank you for the rapid response!
