### ISSUE TITLE
How do i loop through the images in the ImageInfo.FromPath(@"..\1.png"),?

### ISSUE THREAD

**Issue by reteshg** [rosenbjerg/FFMpegCore#28]
static void Main(string[] args)
{
    FFMpeg encoder = new FFMpeg();

    encoder.JoinImageSequence(
        new FileInfo(@"..\joined_video.mp4"),
        1, // FPS
        ImageInfo.FromPath(@"..\1.png"),
        ImageInfo.FromPath(@"..\2.png"),
        ImageInfo.FromPath(@"..\3.png")
    );
}

**Comment by rosenbjerg** [comment]
I don't understand what you are asking.
Could you please try describing what you've tried and what you're after

**Comment by rosenbjerg** [comment]
Closing this issue as no details are provided.
Please reopen when you have some
