### ISSUE TITLE
Continuous Snapshots on Live Stream

### ISSUE THREAD

**Issue by RobbieElias** [rosenbjerg/FFMpegCore#280]
I was hoping I could get some help with my issue:

I'm trying to generate snapshots from a live stream every 1 second, and obtain them as Bitmaps. Basically, I'm trying to perform the following command:

`ffmpeg -i "udp://192.168.2.12:9000" -c:v png -s 256x144 -vf fps=1 -update 1 -y test.png`

This generates a PNG every second. What I'm trying to accomplish with FFMpegCore is to receive a Bitmap every second.

Here's my code so far:

```
using (var ms = new MemoryStream())
{
    await FFMpegArguments
        .FromUrlInput(new Uri("udp://192.168.2.12:9000"))
        .OutputToPipe(new StreamPipeSink(ms), options => options
            .ForceFormat("rawvideo")
            .WithVideoCodec(VideoCodec.Png)
            .Resize(new Size(Config.JpgWidthLarge, Config.JpgHeightLarge))
            .WithCustomArgument("-vf fps=1 -update 1")
        )
        .NotifyOnProgress(o => 
        {
            try
            {
                if (ms.Length > 0)
                {
                    ms.Position = 0;
                    using (var bitmap = new Bitmap(ms))
                    {
                        // Modify bitmap here

                        // Save the bitmap
                        bitmap.Save("test.png");
                    }
                }
            }
            catch { }
        })
        .ProcessAsynchronously();
}
```

The problem I'm having is that the MemoryStream always contains the same frame (the first one that's read), and it never gets updated after that. So, the image that's saved is always the same.

Is there a way to obtain a new Bitmap each time a new frame is generated?

Thanks!

**Comment by Jan1503** [comment]
You need to "reset" the memorystream as FFMpeg just append the images to it...you set the position to 0 so every bitmap generated is the first one captured.
You could check the length of the stream and you will see it gets larger and larger, containing all the images from the beginning.
So just add `ms.SetLength(0);` after you process the bitmap and your good to go.

Regards,
Jan

**Comment by RobbieElias** [comment]
That works, thanks!

**Comment by rosenbjerg** [comment]
Thank you @Jan1503!
