### ISSUE TITLE
I am impressed with this command line tool wrapper - thinking of cloning it for MkvExtract/MkvMerge

### ISSUE THREAD

**Issue by mshiels** [rosenbjerg/FFMpegCore#282]
Would that be something everyone is ok with?  It's a really cool way to build up an interface for command line programs.  So much so that I am using it in my vide processing pretty extensively. 

basically it does a mediaInfo/FFProbe of a file
then does all the following processing
- checks for 'related files in it's current location' ie external subtitles
- checks for all the internal audio/subtitles
- checks to see if it needs to download subtitles (if internal only has image or none)
- checks to see if it has a mixed CC type subtitles embedded and pulls that out
- finally merging it all back into one nice Mkv file. 
So far it's doing really well, finding some bugs in MediaInfo where it's not properly reporting stream numbers if say video is the second one etc.  But FFmpeg/FFmpegcore worked it out just fine.  
Next addition is to also get it to do x265 encoding, based on the biggest files I have/highest quality inputs to crunch down.

**Comment by rosenbjerg** [comment]
As this library is MIT licensed, you are free to use it in whatever application you want to :)

**Comment by rosenbjerg** [comment]
I don't think cloning the library would make much sense though. Why not just use it, and get updates with fixes and features for free?

**Comment by mshiels** [comment]
I do use it in my application, but I was going to massage the code into a wrapper for MKVMerge/Extract etc, so they too would have a nice .Net wrapper for easier access??  But only with the permission of the authors of this one.
