### ISSUE TITLE
How to convert m3u8 to MP4?

### ISSUE THREAD

**Issue by bbhxwl** [rosenbjerg/FFMpegCore#284]
C# how to run the following code?

ffmpeg.exe -i http://xxx.com/test.m3u8 D:\output.mp4

**Comment by bbhxwl** [comment]
Although the following code can be implemented, if I record a live broadcast, how should I segment the video? I close the program directly. MP4 is damaged


```
 string inputPath = "http://hls.cntv.lxdns.com/asp/hls/850/0303000a/3/default/978a64ddd3a1caa85ae70a23414e6540/850.m3u8";

                     var a= FFMpegArguments
         .FromUrlInput(new Uri(inputPath)).OutputToFile("I:\\out2.mp4").ProcessAsynchronously();
               
```

**Comment by rosenbjerg** [comment]
Use [CancellableThrough](https://github.com/rosenbjerg/FFMpegCore/blob/7461407f9240140203503f972c3b1afa0f814c6c/FFMpegCore/FFMpeg/FFMpegArgumentProcessor.cs#L65) with a timeout great enough that ffmpeg has time to "finish up" the file so that it can be read
