### ISSUE TITLE
live stream/ re-stream

### ISSUE THREAD

**Issue by alllucky1996** [rosenbjerg/FFMpegCore#29]
Can I use this library to live stream / re-stream videos? How to perform live stream / re-stream like?
It would be great if it could work with asp.net-core to do just that.
thank you so much !!!

**Comment by rosenbjerg** [comment]
This library does not currently have any way to return a stream of "live" video, so it isn't possible with this library for now. If you have any suggestion to how to add this capability to the library, I am very open to supporting it.
But for now, it isn't supported
