### ISSUE TITLE
Make setters public on MediaStream classes

### ISSUE THREAD

**Issue by melinyi** [rosenbjerg/FFMpegCore#296]
When I serialized the Stream with JSON, I couldn't deserialize it because the set permission was internal

AudioStream.cs
MediaStream.cs
SubtitleStream.cs
VideoStream.cs

Fix
`public Properties { get; internal set; }`

To

`public Properties  { get; set; }`

**Comment by melinyi** [comment]
Thank you very much for the good source code

**Comment by rosenbjerg** [comment]
Version 4.8 has just been released, and contains fix for this issue :)
