### ISSUE TITLE
Can someone explain the purpose and usage of CancellableThrough(CancellationToken token, int timeout = 0)

### ISSUE THREAD

**Issue by GuyWithDogs** [rosenbjerg/FFMpegCore#298]
Can someone explain what the 

`        public FFMpegArgumentProcessor CancellableThrough(CancellationToken token, int timeout = 0)
        {
            token.Register(() => CancelEvent?.Invoke(this, timeout));
            return this;
        }`

I saw the examples in VideoTests.cs, but I don't get what it's trying to do. What I was _hoping_ to do was figure out a way to put a timeout on a transcoding operation in case we run into something that takes "too long" - e.g. say over 30 seconds. I'd like the ffmpeg instance to die, and return "false" from a ProcessAsynchronously() call. But I just don't understand what this is trying to do.

Thanks.

**Comment by rosenbjerg** [comment]
It is a way to obtain a reference to a cancellation token that can be used for cancelling the ffmpeg processing
