### ISSUE TITLE
Ability to kill ffprobe process

### ISSUE THREAD

**Issue by zhuker** [rosenbjerg/FFMpegCore#299]
How do I cancel a long-running `ffprobe`?

When I run the below unit test the `ffprobe` process still keeps running even after unit test quits (i am on MacOS)

There's a `-timeout` option in recent ffprobe versions but it is not universal enough to be useful, eg even the time unit depends on the protocol used (can be milliseconds or microseconds for http vs rtmp)

I'd like to be able to forcefully kill a run-away ffprobe process

```
[Test]
public void CancelFfprobeAsync()
{
    var task = FFProbe.AnalyseAsync(
        "https://devstreaming-cdn.apple.com/videos/streaming/examples/img_bipbop_adv_example_fmp4/master.m3u8",
        checkExists: false);
    task.Wait(100, CancellationToken.None);
}
```

**Comment by rosenbjerg** [comment]
Version 4.8 has just been released, and contains fix for this issue :)
