### ISSUE TITLE
Can't get it to work

### ISSUE THREAD

**Issue by oxodao** [rosenbjerg/FFMpegCore#3]
Hi,
I can't get this lib to work and it seems to be the only one that has what I want.
It crashes like this
[Picture](https://image.noelshack.com/fichiers/2019/12/3/1553069810-aze.png)

Am I doing something wrong ?

**Comment by vladjerca** [comment]
@oxodao Are you using the binaries found [here](https://github.com/vladjerca/FFMpegCore/tree/master/FFMpegCore/FFMPEG/bin)?

**Comment by oxodao** [comment]
I am indeed

**Comment by vladjerca** [comment]
@oxodao Then you can either download the solution and try to debug to see the root cause.

Or 

Attach a sample video + code so I can debug this scenario :)

**Comment by oxodao** [comment]
For some reason it seems to work fine on my other machine with a fresh new install of Windows in a new project. I'll try to debug that as soon as I get home 

EDIT: Derp i haven't tested what was crashing on my other machine... ><
EDIT2: It seems to be something related to webm format, it does work correctly with MP4
It may have something to do with the fact that my webm file only has a audio stream and no video stream?

**Comment by oxodao** [comment]
Ok, so I have not debugged the lib on my computer but what I think it is, is that in FFProbe.cs you are implying that the file contains a video, which is not always the case:
```cs
int videoIndex = metadata["streams"][0]["codec_type"] == "video" ? 0 : 1,
audioIndex = 1 - videoIndex;
```

Then it probably crashes there:
```cs
var bitRate = Convert.ToDouble(metadata["streams"][videoIndex]["bit_rate"], CultureInfo.InvariantCulture);
```

You might need to check for the existance of a video field before getting it

Here is a sample video that has the problem: https://u.oxodao.fr/instru.cloud.rap.pandrezz.mp4



EDIT:
The result of the ffprobe command give different result according to the format. For example the mp4 file (with the aac codec) there will be a duration but in a webm one (opus codec) it won't be there so i'm not sure about how to get the duration on those one...

So for now, I just used a raw ffmpeg binary with the `-vn` to convert to mp3, without the library. But if you decide to support this case I'll be using it to have my nice progess bar ;)

**Comment by vladjerca** [comment]
@oxodao Thanks for all the info. I'll look into this as soon as I can (that file was pending a re-write anyway)

**Comment by vladjerca** [comment]
@oxodao https://www.nuget.org/packages/FFMpegCore/1.0.7 this should do the trick 👍
