### ISSUE TITLE
Pipe ffmpeg errors to get duration

### ISSUE THREAD

**Issue by bradley-varol** [rosenbjerg/FFMpegCore#301]
Is it possible to pipe errors? This seems to be the most reliable way to get duration.

Apologies if this is something obvious that I've missed. Was hoping for something like this:
```
await Cli.Wrap("ffmpeg")
    .WithArguments("-i pipe: -f null -")
    .WithStandardInputPipe(PipeSource.FromStream(new MemoryStream(source)))
    .WithStandardErrorPipe(PipeTarget.ToStream(outputStream))
    .ExecuteBufferedAsync();
```

**Comment by rosenbjerg** [comment]
See [this section in the readme](https://github.com/rosenbjerg/FFMpegCore#input-piping)
