### ISSUE TITLE
Ffmpeg cannot obtain the correct resolution under certain circumstances

### ISSUE THREAD

**Issue by git-Charlie** [rosenbjerg/FFMpegCore#302]
For example, I rotated the video by 90 degrees with this command.

`ffmpeg -i input.mp4 -map_metadata 0 -metadata:s:v rotate="90" -codec copy output.mp4`

Suppose the original video resolution is 720*480
Then the transformed video resolution is 480*720

but `FFProbe.AnalyseAsync(FilePath)`; still returns the untransformed resolution

Also sorry to ask, but is there some efficient way to get frequent screenshots of any frame or time of a video?

Now I'm using the  ` FFMpeg.SnapshotAsync`, But after looking at the source code I think this has to be re-read and verified every time. I tried to modify it but it doesn't work.

This is my code, and I really need help with this .
```

        var duration = (int)(_mediaInfo.Duration.TotalSeconds);
        var step =(int)(duration / (double)( duration > 180 ? 60 : 30));
        var arg= FFMpegArguments.FromFileInput(FilePath, false);
        var i = 1;
        while (i < duration)
        {

            var timespan = TimeSpan.FromSeconds(i);
            await using var ms = new MemoryStream();
            IPipeSink s = new StreamPipeSink(ms);

            void Ac(FFMpegArgumentOptions options) =>
                options
                    .ForceFormat("rawvideo")
                    .Seek(timespan)
                    .SelectStream(0, 0)
                    .WithVideoCodec(VideoCodec.Png)
                    .WithFrameOutputCount(1);
            i += step;
            if (await arg.OutputToPipe(s, Ac).ProcessAsynchronously())
            {
                Console.WriteLine(arg.Text);
                yield return ms.ToArray();
            }
        }

```

**Comment by rosenbjerg** [comment]
That is because that rotation is just saved as metadata, and handled by the media player. The actual media content is not rotated, and that behaviour is intended on ffmpeg's side
