### ISSUE TITLE
Missing disposal of Image

### ISSUE THREAD

**Issue by pxysea** [rosenbjerg/FFMpegCore#304]
https://github.com/rosenbjerg/FFMpegCore/blob/7f1d04dde29557245a951515b81c4aed6dde301f/FFMpegCore/FFMpeg/FFMpeg.cs#L250

Image.FromFile(image) not dispose
and call extension Image.AddAudio has an error to delete temp file

**Comment by rosenbjerg** [comment]
Version 4.8 has just been released, and contains fix for this issue :)
