### ISSUE TITLE
Operation takes very long time

### ISSUE THREAD

**Issue by shaqo88** [rosenbjerg/FFMpegCore#305]
Calling the simplest code:
```
await FFMpegArguments
    .FromFileInput("in.wmv")
    .OutputToFile(outputFile)
    .ProcessAsynchronously();
```

With a specific sample, takes up to an hour.
Running following command in CLI took a second: `ffmpeg -i in.wmv -c copy out.wmv`
Can you help me?

**Comment by rosenbjerg** [comment]
To replicate that CLI command, you need to add `.CopyChannel()`
```csharp
await FFMpegArguments
    .FromFileInput("in.wmv")
    .OutputToFile(outputFile, options => options.CopyChannel())
    .ProcessAsynchronously();
```

Depending on the output file extension, ffmpeg might determine to transcode any/all streams in the mediafile.

Alternatively, remove `-c copy` from the CLI command and see if the behaviour is similar.

**Comment by shaqo88** [comment]
Thanks @rosenbjerg, it helped me.
In general, how can I "translate" a CLI command to `FFMpegCore` command?
