### ISSUE TITLE
way to get segments configured

### ISSUE THREAD

**Issue by milodude** [rosenbjerg/FFMpegCore#308]
I have been trying to configure the ffmpeg segment property in order to get several videos from a continuous input stream but  seems there is no option for this. Am I missing something? any suggestions will be welcomed. Thanks in advance! 

`ffmpeg -i "http://myUrl" -c copy -f segment -segment_time 120 -segment_wrap 2 -reset_timestamps 1 outt%02d.ts -y`

this last sentence creates videos of 2 minutes duration if  I run this in the command line. I was able to create a minute duration video  with this code but it just stops

`await FFMpegArguments
                .FromUrlInput(new Uri(inputPath))
                .OutputToFile(outputPath, overwrite:false, options => options.WithDuration(TimeSpan.FromMinutes(1)))
                .ProcessAsynchronously();`

**Comment by rosenbjerg** [comment]
Hi @milodude 
Assuming that your CLI invocation of ffmpeg gives you the result you want, the main difference between the two usages of ffmpeg is the arguments.
You should add `.CopyChannel()` and one or more `.WithCustomArgument(..)` to you output file options builder, to add the arguments from the CLI invocation that is missing in the C# version.

Something like 
```csharp
await FFMpegArguments
    .FromUrlInput(new Uri(inputPath))
    .OutputToFile(outputPath, overwrite: false, options => options
        .CopyChannel()
        .WithCustomArgument("-f segment")
        .WithCustomArgument("-segment_time 120")
        .WithCustomArgument("-reset_timestamps 1"))
    .ProcessAsynchronously();
```
should replicate the behaviour of the CLI invocation.

`.WithCustomArgument(..)` is used for all ffmpeg arguments that are not directly supported be this library
