### ISSUE TITLE
Duration is Not Supported for Streams (but Works for File Paths)

### ISSUE THREAD

**Issue by Mike-E-angelo** [rosenbjerg/FFMpegCore#309]
First off, thank you for making such a great project.  It does exactly what I am looking for and the design is discoverable and easy to use.

That stated, I did run into a problem. 😁

I noticed this comment:
https://github.com/rosenbjerg/FFMpegCore/issues/214#issuecomment-1012145297

And in particular this:

> This appears to be a [limitation](https://trac.ffmpeg.org/ticket/4358) of how ffprobe determines the duration of the container / streams

I was running into this issue and wondering why my duration was a default value when using a stream, and this appears to be it. 😭  Double-bummer because this is a cool/easy-to-use API.

I do have a way of calculating duration via MP3 files, which seem to work with MP4 files, but I am not sure if it will work w/ other video formats.  Either way, I will have to loop through a stream twice which is not ideal, especially for larger files.

I was wondering if there are any suggestions and/or workarounds for this issue.  I guess an obvious one is to save the stream as a file and use that, but that seems to defeat the purpose of streams. 😇

Thank you for any suggestions/consideration you can provide, and thank you for your efforts towards this project.

**Comment by rosenbjerg** [comment]
Hi @Mike-E-angelo 
Yeah ffmpeg and ffprobe does not provide the same functionality for files vs streams. Afaik, the main show-stopper is that these media container formats require seeking to work with, which is not possible, in general, for streams.

However, I don't think the workaround of saving the file temporarily on disk defeats the purpose of using Streams. The usage of Streams in general is more about working with a large file without having all of it in memory. 
Having the content on disk will of course introduce some additional I/O, but is the only proper way around ffmpeg/ffprobe's limitations with formats that require seeking.

If you are using ASP.NET Core, please be aware that the default configuration, with parsing of `IFormFile`s, actually does write the incoming data to disk(!)

If you do need to support mp3 and mp4 files, I don't think there are other ways around this with ffmpeg/ffprobe.

Another point might be that usually, the actual transcode operation would take long enough that the time spent on the additional I/O would be negligible

**Comment by Mike-E-angelo** [comment]
Thank you for the quick response @rosenbjerg.

> If you are using ASP.NET Core, please be aware that the default configuration, with parsing of IFormFiles, actually does write the incoming data to disk(!)

Note that I am using Blazor server-side and am getting a stream from the <input /> control.  I will have to further look into this.  Thank you for the pointer.  It would be super ideal to get access to those files but I doubt that is the case.

> Having the content on disk will of course introduce some additional I/O, but is the only proper way around ffmpeg/ffprobe's limitations with formats that require seeking.

Yeah, unfortunately I am going to have to bite it on this one, it seems.  However, I actually did a quick test with writing to a file and then reading that, and it was half as slow as the double-read that I was doing with the MP3 reader.  So, maybe not a bad implementation, especially for v1.

FWIW I am using a Path.GetTempPath(), writing/reading from there, and then deleting (in a `try`/`finally`).  If there is anything errant that you find about that, I would be interested in hearing about it.  Otherwise, thanks again for the heads up. 👍

**Comment by Mike-E-angelo** [comment]
FWIW in case anyone else runs into this issue, here is what I am using, as a starting point:

```
sealed class VideoFileDetails : IFileDetails
{
	public static VideoFileDetails Default { get; } = new();

	VideoFileDetails() : this(CopyToFile.Default) {}

	readonly ICopyToFile _copy;

	public VideoFileDetails(ICopyToFile copy) => _copy = copy;

	public async ValueTask<FileDetails> Get(Stream parameter)
	{
		var path = Path.GetTempFileName();
		try
		{
			await _copy.Get(new(parameter, path));

			var probe   = await FFProbe.AnalyseAsync(path).ConfigureAwait(false);
			var primary = probe.PrimaryVideoStream ?? throw new InvalidOperationException("Video Stream not found!");
			return new Entities.Marketplace.Inventory.VideoFileDetails
			{
				Duration             = probe.Duration,
				HorizontalResolution = (ushort)primary.Width,
				VerticalResolution   = (ushort)primary.Height
			};
		}
		finally
		{
			File.Delete(path);
		}
	}
}
```

`CopyToFile` found here:
https://github.com/DragonSpark/Framework/blob/328f808038cdaf0bb4a47af8ede72e34e12cf301/DragonSpark/Runtime/CopyToFile.cs
