### ISSUE TITLE
Missing "start" value 

### ISSUE THREAD

**Issue by Spartan-Hex-Shadow** [rosenbjerg/FFMpegCore#310]
Don't know if this is the correct place to put it, but we have the "bitrate" and "duration" values for audio and video files but not the "start" value. Can this be added? Example: 

Input #0, matroska,webm, from 'RT3437210d4e9eb53375a3b3d7bf8700a2.mka':
  Metadata:
    encoder         : GStreamer matroskamux version 1.16.2
    creation_time   : 2022-03-17T20:57:18.000000Z
  Duration: 00:02:31.54, start: 0.516000, bitrate: 22 kb/s
  Stream #0:0(eng): Audio: opus, 48000 Hz, stereo, fltp (default)
    Metadata:
      title           : Audio

**Comment by rosenbjerg** [comment]
Good suggestion
