### ISSUE TITLE
OutputToUrl() processed an input video but output file is not available.

### ISSUE THREAD

**Issue by enagaraj89** [rosenbjerg/FFMpegCore#311]
I am using PresignedUrl of a S3 object as an input and trying to output the video to S3 as well using presigned PUT url and using below code. I didn't get any errors but output file is not available in S3 location. 

string basePath = Path.GetDirectoryName(Assembly.GetExecutingAssembly().GetName().CodeBase);
            GlobalFFOptions.Configure(new FFOptions { BinaryFolder = basePath.Replace("file:\\", string.Empty) + "\\ffmpeg", TemporaryFilesFolder = basePath.Replace("file:\\", string.Empty) + "\\tmp" });

            var inputPath = "https://awss3.com/bucket/object/videos/input.mp4?AWSAccessKeyId=accesskey&Expires=1648782822&Signature=Nb4DIPdfjhsgduashc45A22W7BZ3kef4%3D";
            var outputPath = "https://awss3.com/bucket/object/videos/output.m3u8?AWSAccessKeyId=accesskey&Expires=1648800908&Signature=0Bqlb%2Bjusdferifw76374twfasfebs%2BPEFD9A%3D";
            
            FFMpegArguments
                 .FromUrlInput(new Uri(inputPath))
                 .OutputToUrl(new Uri(outputPath), options => options
                 //.OutputToFile(outputPath + "sampleedit1.mp4", false, options => options
                 .CopyChannel()
                 .WithCustomArgument("-f hls -hls_playlist_type vod -method PUT")
                     .Seek(TimeSpan.FromSeconds(30))
                     .WithDuration(TimeSpan.FromSeconds(90))
                     .UsingMultithreading(true))
                 .ProcessSynchronously();

Any help would be appreciated.

**Comment by rosenbjerg** [comment]
I don't think ffmpeg actually support reading the input from S3 and writing the results back to S3. Are you sure this should work? Can you give a working example of this just using `ffmpeg` (without this C# wrapper)?

A quick web search finds multiple SO threads discussing workarounds for very similar use-cases.
Please reopen if you find that this use-case is actually supported by ffmpeg
