### ISSUE TITLE
IOException: Pipe is broken when processing streams

### ISSUE THREAD

**Issue by jamessdixon** [rosenbjerg/FFMpegCore#312]
I am trying to convert an audio file.  It works fine when using File Input, but when I set it to Stream, it throws an _IOException: Pipe is broken_.

Here is the code:
```
            var inputPath = @"myInputFile.wav";
            var outputPath = @"myOutputFilemp3";
            var binariesFolder = @"XXX\bin\Debug\net6.0\ffmpeg";
            GlobalFFOptions.Configure(options => options.BinaryFolder = binariesFolder);
            var inputStream = File.OpenRead(inputPath);
            var streamPipeSource = new StreamPipeSource(inputStream);
            var outputStream = File.OpenWrite(outputPath);
            var streamPipeSink = new StreamPipeSink(outputStream);
            var arguments = FFMpegArguments.FromPipeInput(streamPipeSource);
            var processor = arguments.OutputToPipe(streamPipeSink);
            processor.ProcessSynchronously();
```

Here is the exception:

> FFMpegCore.Exceptions.FFMpegException
>   HResult=0x80131500
>   Message=Exception thrown during processing
>   Source=FFMpegCore
>   StackTrace:
>    at FFMpegCore.FFMpegArgumentProcessor.HandleException(Boolean throwOnError, Exception e, IReadOnlyList`1 errorData)
>    at FFMpegCore.FFMpegArgumentProcessor.ProcessSynchronously(Boolean throwOnError, FFOptions ffMpegOptions)
>    at ConsoleApp1.Class1.ConvertFileUsingStreams() in C:\XXX\Class1.cs:line 79
>    at Program.<Main>$(String[] args) in C:\XXX\Program.cs:line 8
> 
>   This exception was originally thrown at this call stack:
>     [External Code]
> 
> Inner Exception 1:
> IOException: Pipe is broken.

Is there a step I am missing?  Thanks in advance.

**Comment by rosenbjerg** [comment]
Most likely caused by asking ffmpeg to input or output a format that requires seeking, which isn't possible with streams. See the `FFMpegErrorOutput` property on the exception to confirm the problem

Please reopen if that is not the case, and both the input and output formats do not require seeking to work with.

**Comment by jamessdixon** [comment]
Here is the value from that property:  ffmpeg version 4.4-full_build-www.gyan.dev Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 10.2.0 (Rev6, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-shared --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libdav1d --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libglslang --enable-vulkan --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Guessed Channel Layout for Input Stream #0.0 : stereo
Input #0, wav, from '\\.\pipe\FFMpegCore_809ce49f-9a28-48f6-ada5-58819a0b31e7':
  Duration: 00:46:40.72, bitrate: N/A
  Stream #0:0: Audio: pcm_mulaw ([7][0][0][0] / 0x0007), 8000 Hz, stereo, s16, 128 kb/s
[NULL @ 000001fc382e90c0] Unable to find a suitable output format for '\\.\pipe\FFMpegCore_1a7f0845-98d0-442c-9ee2-285edc41b04f'
\\.\pipe\FFMpegCore_1a7f0845-98d0-442c-9ee2-285edc41b04f: Invalid argument

**Comment by jamessdixon** [comment]
And I don't understand what you mean: "seeking, which isn't possible with streams".  Should I not use File.OpenRead() and File.Open.Write()?  Is there a different way to pull the file from disk that supports seeking?

**Comment by rosenbjerg** [comment]
Just give ffmpeg the file paths instead. Then seeking isn't a problem.

The problem is that some formats require seeking, and that in general isn't possible with streams.

**Comment by Arlodotexe** [comment]
Streams _are_ designed to be seekable, but not all Stream implementations support it.

From https://learn.microsoft.com/en-us/dotnet/api/system.io.stream#remarks:
> Streams involve three fundamental operations:
> - You can read from streams. Reading is the transfer of data from a stream into a data structure, such as an array of bytes.
> - You can write to streams. Writing is the transfer of data from a data structure into a stream.
> - Streams can support seeking. Seeking refers to querying and modifying the current position within a stream. Seek capability depends on the kind of backing store a stream has. For example, network streams have no unified concept of a current position, and therefore typically do not support seeking.

**Comment by passee** [comment]
@rosenbjerg is there any update on this? streams are supposed to support seeking, is this a problem with ffmpeg itself?

**Comment by rosenbjerg** [comment]
@passee no, but you are of course welcome to dig into it
