### ISSUE TITLE
Why do I not get an OperationCanceledException when using cancellation token?

### ISSUE THREAD

**Issue by GuyWithDogs** [rosenbjerg/FFMpegCore#313]
I get an FFMpegException instead.  I've created the attached routine in a wrapper class so that I can unit test things. I was trying to add a failsafe timeout mode to kill off the FFMPEG process if it gets hung on a file (ran into a malformed PNG file that caused the FFMPEG process to spew "Invalid PNG signature" indefinitely, and that caused problems because the process never ended and other items to be transcoded did not get transcoded).

So my plan was to use the cancellation token option to basically start a timeout for the conversion command and kill things off if the FFMPEG process didn't terminate normally. I was going to use 5 minutes or so as my timeout, and most of the conversions take under a minute.

However, I had a lot of trouble trying to get this working and reporting an exception (let alone the grief in trying to figure out the xunit incantation to verify the exception was thrown. I was expecting an OperationCanceledException, but I get an FFMpegException instead. Now that I write this out, I wonder if I was expecting the OperationCanceledException from reading about CancellationToken and CancellationTokenSource usage, rather that what FFMpegCore might throw out.

Is there a better or more preferred way to put a time limit on command/task execution?

`
public async Task<bool> TranscodeVideoToAVIAsync(string localTmpInputFile, string passOutputFile, VideoSpecification videoSpec,
                    string passlogPrefix, double videoFrameRate, int videoDataRateKHz, string customArguments, int millisecondsTimeout)
{
	var cts = new CancellationTokenSource();
	bool result = false;
	try
	{
		var task = FFMpegArguments
					   .FromFileInput(localTmpInputFile)
					   .OutputToFile(passOutputFile, true, options => options
						   .WithVideoCodec(TranscodingConstants.FFMPEG_VIDEO_CODEC_LIBRARY_NAME)
						   .Resize(videoSpec.FrameWidth, videoSpec.FrameHeight)
						   .ForcePixelFormat("yuv420p")
						   .ForceFormat("avi")
						   .WithVideoBitrate(videoDataRateKHz)
						   .WithFramerate(videoFrameRate)
						   .WithCustomArgument(customArguments)
						   )
					   .CancellableThrough(cts.Token)
					   .ProcessAsynchronously();

		cts.CancelAfter(millisecondsTimeout);

		result = await task;
	}
	finally
	{
		cts.Dispose();
	}

	return result;
}`

**Comment by rosenbjerg** [comment]
Version 4.8 has just been released, and contains fix for this issue :)
