### ISSUE TITLE
how to set cover image to video

### ISSUE THREAD

**Issue by pxysea** [rosenbjerg/FFMpegCore#315]
hi all,
i tried ffmpeg 5.0 work ok
`ffmpeg -i video -i image.png -map 0 -map 1 -c copy -c:v:1 png -disposition:v:1 attached_pic out.mp4`

and use 4.4.1  has error:
Undefined constant or missing '(' in 'attached_pic'
[ @ 00000053913fea10] Unable to parse option value "attached_pic"

ask for help！

**Comment by rosenbjerg** [comment]
That error does not seem related to this .NET wrapper
