### ISSUE TITLE
Audio conversion fails when writing to output pipe

### ISSUE THREAD

**Issue by josago97** [rosenbjerg/FFMpegCore#318]
Hello,

I am trying to change the format of an audio that is obtained from a url to a Stream object. However, when executing the ffmpeg command it fails with the following error: "Error writing trailer of \\.\pipe\FFMpegCore_d411987f-0e0a-4f82-b2de-2228f3b6a8de: Invalid argument".

The code I use is the following:
```csharp
MemoryStream stream = new MemoryStream();

FFMpegArguments.FromUrlInput(new Uri("https://cadena100-cope.flumotion.com/playlist.m3u8"))
  .OutputToPipe(new StreamPipeSink(stream), options =>
  {
      options.WithAudioSamplingRate(48000)
      .WithCustomArgument("-loglevel debug -ac 2 -f wav");
  })
  .NotifyOnOutput((e, r) => Console.WriteLine($">>>>>> {e}"))
  .ProcessAsynchronously();

**Comment by rosenbjerg** [comment]
Please confirm that ffmpeg actually supports transcoding from a m3u8 source to a wav target. It is not possible to output to a stream if the transcoding requires seeking, since streams does not support that.
Consider outputting to a file instead if that is the case.

Reopen this issue if you find that ffmpeg should support this use-case

**Comment by josago97** [comment]
If instead of calling ffmpeg from the library I do it by creating a process, with the same arguments, it works.

```csharp
string path = "https://cadena100-cope.flumotion.com/playlist.m3u8";

Process.Start(new ProcessStartInfo
  {
      FileName = "ffmpeg",
      Arguments = $"-i \"{path}\" -ac 2 -f wav -ar 48000 pipe:1",
      UseShellExecute = false,
      RedirectStandardOutput = true,
  });

**Comment by rosenbjerg** [comment]
To replicate that cli command with this wrapper library, you shouldn't use `OutputToPipe(..)`, but instead `OutputToUrl("pipe:1")`.
But that would make it quite hard to access the resulting data in this case.. Not sure what the best approach is for this

**Comment by josago97** [comment]
Ok, so I think it's best to call ffmpeg directly through Process, thank you very much.
