### ISSUE TITLE
Joined videos in portrait are automatically rotated negative 90 degrees

### ISSUE THREAD

**Issue by tet-web-dev** [rosenbjerg/FFMpegCore#32]
I joined to videos from a phone in portrait mode with a 16:9 aspect ratio and the joined video was changed to landscape mode. What is the best solution for this? use encoder.join then follow that with Convert?

**Comment by rosenbjerg** [comment]
Could you please give an example of what you've tried?

**Comment by rosenbjerg** [comment]
Next version will include TransposeArgument which can be used to rotate the image back 90 degrees.
You can then follow up a Convert with a ArgumentContainer containing that Argument with the proper transpose value 0-3

**Comment by rosenbjerg** [comment]
Version 1.3.0 has now been uploaded to nuget. It contains the TransposeArgument.
Please try this out. Please reopen this issue if that does not solve your problem
