### ISSUE TITLE
ffprobe.exe  cannot find the file specified

### ISSUE THREAD

**Issue by babakmdi** [rosenbjerg/FFMpegCore#324]
this is my code:
" FFMpeg.Mute(openFileDlg.FileName, openFileDlgs.SelectedPath.ToString()); "
and i get this error ! why ?
System.ComponentModel.Win32Exception: 'An error occurred trying to start process 'ffprobe.exe' with working directory 'bin\Debug\net6.0-windows'. The system cannot find the file specified.'

**Comment by rosenbjerg** [comment]
ffprobe was not found where it was expected to be.
See [this section](https://github.com/rosenbjerg/FFMpegCore#path-configuration)
