### ISSUE TITLE
Request - Example code of capturing video from Webcam

### ISSUE THREAD

**Issue by GilchristT** [rosenbjerg/FFMpegCore#325]
Folks, thanks for what seems to be a great library.

I'm wondering if it's possible to get a more detailed example of how to create a video file from frames captured from a webcam?

I'm guessing this is fairly specific to the process used to capture the frames but even some example code would be great. I'm also guessing that the RawVideoStreamPipe example is what I should be looking at but it's a bit beyond my skills.

In my specific example, I'm trying to create a video from frames captured from OpenCVSharp. I don't know enough about image formats to understand how to get from a Mat to an IVideoFrame. Possibly Mat => Bitmap then use the FFMpegCore BitmapConverter but I'm guessing that's horribly inefficient?

Any pointers to an example project would be greatly welcome.

**Comment by rosenbjerg** [comment]
Take a look in the ffmpeg docs [here](https://trac.ffmpeg.org/wiki/DirectShow) and [here](https://trac.ffmpeg.org/wiki/Capture/Webcam) to build something along the lines of:

```csharp
...
.FromDeviceInput("video=\"Integrated Camera\"")
...
```
