### ISSUE TITLE
Question: Concatenating multiple video files

### ISSUE THREAD

**Issue by Spartan-Hex-Shadow** [rosenbjerg/FFMpegCore#326]
I want to concatenate multiple .mkv video files, basically replicate this command line arg using code:
"ffmpeg -i 34a0ea2a-eddb-4607-8029-142b1ed9a015_0_video.mkv -i  34a0ea2a-eddb-4607-8029-142b1ed9a015_6_video.mkv -filter_complex "[0:v][1:v]concat=2:1:0[vout]" -map [vout] out". While this argument works in the command line, FFMpeg.Join() throws errors. Is FFMpeg.Join() not what i am supposed to be using? Debugging it in Visual Studio seems to suggest it's trying to copy the stream rather than concatenate it? Any suggestions? Here is the output from the command line 

`ffmpeg version 2022-03-31-git-e301a24fa1-essentials_build-www.gyan.dev Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 11.2.0 (Rev7, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-sdl2 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libgme --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libtheora --enable-libvo-amrwbenc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-librubberband
  libavutil      57. 24.101 / 57. 24.101
  libavcodec     59. 25.100 / 59. 25.100
  libavformat    59. 20.101 / 59. 20.101
  libavdevice    59.  6.100 / 59.  6.100
  libavfilter     8. 29.100 /  8. 29.100
  libswscale      6.  6.100 /  6.  6.100
  libswresample   4.  6.100 /  4.  6.100
  libpostproc    56.  5.100 / 56.  5.100
Input #0, matroska,webm, from 34a0ea2a-eddb-4607-8029-142b1ed9a015_0_video.mkv:
  Metadata:
    ENCODER         : Lavf59.16.100
  Duration: 03:45:00.36, start: 0.000000, bitrate: 318 kb/s
  Stream #0:0: Video: h264 (High), yuv420p(tv, bt470bg/unknown/unknown, progressive), 640x480 [SAR 1:1 DAR 4:3], 36 fps, 36 tbr, 1k tbn
    Metadata:
      ENCODER         : Lavc59.18.100 libx264
      DURATION        : 03:45:00.361000000
Input #1, matroska,webm, from 34a0ea2a-eddb-4607-8029-142b1ed9a015_6_video.mkv:
  Metadata:
    ENCODER         : Lavf59.16.100
  Duration: 02:45:03.44, start: 0.000000, bitrate: 45 kb/s
  Stream #1:0: Video: h264 (High), yuv420p(tv, bt470bg/unknown/unknown, progressive), 640x480 [SAR 1:1 DAR 4:3], 22.67 fps, 22.67 tbr, 1k tbn
    Metadata:
      ENCODER         : Lavc59.18.100 libx264
      DURATION        : 02:45:03.441000000
File 'output.mkv' already exists. Overwrite? [y/N] y
Stream mapping:
  Stream #0:0 (h264) -> concat
  Stream #1:0 (h264) -> concat
  concat:out:v0 -> Stream #0:0 (libx264)
Press [q] to stop, [?] for help
[libx264 @ 0000026bbdee8b40] using SAR=1/1
[libx264 @ 0000026bbdee8b40] MB rate (1200000000) > level limit (16711680)
[libx264 @ 0000026bbdee8b40] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 0000026bbdee8b40] profile High, level 6.2, 4:2:0, 8-bit
[libx264 @ 0000026bbdee8b40] 264 - core 164 r3094 bfc87b7 - H.264/MPEG-4 AVC codec - Copyleft 2003-2022 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=15 lookahead_threads=2 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, matroska, to 'output.mkv':
  Metadata:
    encoder         : Lavf59.20.101
  Stream #0:0: Video: h264 (H264 / 0x34363248), yuv420p(tv, bt470bg/unknown/unknown, progressive), 640x480 [SAR 1:1 DAR 4:3], q=2-31, 1k tbn
    Metadata:
      encoder         : Lavc59.25.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A
[matroska @ 0000026bbdf8e640] Starting new cluster due to timestampe= 240.2kbits/s speed=58.1x
frame=160737 fps=606 q=-1.0 Lsize=  455699kB time=06:30:03.55 bitrate= 159.5kbits/s speed=88.2x
video:454528kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.257775%
[libx264 @ 0000026bbdee8b40] frame I:676   Avg QP:13.25  size: 24564
[libx264 @ 0000026bbdee8b40] frame P:41523 Avg QP:16.50  size:  6070
[libx264 @ 0000026bbdee8b40] frame B:118538 Avg QP:19.66  size:  1660
[libx264 @ 0000026bbdee8b40] consecutive B-frames:  0.6%  2.8%  1.4% 95.2%
[libx264 @ 0000026bbdee8b40] mb I  I16..4: 33.8% 46.4% 19.8%
[libx264 @ 0000026bbdee8b40] mb P  I16..4:  5.4%  4.3%  0.4%  P16..4: 52.1% 13.7%  9.2%  0.0%  0.0%    skip:15.0%
[libx264 @ 0000026bbdee8b40] mb B  I16..4:  0.4%  0.3%  0.0%  B16..8: 27.7%  1.6%  0.2%  direct:16.4%  skip:53.4%  L0:47.9% L1:50.1% BI: 2.0%
[libx264 @ 0000026bbdee8b40] 8x8 transform intra:43.6% inter:80.0%
[libx264 @ 0000026bbdee8b40] coded y,uvDC,uvAC intra: 25.9% 83.8% 47.3% inter: 7.9% 43.3% 7.6%
[libx264 @ 0000026bbdee8b40] i16 v,h,dc,p: 39% 24% 19% 18%
[libx264 @ 0000026bbdee8b40] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 14% 18% 56%  1%  3%  2%  3%  1%  2%
[libx264 @ 0000026bbdee8b40] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 29% 30% 24%  2%  4%  3%  4%  2%  3%
[libx264 @ 0000026bbdee8b40] i8c dc,h,v,p: 61% 21% 16%  2%
[libx264 @ 0000026bbdee8b40] Weighted P-Frames: Y:1.3% UV:0.9%
[libx264 @ 0000026bbdee8b40] ref P L0: 56.8%  3.4% 26.8% 12.9%  0.1%
[libx264 @ 0000026bbdee8b40] ref B L0: 80.2% 14.7%  5.1%
[libx264 @ 0000026bbdee8b40] ref B L1: 94.5%  5.5%
[libx264 @ 0000026bbdee8b40] kb/s:159.10`

**Comment by rosenbjerg** [comment]
Can you post the C# snippet you have tried with?

**Comment by Spartan-Hex-Shadow** [comment]
Got it resolved :)
