### ISSUE TITLE
Issue processing .gif with FromPipeInput

### ISSUE THREAD

**Issue by wolfcomp** [rosenbjerg/FFMpegCore#335]
When trying to process `.gif` files with `FromPipeInput` I only see 520 bytes being written to either the file or stream in question.

Code that is trying to be used when working as intended:
```cs
private async Task<Stream> HandleThumbnailVideo(Stream stream)
{
    var outputStream = new MemoryStream();
    var info = await FFProbe.AnalyseAsync(stream);
    var width = info.VideoStreams[0].Width;
    var height = info.VideoStreams[0].Height;
    var aspect = (float)width / height;
    if (Math.Abs(aspect - 1) >= float.Epsilon)
        throw new FormatException("Aspect ratio not 1:1");
    if (width < 256)
        throw new FormatException("Size not at or greater than 256x256");
    stream.Seek(0, SeekOrigin.Begin);
    await FFMpegArguments
        .FromPipeInput(new StreamPipeSource(stream))
        .OutputToPipe(new StreamPipeSink(outputStream), options => options
            .WithVideoCodec("libvpx-vp9")
            .ForceFormat("webm")
            .WithConstantRateFactor(12)
            .WithFramerate(60)
            .WithFastStart()
            .ForcePixelFormat("yuv420p")
            .WithVideoBitrate(500)
            .DisableChannel(Channel.Audio)
            .WithCustomArgument("-vf \"scale='min(512,iw)':-1\"")
            .WithCustomArgument("-quality good")
            .WithCustomArgument("-cpu-used 0"))
        .ProcessAsynchronously();
    return outputStream;
}
```

I have tested the exact command arguments in a console and FFmpeg has 0 issues processing it from the file then.
I also tested this code snip it with mp4 and had 0 issues with it only writing 520 bytes.

**Comment by rosenbjerg** [comment]
Could you show the command that worked? Were you also doing in-memory things there?

**Comment by wolfcomp** [comment]
The command used was the exact same as what the function calls set. And I wasn't doing anything more in-memory things than just writing the stream to a file. 

Edit: It's a while since I worked on the project where this was needed. And I think I found a way to execute the FFmpeg command instead of using this pipe.
