### ISSUE TITLE
FFMpegCore: trying to get the progress but only fires action when complete

### ISSUE THREAD

**Issue by Velocedge** [rosenbjerg/FFMpegCore#336]
I'm trying out FFMpegCore and it's converting files fine but I need the progress as it's encoding the video file.  It fires the action, progressHandler, but only when the value is 100 and the process complete.  It's supposed to fire throughout the process.

    FFMpegArguments
        .FromFileInput(InputFile)
        .OutputToFile(OutputFile, true, options => options
        .WithVideoCodec(VideoCodec.LibX264)
        .WithConstantRateFactor(21)
        .WithAudioCodec(AudioCodec.Aac)
        .WithVariableBitrate(4)
        .WithVideoFilters(filterOptions => filterOptions
            .Scale(VideoSize.Hd))
        .WithFastStart()).NotifyOnProgress(progressHandler, videoDuration)
    .ProcessAsynchronously();

...

        private Action<double> progressHandler = new Action<double>(p =>
        {
            //progress value from 0 to 100
            Debug.WriteLine(p);
            if (p == 100)
            {
                isProcessing = false;
            }
            });

I thought I might need to await the FFMpegArguments so I put it in a separate async method but it didn't do anything different.  I also downloaded the latest ffmpeg and ffprobe from the link on your site... no change.  So, how do I make it so progressHandler is fired throughout the process?

**Comment by rosenbjerg** [comment]
#339

**Comment by rosenbjerg** [comment]
This was fixed in a PR from keg247
