### ISSUE TITLE
Intercept event or log when new file is generated using CustomArgument -f segment.

### ISSUE THREAD

**Issue by chokosticks** [rosenbjerg/FFMpegCore#337]
Hi,

I am trying to figure out how to intercept an event or information when ffmpeg generates a new file when using the CustomArgument:

-f segment -segment_time 120

Is there some built in function or method I can use to accomplish this?

Thanks in advance!

**Comment by chokosticks** [comment]
Hi,

I managed to get it working using NotifyOnError and matching the logs using "[segment @" combined with "ended".

I don't know if there's a bug or if my setup is wrong. I only managed to get an output from NotifyOnError, but not from NotifyOnOutput.

**Comment by rosenbjerg** [comment]
FFMpeg writes all non-media output to std error, so that is actually expected

**Comment by chokosticks** [comment]
Okey, thanks for the clarification! :)
