### ISSUE TITLE
Looking for long term maintainer

### ISSUE THREAD

**Issue by vladjerca** [rosenbjerg/FFMpegCore#34]
I've been focusing on web development for a few years now, this project started as a small wrapper I wrote when I was developing some server side encoding routines.

I feel like I don't have the necessary time to maintain and keep this repository in a good shape so if anyone is interested, feel free to leave a comment here.

**Comment by rosenbjerg** [comment]
I am interested in helping maintain this package.
I use FFMpeg and FFProbe for several projects, both open-source and at work.
If you don't have the time to keep maintaining this repo, I'll gladly carry on the torch :)

**Comment by vladjerca** [comment]
@rosenbjerg I'll transfer ownership. Thanks!

LE: in order for me to transfer ownership, I'll need you to remove/rename your existing fork (naming conflict).

Let me know when I can start the transfer.

**Comment by rosenbjerg** [comment]
That sounds great!
I have just deleted my fork. I only kept it because it wanted to continue working on the project :)

**Comment by vladjerca** [comment]
@rosenbjerg I've initiated the transfer, from what I got from the docs the invitation to accept is valid for 24 hours.

Thanks again for supporting the project!

PS: if the invite expires, let me know.

**Comment by vladjerca** [comment]
@rosenbjerg I'm also going to need your `nuget` username in order to add you as an owner 😬

**Comment by rosenbjerg** [comment]
I have accepted the invitation, and my nuget username is rosenbjergsoftworks :)

**Comment by vladjerca** [comment]
I've send you a nuget invite as well, you should be good to go!

**Comment by rosenbjerg** [comment]
I've just accepted the NuGet invitation 👍
Thank you for not letting this package die!
