### ISSUE TITLE
at FFMpegCore.FFMpeg.Snapshot()... -> System.PlatformNotSupportedException: System.Drawing.Common

### ISSUE THREAD

**Issue by ep1kt3t0s** [rosenbjerg/FFMpegCore#342]
Folks,

Should `FFMpeg.Snapshot()` have to use `Bitmap` object? I don't think it works on Linux. I am trying to get `"System.Drawing.EnableUnixSupport": true,` working but is this the suggested way?

```
---> System.TypeInitializationException: The type initializer for 'Gdip' threw an exception.
 ---> System.PlatformNotSupportedException: System.Drawing.Common is not supported on non-Windows platforms. See https://aka.ms/systemdrawingnonwindows for more information.
   at System.Drawing.LibraryResolver.EnsureRegistered()
   at System.Drawing.SafeNativeMethods.Gdip.PlatformInitialize()
   at System.Drawing.SafeNativeMethods.Gdip..cctor()
   --- End of inner exception stack trace ---
   at System.Drawing.SafeNativeMethods.Gdip.GdipLoadImageFromDelegate_linux(StreamGetHeaderDelegate getHeader, StreamGetBytesDelegate getBytes, StreamPutBytesDelegate putBytes, StreamSeekDelegate doSeek, StreamCloseDelegate close, StreamSizeDelegate size, IntPtr& image)
   at System.Drawing.Image.InitializeFromStream(Stream stream)
   at System.Drawing.Bitmap..ctor(Stream stream)
   at FFMpegCore.FFMpeg.Snapshot(String input, Nullable`1 size, Nullable`1 captureTime, Nullable`1 streamIndex, Int32 inputFileIndex)
```

**Comment by rosenbjerg** [comment]
Hey
On .NET 6, System.Drawing.Common has finally been marked as Windows-only, instead of the previous solution of limited support on non-Windows systems.
So yeah, the overload of Snapshot that returns a Bitmap will only work on Windows.
I have considered cutting all the System.Drawing.Common dependent functionality to a second nuget package now that MS has decided to give up on supporting System.Drawing.Common on anything other than Windows.

**Comment by rosenbjerg** [comment]
You should however be able to use the overload that doesn't return a Bitmap on linux and macos :)

**Comment by ep1kt3t0s** [comment]
Yeah the overload may work but it seems to be writing onto the disk. In my use case, I generate snapshots every x seconds then merge them onto a single image. Wouldn't be very performant to write everything onto disk and read back.

I wonder if we can just re-use the code below without creating the Bitmap. I guess the question is how to represent the stream in an image format. I might give it a try to see if [ImageSharp](https://github.com/SixLabors/ImageSharp) can understand it.

https://github.com/rosenbjerg/FFMpegCore/blob/9f34591a03ef5db49b4b993122e03cbd8a7fa8c4/FFMpegCore/FFMpeg/FFMpeg.cs#L71-L85

But then, how can the overload write the `png` to the a without using Bitmap? Is it `ffmeg` doing it directly?
