### ISSUE TITLE
HardwareAcceleration CUDA

### ISSUE THREAD

**Issue by YamielVargas** [rosenbjerg/FFMpegCore#354]
Hello, I want to perform a transcoding with HardwareAcceleration (Nvidia GPU), I tested with FFmpeg direct commands in CMD, and it works perfectly, now I am integrating .NetFramework with FFmpegCore, I have achieved good results with "HardwareAccelerationDevice.D3D11VA" but now we need to do it with CUDA, but the hardware acceleration devices don't give me this option, I tried with CUVID believing that it is the same as CUDA but I can't get it to work.

          `FFMpegArguments
                .FromFileInput(fileS, true, options => options
                    .WithHardwareAcceleration(HardwareAccelerationDevice.CUVID))
                .OutputToFile(fileT + "." + format.ToLower(), true, options => options
                    .WithDuration(mediaInfo.Duration)
                    .UsingMultithreading(true)
                    //.WithVideoCodec(VideoCodec.LibX264)
                    .WithVideoCodec("h264_nvenc")
                    .WithAudioCodec(AudioCodec.Aac)
                    .WithVideoBitrate(150)
                    .WithVideoFilters(filterOptions => filterOptions
                        //CITY
                        .DrawText(DrawTextOptions
                            .Create("CDMX", "/Windows/Fonts/Arial.ttf")
                            .WithParameter("fontcolor", "white")
                            .WithParameter("fontsize", "70")
                            .WithParameter("box", "1")
                            .WithParameter("boxcolor", "black@0.6")
                            .WithParameter("boxborderw", "5")
                            .WithParameter("x", "0")
                            .WithParameter("y", "0"))
                    .Resize(340, 260)
                    .WithFramerate(15)
                    .UsingThreads(6)
                    .WithFastStart())
                .NotifyOnProgress(OnPercentageProgess, mediaInfo.Duration)
                .NotifyOnProgress(OnTimeProgess)
                .ProcessSynchronously();`

This is the answer of Attempt with **CUVID**, anyway, **CUVID** and **CUDA** are not the same

![image](https://user-images.githubusercontent.com/48700514/183216089-e71d61cc-2ff8-4901-afdc-4f17a78591b1.png)

![image](https://user-images.githubusercontent.com/48700514/183216262-da96a2cf-51f8-4a9c-b5c4-d116f04994b5.png)

![image](https://user-images.githubusercontent.com/48700514/183216347-f5939214-070b-4718-9f01-94d30782cd82.png)

This the comand in CMD with **-hwaccel cuda**

![image](https://user-images.githubusercontent.com/48700514/183216698-27cdccf0-2889-4b64-8fc2-86595867ce14.png)

**Comment by rosenbjerg** [comment]
Added [here](https://github.com/rosenbjerg/FFMpegCore/pull/386/commits/3080fb44b32c67e02304d60ba6a88626cff6f5dd)
