### ISSUE TITLE
AddAudio call causes FFMPEG to hang for specific piece of media

### ISSUE THREAD

**Issue by OtherwiseJunk** [rosenbjerg/FFMpegCore#356]
I've been using this library for adding a wilhelm scream to static images in a discord bot, but I've come across a piece of media where the `AddAudio` call hangs indefinitely, and the ffmpeg process that gets created seems to hang indefinitely as well.

 https://cdn.discordapp.com/attachments/855227586212134922/1015673376397852772/IMG_5814.png
 
 The media itself seems pretty mundane, but I wasn't sure if this is an issue you've seen before or if I'm just misusing the library somehow 😅

**Comment by ADefWebserver** [comment]
Try running FFMpeg.Mute first.

**Comment by rosenbjerg** [comment]
Thank you @ADefWebserver

**Comment by OtherwiseJunk** [comment]
hey @rosenbjerg @ADefWebserver  sorry for the huge delay on responding, I just got around to attempting this suggestion but I don't think this answer makes sense, at least to me 😅

I'm reading an image file into memory and then invoking the AddAudio on that image in memory, what should I be attempting to mute in this case? The image file is a .png/.jpeg and shouldn't have any audio information, and presumably I wouldn't want to mute the audio input.

```
private bool AddWilhemToImage(Stream fileStream, string fileName)
{
    System.Drawing.Image image = MakeImageDimensionsEven(System.Drawing.Image.FromStream(fileStream));
    return image.AddAudio("./wilhelm.ogg", $"{fileName}.mp4");            
}
```        

This will never return in the scenario I'm running into, the filename is a randomly generated guid so it shouldn't be running into any conflict with existing files.

Please let me know if something is just going over my head 😅This method usually returns, but I've found a handful of images like the one above that will just completely cause this to hang, tying up FFMPEG.

**Comment by ADefWebserver** [comment]
@OtherwiseJunk I am doing the exact same thing you are (adding audio to a .mp4 file that I constructed of just images), and this is what worked for me.

**Comment by OtherwiseJunk** [comment]
I don't have an mp4 file prior to calling addaudio, the mp4 file is created as a result of that call. 

Since the call never returns, what am I calling mute on? Sorry if I'm just being an idiot

**Comment by ADefWebserver** [comment]
```
        // Join files
        FFMpeg.Join($"{SubProcessingFolder}\\PreFinalVideoNoAudio.mp4", colSilentVideoFiles.ToArray());

        // Add Audio.mp3
        // first mute the audio
        FFMpeg.Mute($"{SubProcessingFolder}\\PreFinalVideoNoAudio.mp4", 
             $"{SubProcessingFolder}\\PreFinalVideoNoAudioMuted.mp4");

        // Add the audio
        FFMpeg.ReplaceAudio($"{SubProcessingFolder}\\PreFinalVideoNoAudioMuted.mp4"
            , $"{ProcessingPath}\\{VideoNumber}.mp3"
            , $"{SubProcessingFolder}\\PreFinalVideoWithAudio.mp4", false);
```

**Comment by OtherwiseJunk** [comment]
Ahh kk, your suggest makes more sense now, but I think you're doing things more manually than I am, I don't create the mp4 prior to my call, I'm using the AddAudio function on an Image directly which creates an mp4. 

I should probably just do what you're doing in the meanwhile, manually create the mp4 prior and adding audio myself, but it would be nice if the Image.AddAudio functionality worked consistently 😅 maybe I'm just using it wrong.

Thanks!

**Comment by ADefWebserver** [comment]
Also if you are adding images, I recently had to implement this code to fix images, from IPhones, that came out sideways: [Handling the orientation EXIF tag in images using C#](https://devblog.cyotek.com/post/handling-the-orientation-exif-tag-in-images-using-csharp)
