### ISSUE TITLE
Ability to obtain BitDepth

### ISSUE THREAD

**Issue by tombogle** [rosenbjerg/FFMpegCore#358]
The output from FFprobe contains some useful information that gets thrown away. Specifically, I would like to be able to access the bit depth, when available. This is in bits_per_raw_sample, when that is not N/A. When it is N/A, a good fallback would be to try bits_per_sample. Are you willing to take this change as a pull-request if I fork this repo and take a stab at implementing it?

**Comment by tombogle** [comment]
Since bit depth is only relevant for lossless encodings, this could either return 0 for lossy encodings or it could be a nullable int and return null.

**Comment by rosenbjerg** [comment]
Solved by your own PR :)
version 5 which includes your fix will soon be released
