### ISSUE TITLE
FFMpeg.Join video and audio is out of sync

### ISSUE THREAD

**Issue by jokerham** [rosenbjerg/FFMpegCore#362]
I have generated many individual video files using BMP and audio with 1 second delay.

I wanted to join all the videos and used the method.

Individual video worked find (since it only generated from 1 bmp)

but the result after join shows un sync between audio and video.

Is there a way to solve this?

```
        // Generating single video
        public void GenerateMP4(string audioFileName, string pictureFileName, string outputFileName, int duration)
        {
            FFMpegArguments
                .FromFileInput(pictureFileName)
                .AddFileInput(audioFileName)
                .OutputToFile(outputFileName, true, arguments => arguments.WithCustomArgument(string.Format("-af apad=pad_dur={0}", duration)))
                .ProcessSynchronously();
        }

        // Merging the video
        public void MergeMp4(ArrayList videoFileNames, string outputFileName)
        {
            string concatTsName = "concat:";
            int index = 0;

            FFMpeg.Join(outputFileName, videoFileNames.ToArray(typeof(string)) as string[]);
        }
```

**Comment by ADefWebserver** [comment]
This will fix the audio:

```
var success = FFMpegArguments
    .FromFileInput(outputFileName, true, opt => opt.WithCustomArgument("-async 25"))
    .OutputToFile("FinalVideo.mp4", true, opt => opt.WithCustomArgument("-r 25"))
    .ProcessSynchronously();
```

**Comment by jokerham** [comment]
Thanks for the reply.
But I solved it by doing it like below.

        private void ConcatenateMP4WithLimit(List<string> videoFilepathes, string outputFilepath)
        {
            string customArgument = "-filter_complex \"";

            for (int i = 0; i < videoFilepathes.Count; i++)
            {
                customArgument += "[" + i + ":0] ";
                customArgument += "[" + i + ":1] ";
            }

            customArgument += "concat=n=" + videoFilepathes.Count + ":v=1:a=1 [v] [a]\" -map \"[v]\" -map \"[a]\"";

            var argument = FFMpegArguments
                .FromFileInput(videoFilepathes[0]);

            for (int i = 1; i < videoFilepathes.Count; i++)
            {
                argument.AddFileInput(videoFilepathes[i]);
            }

            argument.OutputToFile(outputFilepath, true, arguments => arguments.WithCustomArgument(customArgument))
                .ProcessSynchronously();
        }

**Comment by rosenbjerg** [comment]
Thank you for posting your solution to this problem
