### ISSUE TITLE
OutputToPipe fails on macOS

### ISSUE THREAD

**Issue by GOATS2K** [rosenbjerg/FFMpegCore#365]
This operation fails on macOS.
```
await FFMpegArguments
            .FromFileInput(track.FilePath)
            .OutputToPipe(new StreamPipeSink(outputStream), options =>
            {
                options.WithAudioCodec(requestedCodec);
                options.WithArgument(new AudioBitrateArgument(bitrate));
            })
            .ProcessAsynchronously();
```

```
The path '/var/folders/n2/5qzqsyf97cq3tz608mpdqw2r0000gn/T/CoreFxPipe_FFMpegCore_1325ce6c-6e8e-497a-8c0a-c46703282209' is of an invalid length for use with domain sockets on this platform.  The length must be between 1 and 104 characters, inclusive. (Parameter 'path')

Actual value was /var/folders/n2/5qzqsyf97cq3tz608mpdqw2r0000gn/T/CoreFxPipe_FFMpegCore_1325ce6c-6e8e-497a-8c0a-c46703282209.
```

I see this is being addressed by https://github.com/rosenbjerg/FFMpegCore/pull/286, but the PR has been inactive for a while.

**Comment by ep1kt3t0s** [comment]
I am hitting the same problem. This is a genuine problem on MacOS and related to the generated long socket pipe name.

@rosenbjerg updated the code with this commit below that removed short pipe name generation. Is there a reason of using this long pipe names? It's breaking the code.
https://github.com/rosenbjerg/FFMpegCore/commit/3d50530c742bd5c3de39d6264a86f41b62ee1001

By default `Path.GetTempPath()` on MacOS returns a path like `/var/folders/n2/5qzqsyf97cq3tz608mpdqw2r0000gn/T` which is already long enough. If we also use a long pipe names, where the pipe name is appended to it by the `System.IO.Pipes`. Reference: https://github.com/dotnet/corefx/blob/master/src/System.IO.Pipes/src/System/IO/Pipes/PipeStream.Unix.cs#L67-L76

At the moment, the FFMpegCore is unusable for me on MacOS. There is a significant impact. Let's fix this.

**Comment by rosenbjerg** [comment]
PR by @ep1kt3t0s has been merged, so hopefully this will fix your issue.
I have included macos in the os test matrix
