### ISSUE TITLE
Join with multiple audio tracks

### ISSUE THREAD

**Issue by HenningF2** [rosenbjerg/FFMpegCore#372]
The join method works very well. But I want to merge some mp4-files that have three audio tracks (spanish, english, german).
The join method uses only the first audio track.
How can I join all three tracks or how can I choose the preferred one?

**Comment by rosenbjerg** [comment]
You can use `.SelectStream(..)` and the other similar methods:

https://github.com/rosenbjerg/FFMpegCore/blob/11abaeecc35bafa70bb3abd6a524acbb768445fa/FFMpegCore/FFMpeg/FFMpegArgumentOptions.cs#L64-L73

ffmpeg docs for map: [Selecting streams with the -map option](https://trac.ffmpeg.org/wiki/Map)

I hope this helps
