### ISSUE TITLE
'FFMpeg yuv420p encoding requires the width and height to be a multiple of 2!' error

### ISSUE THREAD

**Issue by e2gun** [rosenbjerg/FFMpegCore#375]
Hello,

When I use FFMpeg.JoinImageSequence method I got this error.

`System.ArgumentException: 'FFMpeg yuv420p encoding requires the width and height to be a multiple of 2!'`

`This exception was originally thrown at this call stack:
    FFMpegCore.Helpers.FFMpegHelper.ConversionSizeExceptionCheck(int, int)
    FFMpegCore.Helpers.FFMpegHelper.ConversionSizeExceptionCheck(System.Drawing.Image)
    FFMpegCore.FFMpeg.JoinImageSequence.AnonymousMethod__0(FFMpegCore.ImageInfo, int)
    System.Linq.Enumerable.SelectIterator<TSource, TResult>(System.Collections.Generic.IEnumerable<TSource>, System.Func<TSource, int, TResult>)
    System.Collections.Generic.LargeArrayBuilder<T>.AddRange(System.Collections.Generic.IEnumerable<T>)
    System.Collections.Generic.EnumerableHelpers.ToArray<T>(System.Collections.Generic.IEnumerable<T>)
    FFMpegCore.FFMpeg.JoinImageSequence(string, double, FFMpegCore.ImageInfo[])
    RabbitMq.Pages.IndexModel.OnPostProjectSubmit(RabbitMq.Pages.IndexModel.CustomImageData) in Index.cshtml.cs
`

**Comment by gensichen** [comment]
Hey, how did you resolve this issue?
