### ISSUE TITLE
File not found: ffmpeg

### ISSUE THREAD

**Issue by cdavidyoung** [rosenbjerg/FFMpegCore#376]
I first tested my Maui app on Windows and things are working well.  I am converting, trimming, and concatenating audio files with commands like

            FFMpegArguments
               .FromFileInput(file)
               .OutputToFile(mp3File, false
                             ,options => options
                             .WithCustomArgument($"-ss {ss} -t {t} -acodec copy")
                            )
               .ProcessSynchronously();

However, on both Android and MacCatalyst I am getting this error.  I figure it is just a matter of setting PATH but I am not sure how to do it.  Would it be possible to update the README to show what is necessary to run on each platform?  Thanks

**Comment by cdavidyoung** [comment]
Ok, now I understand that it is assumed that ffmpeg is already installed on whichever platform.  I just happened to have it installed on my Windows platform so it worked.  I subsequently downloaded ffmpeg to my Mac into the Downloads folder and was successfully able to run it specifying the BinaryFolder option:

            FFMpegArguments
               .FromFileInput(file)
               .OutputToFile(mp3File, false)
               .ProcessSynchronously(true, new FFOptions { BinaryFolder = "/Users/charlesyoung/Downloads", TemporaryFilesFolder = "/tmp" });

I need to see if I can include ffmpeg.exe as a resource in my bundle and copy it into the app folder and specify that as the BinaryFolder.

**Comment by cdavidyoung** [comment]
I am having a very hard time specifying the BinaryFolder to make it work on Mac.  I would like to bundle ffmpeg.exe with my app so that it will be deployed in the same folder.  The only thing I can get to work is BinaryFolder = "/Users/charlesyoung/Downloads" which is not really desirable for deployment.  Any tips would be appreciated!

**Comment by cdavidyoung** [comment]
I have since given up on bundling ffmpeg with my app and will probably just use brew to install it.

**Comment by cdavidyoung** [comment]
Well, I used brew to install ffmpeg and now it finds it at a command prompt.  I subsequently was able to run the Examples solution, but only after added the following to the project:

    <ItemGroup>
      <None Remove="runtime.osx.10.10-x64.CoreCompat.System.Drawing" />
    </ItemGroup>
    <ItemGroup>
      <PackageReference Include="runtime.osx.10.10-x64.CoreCompat.System.Drawing" Version="6.0.5.128" />
    </ItemGroup>

Otherwise I was getting an exception as described here: https://github.com/dotnet/core/issues/2746.  **We might want to update this package to make it possible to run on the Mac.**

So everything is great with the Examples solution of FFMpegCore.  However, when running my app under the same circumstances (and installing the package described above) I am still getting the exception that ffmpeg (or ffprobe) cannot be found.

Does anyone have an idea why ffmpeg can be found at the command prompt and when running the Examples app, but not when running my app?

**Comment by cdavidyoung** [comment]
I even tried setting the BinaryFolder to the explicit location of ffmpeg and ffprobe. The value of ffmpegexe is "/usr/local/bin/ffmpeg", which is exactly right.  I still get the exception that ffprobe cannot be found.

               FFOptions options = new FFOptions{ BinaryFolder = $"/usr/local/bin" };
               string ffmpegexe = GlobalFFOptions.GetFFMpegBinaryPath(options);
               var mediaInfo = FFProbe.Analyse(file);

**Comment by cdavidyoung** [comment]
@rosenbjerg any help here?  It seems like it should be a simple solution.  Also, it seems like we need to add the Drawing package to the repo to get the Examples to run on the Mac.  Do you want me to go to the trouble of forking, adding the package, and then submitting a merge request?

**Comment by cdavidyoung** [comment]
So I created a new Maui app and inserted just the bare minimum FFMpegCore code to call ffprobe when the button is clicked.  I am getting the following exception:

	ex	{Instances.Exceptions.InstanceFileNotFoundException: File not found: ffprobe  ---> System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'ffprobe' with working directory '/Users/charlesyoung/Projects/FFmpegTest/FFmpegTest/bin/Debug…}	

This is the code.  So somehow the FFMpegCore.Examples code finds ffprobe (and ffmpeg) but my basic Maui app cannot.  What could be the solution?

using FFMpegCore;
using FFMpegCore.Enums;

namespace FFmpegTest;

public partial class MainPage : ContentPage
{
	int count = 0;

	public MainPage()
	{
		InitializeComponent();
	}

	private void OnCounterClicked(object sender, EventArgs e)
	{
        var outputPath = "/Users/charlesyoung/Library/august 2.mp4";
        var outputPathJpg = "/Users/charlesyoung/Library/august 2.jpg";
        var outputPathPng = "/Users/charlesyoung/Library/august 2.png";
        var inputPathJpg = "/Users/charlesyoung/Library/DB2Image156.jpg";
        var inputPathMp3 = "/Users/charlesyoung/Library/DB2Audio156.mp3";
        var outPathMp4 = "/Users/charlesyoung/Library/DB2Image156.mp4";

        try {
            //FFOptions options = new FFOptions{ BinaryFolder = $"{filePath}"};
            string ffmpegexe = GlobalFFOptions.GetFFMpegBinaryPath(/*options*/);

            var mediaInfo = FFProbe.Analyse(inputPathJpg);
        } catch (Exception ex)
		{

		}

        count++;

		if (count == 1)
			CounterBtn.Text = $"Clicked {count} time";
		else
			CounterBtn.Text = $"Clicked {count} times";

		SemanticScreenReader.Announce(CounterBtn.Text);
	}
}

**Comment by cdavidyoung** [comment]
Ok, I finally realized that I was not setting the BinaryFolder correctly.  This works so that the ffmpeg and ffprobe are being found when I run my Maui app on my Mac.

         if (DeviceInfo.Current.Platform == DevicePlatform.MacCatalyst)
            GlobalFFOptions.Configure(new FFOptions { BinaryFolder = "/usr/local/bin", TemporaryFilesFolder = "/tmp" });

**Comment by rosenbjerg** [comment]
Good to hear you figured out the issue. If you feel the README doesn't make this clear enough, a PR clarifying it further would be welcome :)
