### ISSUE TITLE
Exception when running Examples on Mac

### ISSUE THREAD

**Issue by cdavidyoung** [rosenbjerg/FFMpegCore#380]
I installed ffmpeg on my mac according to the instructions using brew.  However, in my program, which runs fine on Windows, it can't seem to find ffmpeg when I use the FFMpeg class (e.g. FFMpeg.PosterWithAudio()).  So I thought I would try the examples.  It gets through the first few instructions (FFProbe.Analyse(inputPath) and FFMpegArguments to convert my mp4) but when it reaches the instruction FFMpeg.Snapshot it gives me this exception.  Has someone else tried running the Examples on a Mac?

"The path '/var/folders/lw/z89vj72j3rd6bngs45vz8jx40000gn/T/CoreFxPipe_FFMpegCore_5c335f78-6ec6-416d-8ccf-6ad8164f6ef4' is of an invalid length for use with domain sockets on this platform.  The length must be between 1 and 104 characters, inclusive. (Parameter 'path')\nActual value was /var/folders/lw/z89vj72j3rd6bngs45vz8jx40000gn/T/CoreFxPipe_FFMpegCore_5c335f78-6ec6-416d-8ccf-6ad8164f6ef4."

**Comment by cdavidyoung** [comment]
I see this seems to be related to https://github.com/rosenbjerg/FFMpegCore/issues/365

**Comment by cdavidyoung** [comment]
I am really just looking for verification that others are having trouble running the examples on a Mac.  I have been using this package with great success on Windows but with the same code on Mac I just get exceptions.  Any feedback would be appreciated to help me figure out whether this is an ffmpeg installation issue or what.

**Comment by ep1kt3t0s** [comment]
I made a fork and published below for this issue but I am concerned that the project is abandoned. It's might better to use ffmpeg directly on simple command calls.
https://www.nuget.org/packages/FFMpegCore-ep1kt3t0s

**Comment by cdavidyoung** [comment]
Thanks for this.  I had actually overcome most of my Mac problems by installing runtime.osx.10.10-x64.CoreCompat.System.Drawing.  However, I can't get FFMpeg.PosterWithAudio to work on Mac even though it works great on Windows.  I think it has to do with that I am targeting .Net 7 instead of 6.  In any case I tried your package and it does not solve this problem.

BTW, you mention using ffmpeg directly on simple command calls.  Do you mean something like this?  Or do you mean calling ffmpeg outside of FFMpegCore?  If you could tell me how to make ffmpeg calls directly I would appreciate it.  I have been trying to use WithCustomArgument to duplicate PosterWithAudio without success.

               FFMpegArguments
                  .FromFileInput(file)
                  .OutputToFile(jpgFile, false
                                ,options => options
                                .WithCustomArgument($"-vf scale='iw/2:ih/2'")
                               )
                  .ProcessSynchronously(true/*, options*/);

**Comment by cdavidyoung** [comment]
With regard to .Net 7 I recreated my little test program with .Net 6 and am still getting this exception on FFMpeg.PosterWithAudio.  Any help working around this would be appreciated!

{System.TypeInitializationException: The type initializer for 'Gdip' threw an exception.
 ---> System.DllNotFoundException: libgdiplus
   at System.Drawing.SafeNativeMethods.Gdip..cctor()
   --- End of inner exception stack trace ---
   at System.Drawing.Image.…}

using FFMpegCore;
using FFMpegCore.Enums;

namespace FFmpegTest_6;

public partial class MainPage : ContentPage
{
    int count = 0;

    public MainPage()
    {
        InitializeComponent();
    }

    private void OnCounterClicked(object sender, EventArgs e)
    {
        var outputPath = "/Users/charlesyoung/Library/august 2.mp4";
        var outputPathJpg = "/Users/charlesyoung/Library/august 2.jpg";
        var outputPathPng = "/Users/charlesyoung/Library/august 2.png";
        var inputPathJpg = "/Users/charlesyoung/Library/DB2Image156.jpg";
        var inputPathMp3 = "/Users/charlesyoung/Library/DB2Audio156.mp3";
        var outPathMp4 = "/Users/charlesyoung/Library/DB2Image156.mp4";

        try
        {
            GlobalFFOptions.Configure(new FFOptions { BinaryFolder = "/usr/local/bin", TemporaryFilesFolder = "/tmp" });
            //FFOptions options = new FFOptions{ BinaryFolder = $"{filePath}"};
            string ffmpegexe = GlobalFFOptions.GetFFMpegBinaryPath(/*options*/);

            FFMpeg.PosterWithAudio(inputPathJpg, inputPathMp3, outPathMp4);
        }
        catch (Exception ex)
        {

        }

        count++;

        if (count == 1)
            CounterBtn.Text = $"Clicked {count} time";
        else
            CounterBtn.Text = $"Clicked {count} times";

        SemanticScreenReader.Announce(CounterBtn.Text);
    }
}

**Comment by cdavidyoung** [comment]
I modified the FFMpegCore.Examples program to target .Net 7 and it works, including FFMpeg.PosterWithAudio.  So the question is why does this work but my test program not work?

{System.PlatformNotSupportedException: System.Drawing.Common is not supported on this platform.
   at System.Drawing.Image.FromFile(String filename)
   at FFMpegCore.FFMpeg.PosterWithAudio(String image, String audio, String output)
   at FFmpegTest.MainPage.OnC…}

Well, it seems to have something to do with this, but I don't know why it works with FFMpegCore.Examples but not with my .Net Maui test program:
https://learn.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only

So it occurred to me, why is FFMpegCore using System.Drawing.Common at all?  In perusing the code it appears to be only to use the Size class, which in turn is only used to store Height and Width.  So why not create a local Size class to do just this and not use System.Drawing.Common?  I will create a new issue to explore this.

**Comment by cdavidyoung** [comment]
See issue #381 for my resolution.

**Comment by rosenbjerg** [comment]
System.Drawing.Common will be gone in version 5
