### ISSUE TITLE
Remove System.Drawing.Common

### ISSUE THREAD

**Issue by cdavidyoung** [rosenbjerg/FFMpegCore#381]
I have been having so much trouble with this package that I am wondering why is FFMpegCore using System.Drawing.Common at all?  In perusing the code it appears to be only to use the Size class, which in turn is only used to store Height and Width.  So why not create a local Size class to do just this and not use System.Drawing.Common?

**Comment by cdavidyoung** [comment]
Well, it is not as easy as that.  I am current trying Aspose.Drawing as a replacement for System.Drawing.Common.  I need to rebuild the FFMpegCore package with that and add it locally to my project.  I'll report back.

**Comment by cdavidyoung** [comment]
It seems that Aspose.Drawing has solved my problem with FFMpeg.PosterWithAudio and System.Drawing.Common.  After branching FFMpegCore and cloning to my desktop, I rebuilt the FFMpegCore package (changing the package version to 4.8.1) with Aspose.Drawing after removing System.Drawing.Common and updated my app with the new FFMpegCore .  Here is the package manager output:

Successfully uninstalled 'FFMpegCore 4.8.0' from jiffyLog
Successfully uninstalled 'System.Drawing.Common 5.0.2' from jiffyLog
Successfully uninstalled 'Microsoft.NETCore.Platforms 5.0.0' from jiffyLog
Successfully uninstalled 'Microsoft.Win32.SystemEvents 5.0.0' from jiffyLog
Successfully installed 'Aspose.Drawing 22.12.0' to jiffyLog
Successfully installed 'FFMpegCore 4.8.1' to jiffyLog

My initial tests seem to indicate that FFMpegCore is now working as well on the Mac as it does on Windows!

**Comment by drasive** [comment]
Replacing System.Drawing.Common makes sense as [starting with .NET 7 it is windows-only](https://learn.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only) and will not allow execution on other platforms. Aspose.Drawing does not seems like a good replacement to me due to their [licensing](https://docs.aspose.com/drawing/net/licensing/) though.

**Comment by cdavidyoung** [comment]
This works for me but I agree it is not the optimal solution.  I hope someone figures that out.

**Comment by tiesont** [comment]
There's always something like ImageSharp, if you're after cross-platform support. That does introduce a hard dependency on a library that isn't FOSS in every scenario.

**Comment by rosenbjerg** [comment]
For now code depending on System.Drawing.Common will go into a separate package. I think it makes sense to do the same for image extensions using other libraries, even if cross-platform

**Comment by cdavidyoung** [comment]
So I see that Aspose.Drawing gets an error when I build it for Release.  I assume this is caused by the license that allows for debugging but does not allow the app to be published.  So is

https://github.com/rosenbjerg/FFMpegCore/pull/396

the next best hope of getting this issue resolved?  It looks like I can't publish for Mac until it is.

**Comment by drasive** [comment]
@cdavidyoung FYI, [#396](https://github.com/rosenbjerg/FFMpegCore/pull/396) was merged and an initial version of [FFMpegCore.Extensions.SkiaSharp](https://www.nuget.org/packages/FFMpegCore.Extensions.SkiaSharp) has been released to NuGet.

**Comment by cdavidyoung** [comment]
Thanks Dimitri!  I'll give it a try.  By the way will
Microsoft.Maui.Graphics accomplish the same thing?

**Comment by drasive** [comment]
I am not familiar with Microsoft.Maui.Graphics but I would assume so, yes.

**Comment by cdavidyoung** [comment]
Ok, I could use a little help updating my fork (https://github.com/cdavidyoung/FFMpegCore).  I don't understand, but when I forked from https://github.com/rosenbjerg/FFMpegCore in January I ended up with the last commit of Apr 15, 2022 Update Metadata.  From there I added my changes to support my app.  My intention was to eventually do a pull request to get them merged back to the main code.

So now I want to basically start over and fork https://github.com/rosenbjerg/FFMpegCore again but github won't let me because I already have one.  So I thought I could just delete my fork and start over, however I don't see how to delete my fork.  So I created a branch on my fork that is based on the Apr 15, 2022 commit.  I thought I would be able to sync that branch with rosenbjerg/FFMpegCore but I get all kinds of merge conflicts.

So could someone please give me the steps that I need to follow to accomplish what I am trying to do?  Thanks!

**Comment by rosenbjerg** [comment]
Please do not base your changes on an old commit. Git history has been rewritten since to remove some large files in git history. Please follow these steps for deleting your forked repository:
https://docs.github.com/en/repositories/creating-and-managing-repositories/deleting-a-repository

**Comment by cdavidyoung** [comment]
I have merged my changes to the latest commit and did a pull request but it is failing the automatic tests.  I fixed some of the Lint errors but I am not sure what to do beyond that.

BTW this has been a great experience and I greatly appreciate all the expert help!

**Comment by tiesont** [comment]
@cdavidyoung You can delete your repo by choosing the Settings tab on Github (in your repo), then scroll all the way down. Deleting a repo is in the Danger Zone section

**Comment by cdavidyoung** [comment]
Thanks, Tieson.  That is exactly what I did and after cloning the current version I was able to add my changes, test them on Windows and Mac, and do the pull request.  I am currently waiting to find out if there is anything else I can do to get rid of the errors in the automatic tests.

**Comment by rosenbjerg** [comment]
@cdavidyoung I will recommend using [`dotnet format`](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-format) for fixing the linting errors. It should be able to fix most if not all automatically

**Comment by cdavidyoung** [comment]
So I would like to finish the work on this and get the PR accepted.  @rosenbjerg, I know that you would prefer that PosterWithAudio throw an exception if the audio parameter is null, so what about a new method PosterWithoutAudio that passes the duration argument?  In both cases I need the rotateX90 argument.

Also, I think the RotateArgument is so much easier to use and intuitive than TransposeArgument.  How about I integrate RotateArgument with IVideoFilterArgument in the same way TransposeArgument is?

**Comment by rosenbjerg** [comment]
@cdavidyoung As I have already mentionend, transposition is already support and we will not be adding a second argument for the exact same ffmpeg functionality.
Your suggested change to `VerifyFFMpegExists` does not have any tests that demonstrates that it actually corrects some behaviour.
The `PosterWithAudio` should not behave differently when poster path is not provided. Methods should do what their name hints, not behave completely different when some parameter is null. If you need that functionality, you can do the exact same thing as PosterWithAudio but with whatever modifications you might need for your project:

```csharp
FFMpegArguments
    .FromFileInput(image, false, options => options
        .Loop(1)
        .ForceFormat("image2"))
    .AddFileInput(audio)
    .OutputToFile(output, true, options => options
        .ForcePixelFormat("yuv420p")
        .WithVideoCodec(VideoCodec.LibX264)
        .WithConstantRateFactor(21)
        .WithAudioBitrate(AudioQuality.Normal)
        .UsingShortest())
    .ProcessSynchronously()
```

**Comment by cdavidyoung** [comment]
I would ask you to please reconsider.  I have tried to address your issues.

   - I restored PosterWithAudio to its original behavior while adding the
   very useful rotate parameter.
   - I created a new PosterWithoutAudio method that allows one to easily
   create a poster when no audio is available by specifying a duration.
   - I integrated RotateArgument with IVideoFilterArgument.

I would respectfully disagree that Rotate is not the same as Transpose.
Rotate requires the application of up to 3 "transpose=1" filters.  My
implementation makes it easy and intuitive.

I found it necessary to adapt VerifyFFMpegExists to make it behave the same
way on Windows and Mac.

If you still don't want my changes that are essential for my app I'll just
continue to use my version of the nuget and sync with yours.  It is a great
body of work and I anticipate using it extensively.  Thanks.
