### ISSUE TITLE
Detecting HDR video

### ISSUE THREAD

**Issue by streamzyuk** [rosenbjerg/FFMpegCore#393]
I am trying to detect if a video is hdr.
ffprobe gives you a properties :
color_space=bt709
color_transfer=bt709
color_primaries=bt709

But the wrapper does not have these properties or I can't find them

**Comment by rosenbjerg** [comment]
Hi, those properties are currently not supported

**Comment by streamzyuk** [comment]
Thank you for your response. I have seen that at some point you have merged it but current code does not include it.

I have added this to the spurce code and it works for now.

Did you have any issues with this.

**Comment by JoeSchulte** [comment]
I am looking for the HDR color space info as well. I'm afraid I might have to go back to parsing the FFProbe data myself without it.

**Comment by rosenbjerg** [comment]
Added in #498
