### ISSUE TITLE
JoinImageSequence ffmpeg cannot find files after creating the temp folder and image inside

### ISSUE THREAD

**Issue by yuqian5** [rosenbjerg/FFMpegCore#394]
### Platform 
MacOS 13.2, M1

### To reproduce 
FFMpeg.JoinImageSequence($"{Environment.GetFolderPath(Environment.SpecialFolder.Desktop)}/test.mp4", frameRate: 1, files.ToArray());

### Error
[image2 @ 0x7fc46a004080] Could find no file with path '/var/folders/2v/j64hr8853fgg4pxt410228480000gn/T/2b7af209-3019-4cc7-ab07-86ed5eac5f78/%09d.png' and index in the range 0-4
/var/folders/2v/j64hr8853fgg4pxt410228480000gn/T/2b7af209-3019-4cc7-ab07-86ed5eac5f78/%09d.png: No such file or directory)

**Comment by yuqian5** [comment]
Upon further investigation, this issue is also present on windows 10

**Comment by rosenbjerg** [comment]
What is different in your case than in this test?

https://github.com/rosenbjerg/FFMpegCore/blob/e32dd3a7f720fad33ee8645565c37112701f4206/FFMpegCore.Test/VideoTest.cs#L450-L472

Could you create a similar unit test using the existing images, that will fail due to this issue?

**Comment by yuqian5** [comment]
Will investigate and update soon

**Comment by kswanner** [comment]
I'm having the same issue. I tried both ffmpeg v4.2.1 and v4.4.1, and both had the same error. I also tried the sample in the **samples** folder and your sample code above. It gave the same error using v4.2.1.

The files are read and copied to a temp folder correctly.

I also tried running ffmpeg from the command prompt. It works fine.

**Comment by rosenbjerg** [comment]
It seems only png were handled, so my guess is that your problem is that your files are not png.
#397 should fix this

**Comment by rosenbjerg** [comment]
Version 5.0.1 of this library contains a fix for this specifically, so please try with that version

**Comment by yuqian5** [comment]
Works now. Amazing! Thanks!
