### ISSUE TITLE
No way to run RawVideoPipeSource ahead of RawAudioPipeSource

### ISSUE THREAD

**Issue by i-e-b** [rosenbjerg/FFMpegCore#395]
Hi. 

Thanks for this project, it's really great.
I've found an odd issue that breaks my very specific use case.

My use case is generating a set of video frames, each of which results in a tone to play over that frame.
The tone is complex, and is based on the frame data.
I was hoping to queue tones after generating the frames, then feed that out of my audio source.

## Description

Tested on Windows, `ffmpeg version 5.1.2-essentials_build-www.gyan.dev`

When given a pair of pipe inputs to encode, one for audio and one for video, it seems to pull exactly 2 video frames, then will read all audio frames.

- If audio generation lags behind video generation, the video generation will stall until all audio is completed
- If audio generation waits for video frames to be written, the process will hang indefinitely.

## Self contained demonstration of the issue

```
IEnumerable<IVideoFrame> OneSecondOfVideoFrames()
{
    var frameImage = new Bitmap(320, 240, PixelFormat.Format24bppRgb);

    for (int i = 0; i < 60; i++)
    {
        Console.Write('v');
        Thread.Sleep(10); 
        yield return new BitmapVideoFrameWrapper(frameImage);
    }
    frameImage.Dispose();
}

IEnumerable<IAudioSample> OneSecondOfAudioFrames()
{
    var toneSamples = 44100 / 440;
    var buffer = new byte[toneSamples];
    
    for (int i = 0; i < 440; i++)
    {
        Console.Write('a');
        Thread.Sleep(10); 
        yield return new PcmAudioSampleWrapper(buffer);
    }
}

public void WriteVideo()
{
    var videoFramesSource = new RawVideoPipeSource(OneSecondOfVideoFrames()) { FrameRate = 60 };
    var audioSource = new RawAudioPipeSource(OneSecondOfAudioFrames()) { Channels = 1, SampleRate = 44100, Format = "u8" };

    FFMpegArguments
        .FromPipeInput(videoFramesSource)
        .AddPipeInput(audioSource)
        .OutputToFile("test.mp4", overwrite: true, options => options
            .WithVideoCodec(VideoCodec.LibX264)
            .WithAudioCodec(AudioCodec.Aac)
        )
        .ProcessSynchronously();
}
```

Expected output -- something like this:
```
vaaaaavaaaaaavaaaaaavaaaaavaaaaaavaaaaavaaaaaaaavaaaaavaaaaavaaaaavaaaaaaaaavaaaaavaaaavaaaaaavaaaaaaaavaaaaaaaaavaaaaaaaaaaaavaaaaaaavaaaaaaaavaaaaaaaaaaavaaaaaaaaaaaavaaaaaaaaavaaaaaaavaaaaaavaaaaaaavaaaaaaavaaaaaaaavaaaaaaaaaavaaaaaaaaaaaaaavaaaaavaaaaaaavaaaaavaaaaavaaaaaavaaaaaaavaaaaaaavaaaaavaaaaavaaaavaaaaaavaaaaaaavaaaaaaaaaavaaaaaaaaavaaaaaavaaaaaaaaavaaaaaaavaaaaaaaaaavaaaaaaaavaaaaavaaaaaaaaaavaaaaaaaavaaaaaaaaavaaaaaavaaaaaaaavaaaaaaavaaaaaaavaaaaaaaaavaaaaaaavaaaaaaaaaavaaaavaaaaaav
```

Actual output
```
vvaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaavvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
```

## Notes

From what I can see, the video generator and audio generator `IEnumerable` are running on different threads.

If `ProcessSynchronously` is changed to `ProcessAsynchronously`, this problem persists

If the feed order is changed to `.FromPipeInput(audioSource).AddPipeInput(videoFramesSource)...`, then only 1 video frame is read before all audio frames are read.

I have tried all the threading options on `OutputToFile`, and they don't have any effect on this issue.

Changing `Thread.Sleep` to `Task.Delay` makes no difference.

From what I can see, this might be an issue with the call `this._ffMpegArguments.During(...)` in `FFMpegCore.FFMpegArgumentProcessor.Process`.

I will investigate further if I have time.

**Comment by i-e-b** [comment]
I've investigated this issue, and it looks like a fault in C# or Windows.  `NamedPipeServerStream` with the `PipeOptions.Asynchronous` option set are still synchronous on writes -- any attempt to write to them out of sync with the consumer will block. There doesn't seem to be any work-around available while still using pipes.

I may investigate using a local TCP/IP server as the source.

**Comment by rosenbjerg** [comment]
Hey @i-e-b, 
I was aware that there were some limitations with `NamedPipeServerStream`, but I didn't know about this one. 
I know some people have mentioned looking into a workaround similar to what you mentioned, but I haven't been able to find an issue thread mentioning it. I do however think it is a viable route, although maybe not the easiest.
Thank you for posting your findings here
