### ISSUE TITLE
Ffmpeg one seconds have freeze when use overlay

### ISSUE THREAD

**Issue by adelhoss** [rosenbjerg/FFMpegCore#40]
I Use Ffmpeg For Overlay Png on short video : For Example 5 seconds video I Use This Command :
`-i C:\\part1.mp4 -i C:\\txt1.png -filter_complex \"overlay=(main_w-overlay_w)/2:(main_h-overlay_h)/2\" -c:v libx264  -pix_fmt yuv420p -codec:a copy C:\\outputtext1.mp4
`
one seconds freeze in playing ...
please help me
please download and see my output video :
[Output Above Command](https://www.mediafire.com/file/befhqnebki9owti/outputtext2.mp4/file)

**Comment by rosenbjerg** [comment]
Please refer all ffmpeg questions to the ffmpeg bug tracker.
This library is a C# wrapper for ffmpeg
