### ISSUE TITLE
Join Method is Problem : Repeat last frame from first input

### ISSUE THREAD

**Issue by adelhoss** [rosenbjerg/FFMpegCore#41]
hello
i use your powerful library
but join method have proble two mp4 :
some last frame from first input have repat after join
i use this code :
`  FFMpeg encoder = new FFMpeg();
            VideoInfo vf=encoder.Join(
                new FileInfo(@"C:\joined_video.mp4"),
                VideoInfo.FromPath(@"C:\part2.mp4"),
                VideoInfo.FromPath(@"C:\part2after.mp4")
            )`
please down load and see my joined video from this link :
[my joined video](https://www.mediafire.com/file/fjvr86ub9wvdmxc/joined_video.mp4/file)

**Comment by rosenbjerg** [comment]
That sounds like a problem with `ffmpeg` itself
This library builds up the `concat` argument for ffmpeg correctly, so the rest is up to ffmpeg.
Please report the bug you found to the ffmpeg bug tracker
