### ISSUE TITLE
processing individual video frames of a video

### ISSUE THREAD

**Issue by vpenades** [rosenbjerg/FFMpegCore#411]
Hi

I am having a hard time figuring out the sequence of commands needed to process the frame bitmaps of a video.

In short, I would like a method like this:

```c#

FFMpeg.ProcessFrames("source.mp4", "destination.mp4",  _singleFrameProcessor);

void _singleFrameProcessor(int frameIndex, TimeSpan frameTime, int width, int height, int stride, string pixelFormat, Byte[] pixels)
{
// filter the image, draw some text over the image, whatever.
}

```

As a bonus, it should preserve the original audio, framerate, etc.

**Comment by rosenbjerg** [comment]
PRs are welcome, but I think FFMpeg.AutoGen is more fitting for such functionality
