### ISSUE TITLE
How do I run a command that doesn't require an outputfile?

### ISSUE THREAD

**Issue by fredyfx** [rosenbjerg/FFMpegCore#414]
Hello! I would like to run this command:

`ffmpeg -i "Random Test.mp3" -af silencedetect=n=-50dB:d=1 -f null -`

And read the result for saving it on a text file.
I've reading the library and by watching the unit testing, I realize that it is mandatory to have an output file, Am I understanding it wrong?

Any help is much appreciate it.

Thanks and continue having a good day!

Fredy.

**Comment by rosenbjerg** [comment]
Hey @fredyfx 
You could consider outputting to a memorystream, seek to the beginning, and then getting the string representation of the bytes
