### ISSUE TITLE
FFMpegHelper.VerifyFFMpegExists(new FFOptions()) not working on Mac

### ISSUE THREAD

**Issue by cdavidyoung** [rosenbjerg/FFMpegCore#418]
The default is supposed to be that ffmpeg can be found via PATH.  This works on Windows but on MacOS it keeps giving me the file not found: ffmpeg exception.  As shown below, a terminal window shows that ffmpeg it is in the PATH.

I have created a little project to demonstrate this.  Could someone try this out on a Mac?
https://github.com/cdavidyoung/MauiApp-FFMpegCore-test.git

sh-3.2# ffmpeg -version
ffmpeg version 5.1.2 Copyright (c) 2000-2022 the FFmpeg developers
built with Apple clang version 14.0.0 (clang-1400.0.29.202)
configuration: --prefix=/opt/homebrew/Cellar/ffmpeg/5.1.2_5 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libaribb24 --enable-libbluray --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librist --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libsvtav1 --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-videotoolbox --enable-neon
libavutil      57. 28.100 / 57. 28.100
libavcodec     59. 37.100 / 59. 37.100
libavformat    59. 27.100 / 59. 27.100
libavdevice    59.  7.100 / 59.  7.100
libavfilter     8. 44.100 /  8. 44.100
libswscale      6.  7.100 /  6.  7.100
libswresample   4.  7.100 /  4.  7.100
libpostproc    56.  6.100 / 56.  6.100
sh-3.2#

**Comment by rosenbjerg** [comment]
The test suite is getting run on both macOS, linux and windows, so it should be possible to reproduce the same issue in a unit test. `FFMpegHelper.VerifyFFMpegExists` is used in `PrepareProcessArguments` which is used in several tests which run sucessfully on the macOS CI agents. If you could reproduce your issue in a unit test, it will be much easier to fix

**Comment by cdavidyoung** [comment]
The issue is that this may not reproduce the problem.  I added this call to
FFMpegCore.Examples\Program.cs and it works fine on MacOS.  However, when I
added the call to my app that just uses the FFMpegCore nuget it does not
work on MacOS (but works fine on Windows).  That is why I created the
standard Maui app to reproduce the problem.  It behaves the same as my app.

**Comment by cdavidyoung** [comment]
I could still use some help evaluating this.  I have updated the test code by pulling out the VerifyFFMpegExists method to the main program so that it can be more easily debugged.  I am also printing out the InnerException to get more detail on the exception.  Could someone with a Mac and has ffmpeg installed please clone and run this solution?  Thanks.

https://github.com/cdavidyoung/MauiApp-FFMpegCore-test

To reiterate, VerifyFFMpegExists works fine on Windows and it used to work on my Mac as well.  Something happened that caused it to no longer work in my app so I created this standard Maui test app where it also does not work on my Mac.  However, if I add the call to FFMpegCore.Examples\Program.cs and run the sample FFMpegCore app it successfully detects ffmpeg!  How can this be explained?

**Comment by cdavidyoung** [comment]
Here is the exception:

"An error occurred trying to start process 'ffmpeg' with working directory '/Volumes/Mac only extern/MauiApp-FFMpegCore-test/MauiApp FFMpegCore test/bin/Debug/net7.0-maccatalyst/maccatalyst-x64/MauiApp FFMpegCore test.app'. No such file or directory"

**Comment by cdavidyoung** [comment]
I could still use some help evaluating this.  I have updated the test code by pulling out the VerifyFFMpegExists method to the main program so that it can be more easily debugged.  On Windows it is fine to use the default FFOptions() but on the Mac the BinaryFolder must be set explicitely.  Since I use homebrew to install ffmpeg the folder is  "/opt/homebrew/bin".

 VerifyFFMpegExists(new FFOptions { BinaryFolder = "/opt/homebrew/bin", TemporaryFilesFolder = "/tmp" });

Here is the test project: https://github.com/cdavidyoung/MauiApp-FFMpegCore-test

To reiterate, VerifyFFMpegExists works fine on Windows and it used to work on my Mac as well.  Something happened that caused it to no longer work in my app so I created this standard Maui test app and it does indeed work.  I also added the call to FFMpegCore.Examples\Program.cs and ran the sample FFMpegCore app and it also successfully detects ffmpeg!

Can anyone give me an idea of why VerifyFFMpegExists works on Windows and on Mac works with the test project as well as the sample FFMpegCore app but does not work in my app using the same code?  Any help would be greatly appreciated.

**Comment by cdavidyoung** [comment]
I could still use some help evaluating this.  I have updated the test code by pulling out the VerifyFFMpegExists method to the main program so that it can be more easily debugged.  On Windows it is fine to use the default FFOptions() but on the Mac the BinaryFolder must be set explicitely.  Since I use homebrew to install ffmpeg the folder is  "/opt/homebrew/bin".

 VerifyFFMpegExists(new FFOptions { BinaryFolder = "/opt/homebrew/bin", TemporaryFilesFolder = "/tmp" });

Here is the test project: https://github.com/cdavidyoung/MauiApp-FFMpegCore-test

To reiterate, VerifyFFMpegExists works fine on Windows and it used to work on my Mac as well.  Something happened that caused it to no longer work in my app so I created this standard Maui test app and it does indeed work.  I also added the call to FFMpegCore.Examples\Program.cs and ran the sample FFMpegCore app and it also successfully detects ffmpeg!

Can anyone give me an idea of why VerifyFFMpegExists works on Windows and on Mac works with the test project as well as the sample FFMpegCore app but does not work in my app using the same code?  Any help would be greatly appreciated.

**Comment by cdavidyoung** [comment]
I managed to get VerifyFFMpegExists to work by starting over with a fresh Maui project with the same name as my app's project.  Then I methodically merged the files from my old project to the new.  After a couple of hours I was able to run my new project on the Mac and my app behaved normally.  This includes VerifyFFMpegExists.  So something about creating the fresh project made it work.
