### ISSUE TITLE
Support to overlays

### ISSUE THREAD

**Issue by fmanso** [rosenbjerg/FFMpegCore#422]
I tried to build a mosaic video like the one in the following URL:
http://trac.ffmpeg.org/wiki/Create%20a%20mosaic%20out%20of%20several%20input%20videos

But I couldn't find the way to use overlays. It would be great feature.

Thanks for your effort.

**Comment by rosenbjerg** [comment]
You could do something like in [`GifPaletteArgument`](https://github.com/rosenbjerg/FFMpegCore/blob/943662aa15e8cf73dce0b1a8b93ffe8e8bae274b/FFMpegCore/FFMpeg/Arguments/GifPaletteArgument.cs)

https://github.com/rosenbjerg/FFMpegCore/blob/943662aa15e8cf73dce0b1a8b93ffe8e8bae274b/FFMpegCore/FFMpeg/Arguments/GifPaletteArgument.cs#L22

But I don't see a good way to support building the filter_complex value more fluently
