### ISSUE TITLE
RTSP url to MP4

### ISSUE THREAD

**Issue by MortenTobiasNielsen** [rosenbjerg/FFMpegCore#424]
Hi, 

I have a project where I need to take in an RTSP stream and convert it to MP4. I currently have this code: 
```csharp
FFMpegArguments
            .FromUrlInput(new Uri("rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mp4"))
            .OutputToFile("output.mp4")
            .ProcessSynchronously(); 
```

The problem is that I get this error: 
![image](https://user-images.githubusercontent.com/48355480/225599907-765510ed-8019-482e-8be6-99b66b12f09a.png)

I have tried to use ForcePixelFormat and ForceFormat, but I cannot figure out how I am supposed to use them - at the very least what I am doing isn't working. I have tried figuring out how I am supposed to _increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options_, but I cannot find an example of that. 

I hope you can help me out with a working example using _rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mp4_

This works in the CLI:
ffmpeg -rtsp_transport tcp -i rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mp4 -acodec copy -vcodec  copy -preset ultrafast -t 20  output.mp4

**Comment by rosenbjerg** [comment]
Hi @MortenTobiasNielsen,
We currently don't have anything adding the `-rtsp_transport tcp` part, which is probably the issue you are facing

**Comment by MortenTobiasNielsen** [comment]
@rosenbjerg Do I need to be aware of a specific pattern which should be used, if I were to make a PR for adding the `-rtsp_transport tcp` part

**Comment by MortenTobiasNielsen** [comment]
Seems like it can be solved with the WithCustomArgument method.

``` csharp
FFMpegArguments
            .FromUrlInput(new Uri("rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mp4"), options =>
                options
                    .WithCustomArgument("-rtsp_transport tcp")
                    .WithCustomArgument("-ss 15"))
            .OutputToFile("output.mp4", true, options => 
                options
                    .WithCustomArgument("-acodec copy")
                    .WithCustomArgument("-vcodec copy")
                    .WithCustomArgument("-t 20")
                    .WithFastStart())
            .ProcessSynchronously();
```

If someone comes to this issue with the same problem. This will remove the first 15s and make a 20s clip. Remember to change the "output.mp4" if you don't want the clip to just be placed in the folder of the executable.
