### ISSUE TITLE
Rotate, Scale and Crop - with ChatGPT!

### ISSUE THREAD

**Issue by sp00ky** [rosenbjerg/FFMpegCore#427]
This is less an issue than it is a question.

Please don't laugh!  I have an actual (hobby) use case that I was looking for input on, so I went where everyone else is going these days - ChatGPT.  I asked the following:

"show me a class that uses ffmpegcore to concatenate multiple 4k video files, rotate the resulting video by 4 degrees, crop to 1920x1080 at the pixel 0x100, then rescale the video to 4k"

This is the response I got.  I'm kinda wondering if ChatGPT was hallucinating.  After installing the FFMpegCore NuGet package as well as FFMpegCore.Extensions.SkiaSharp and FFMpegCore.Extensions.System.Drawing.Common, VS has no idea where half of these classes come from.  Nor can I find them in this repo.  I'm not even sure the FFMpegCore.Filters.Video namespace exists.

Or...maybe ChatGPT is right and I'm just missing something really important.  

`
using System.Collections.Generic;
using FFMpegCore;
using FFMpegCore.Arguments;
using FFMpegCore.Enums;
using FFMpegCore.Filters.Video;
using FFMpegCore.Pipes;

public class VideoConcatenator
{
    public async Task ConcatenateVideosAsync(List<string> inputPaths, string outputPath)
    {
        // Set the video concatenation options
        var concatenationOptions = new ConcatenateOptions { VideoCodec = VideoCodec.H264 };

        // Concatenate the input videos into a single video stream asynchronously
        var videoStream = await FFMpegArguments.FromConcatenateInputs(concatenationOptions, inputPaths.ToArray())
            .OutputToFile(new NullOutputPipe(), true)
            .ProcessAsynchronously();

        // Set the rotation and crop options for the video filter
        var videoFilter = FilterChain
            .New()
            .AddFilter(new VideoRotationFilter(4))
            .AddFilter(new VideoCropFilter(1920, 1080, 100, 100))
            .AddFilter(new VideoScaleFilter(4096, 2160, VideoSizeUnit.Landscape));

        // Set the conversion options for the video filter
        var conversionOptions = new ConversionOptions { VideoFilter = videoFilter };

        // Convert the video asynchronously using FFMpegCore
        await FFMpegArguments
            .FromPipeInput(videoStream)
            .OutputToFile(outputPath, false, options => options
                .WithVideoCodec(VideoCodec.Libx264)
                .WithConstantRateFactor(22)
                .WithAudioCodec(AudioCodec.Aac)
                .WithBitrate(6000)
                .WithCustomArgument("-preset", "ultrafast")
                .ForceFormat("mp4"))
            .WithConversionOptions(conversionOptions)
            .ProcessAsynchronously();
    }
}
`

**Comment by rosenbjerg** [comment]
Seems like it is hallucinating those class names
