### ISSUE TITLE
OutputToPipe doesn't include cover art while OutputToFile does

### ISSUE THREAD

**Issue by goffincedric** [rosenbjerg/FFMpegCore#429]
I noticed that when outputting to a stream, cover art doesn't get included in the outputted file.
To reproduce:
```
var transcodeBuilder = FFMpegArguments.FromFileInput("audio.mp3");
transcodeBuilder = transcodeBuilder.AddFileInput("download.png");

await using var fileStream = File.OpenWrite("output.mp3");
var v = transcodeBuilder
    .OutputToPipe(new StreamPipeSink(fileStream),
        options =>
        {
            options
                .WithCustomArgument("-c copy -map 0 -map 1")
                .ForceFormat("mp3");
        }
    );
    
await v.ProcessAsynchronously();
```

The following code does include the cover art in the output file
```
var transcodeBuilder = FFMpegArguments.FromFileInput("audio.mp3");
transcodeBuilder = transcodeBuilder.AddFileInput("download.png");
var v = transcodeBuilder
    .OutputToFile("output.mp3", true,
        options =>
        {
            options
                .WithCustomArgument("-c copy -map 0 -map 1")
                .ForceFormat("mp3");
        }
    );
    
await v.ProcessAsynchronously();
```

In my use case, I have a web api, which can't use the local filesystem to write a temporary file. It should respond to requests with streams.

Is this a limitation of the .OutputToPipe method or a bug?

**Comment by vadymsushkovdev** [comment]
Same problem. The problem is that mp3 or mp4 (in my case) are file containers that cannot be used as streams. I may have found a little crutch, which is to use the stream format to save it to a file. You'll find it easier with mp3, as I think I've seen such a stream in "ffmpeg -formats", but mine is more complicated. The file is saved, runs, but I get the audio with a grey screen.  And yes, I'm using Process to directly set parameters in ffmpeg, as FFMpegCore doesn't have such a solution yet. Here's an example you can start working with: 
   private async Task<MemoryStream> ProcessVideoAsync(string inputTempUri)
    {
        Console.WriteLine(inputTempUri);
        var outputTempStream = new MemoryStream();
        
        var ffmpegArgs = $"-nostdin -i \"{inputTempUri}\" " +
                         $"-map 0 " +
                         $"-vf \"scale=w={
                             _videoMaxWidth
                         }:h={
                             _videoMaxHeight
                         }:force_original_aspect_ratio=decrease,pad={
                             _videoMaxWidth
                         }:{
                             _videoMaxHeight
                         }:(ow-iw)/2:(oh-ih)/2:color=0x000000\" " +
                         $"-c:v libx264 -preset ultrafast -b:v {_bitrateVideoVariable}k " +
                         $"-c:a aac " +
                         $"-force_key_frames \"expr:gte(t,n_forced*{_standardVideoFramerate})\" " +
                         $"-f matroska - ";



        using var process = new Process();
        process.StartInfo.FileName = "ffmpeg";
        process.StartInfo.Arguments = ffmpegArgs;
        process.StartInfo.UseShellExecute = false;
        process.StartInfo.RedirectStandardInput = true;
        process.StartInfo.RedirectStandardOutput = true;
        process.EnableRaisingEvents = true;
        process.Exited += (sender, args) =>
        {
            outputTempStream.Seek(0, SeekOrigin.Begin);
            Console.WriteLine("outputTempStream2 " + outputTempStream.Length);
        };

        process.Start();

        await using var baseStream = process.StandardOutput.BaseStream;

        await Task.WhenAny(process.WaitForExitAsync(), outputTempStream.FlushAsync());

        await baseStream.CopyToAsync(outputTempStream);

        process.StandardInput.BaseStream.Close();

        return outputTempStream;
    }

**Comment by rosenbjerg** [comment]
Thank you @vadymsushkovdev for the explanation and example

**Comment by rosenbjerg** [comment]
btw @vadymsushkovdev that ffmpeg command should be supported in FFMpegCore, though with the help of WithCustomArgument
