### ISSUE TITLE
Error in MJPEG output

### ISSUE THREAD

**Issue by andreadps** [rosenbjerg/FFMpegCore#43]
I am using the library to extract frames from a video file. So the output I am using is `frame%06d.jpg`.

However, the `RunProcess` method will always check for the existence of the output file, which doesn't exist in the way it expects. In the end, I always get the exception below.

```
if (!File.Exists(output.FullName) || new FileInfo(output.FullName).Length == 0)
    throw new FFMpegException(FFMpegExceptionType.Process, string.Join("\n", _instance.ErrorData));
```

**Comment by rosenbjerg** [comment]
Is the file getting created? Can you give a short example that replicates your problem?

**Comment by andreadps** [comment]
To be clear, FFMpegCore performs as expected until that check. The snippet below will generate a bunch of `.jpg` as desired and will cause the exception I reported at the end because there will be no file actually named `frame%06d.jpg`.

```
public void ExtractFrames(string videoPath, string framesDir)
{
    var output = Path.Combine(framesDir, "frame%06d.jpg");
    var args = new ArgumentContainer
    {
        new InputArgument(videoPath),
        new OutputArgument(output)
    };
    var ffmpeg = new FFMpeg();
}
```
The workaround below does the trick for me:
```
using (var sw = File.CreateText(output))
{
    sw.Write("content cant be zero");
}
var ffmpeg = new FFMpeg();
ffmpeg.Convert(args);
File.Delete(output);
```

**Comment by rosenbjerg** [comment]
I'm considering fixing this issue by making the existence check optional. Would something like `ffmpeg.Convert(args, skipOutputExistsCheck: true)` be a suitable solution?

**Comment by andreadps** [comment]
I think that, ideally, the library should skip this check by itself when the output argument is not a single/real file. But I would gratefully accept your solution above. =)

**Comment by rosenbjerg** [comment]
Yeah, that would be optimal.
But I don't really see why this library performs that check at all, as users can very easily perform that check if it is necessary for them. I'll make it optional, defaulting to perform the check to avoid breaking any expectations from users of this library. But in version 2, I'll probably cut that check entirely :)

I have updated the nuget package

**Comment by rosenbjerg** [comment]
I'll close this now that the nuget package is updated. Please reopen if this didn't solve your problem
