### ISSUE TITLE
FFMpegCore.Exceptions.FFMpegException: ffmpeg exited with non-zero exit-code

### ISSUE THREAD

**Issue by AnthonyGiretti** [rosenbjerg/FFMpegCore#439]
Hi 

I'm trying to transform a MOV file to a MP4 file, here my code:

![image](https://user-images.githubusercontent.com/21200167/235548463-33db9068-5068-47f8-8246-facd6820c85a.png)

Unfortunately, I get this error:

![image](https://user-images.githubusercontent.com/21200167/235548287-107fde65-428d-46f9-8674-fc1a93dec1bb.png)

Any Idea why ?

**Comment by AnthonyGiretti** [comment]
I added the following arguments without luck: 

.WithCustomArgument("-analyzeduration 100M -probesize 100M"))

I found more errors here:
![image](https://user-images.githubusercontent.com/21200167/235551906-4a1ad88a-97c7-4beb-86bb-df95459cccc2.png)

I'm sure that the input file is correct since I have been able to make it work with the Xabe.FFMpeg library. But I would like to use FFMpegCore because Streams.

**Comment by tqk2811** [comment]
Not your main problem (your input) but. Mux file format mp4 (your output) is compression type.   
Then you can't output it as stream write only, that mux format need seek on stream. And stdout stream don't allow it.

And in input, try input as file instead of stdin stream. If it work then stream is problem (same as above)

**Comment by rosenbjerg** [comment]
I see two problems here, one being what @tqk2811 mentioned; that the h264+mp4 transcoding you ask for requires that the output stream can seek, which isn't the case. Try with i.e. vp9+webm instead
Second problem is that you are not setting the position of your `audioOutputStream` to `0` before reading from it
