### ISSUE TITLE
_instance.BlockUntilFinished() never returns 

### ISSUE THREAD

**Issue by thespragg** [rosenbjerg/FFMpegCore#44]
Hi,

So it seems I can generate a PosterWithAudio fine (mp4 appears in folder) , but execution doesn't continue after that point as the BlockUntilFinished() line doesn't return

**Comment by rosenbjerg** [comment]
Hmm, interesting. Are you able to replicate it? We have unittests that verifies that it returns, but it might not cover your use-case. Can you give a short example that replicates your problem, so we can cover it properly in unit-tests?

**Comment by WeihanLi** [comment]
maybe the file had existed, if so, the process will prompt if overwrite the exist file, so it will not return.

![image](https://user-images.githubusercontent.com/7604648/80555244-4dea7480-8a02-11ea-94ee-554f3bbb10e1.png)

**Comment by rosenbjerg** [comment]
That seems quite likely, WeihanLi. We could tell ffmpeg to also overwrite, to avoid such problem in the future. Otherwise, we could check if output already exists before conversion and then throw exception
