### ISSUE TITLE
[Question] Load byte[] of m2t data and reading frame information

### ISSUE THREAD

**Issue by LiorBanai** [rosenbjerg/FFMpegCore#448]
## Context

I have Enciris lt 101 card which I read the frames in a loop and write it to m2t file.
Each frame is being read and just written to the file as is. VLC can play it since each frame is a key frame also.  

## Question

I was wondering if it possible in parallel of writing the byte array also to:
- [ ] pass each frame  to the library and also create m2t file (maybe in different encoding).
- [ ] Get frame statistics (ffprobe): pts value , resolution.. etc..

and if it is possible (one of them or both) some code example would be appreciated.
The example shows inputPath but I have the frame data

**Comment by rosenbjerg** [comment]
You may be able to use RawVideoPipeSource for passing each frame, but I don't think FFMpegCore supports anything for getting frame analysis data from the frame data
