### ISSUE TITLE
Audio cuts in final video 

### ISSUE THREAD

**Issue by REEDOOX** [rosenbjerg/FFMpegCore#45]
Hello guys, 

Thank you for making this library possible, I'm experiencing an issue with the Join method, I have some MP4 videos (10 videos) and I'm using the Join method to join them all into a single MP4 file, the MP4 file is good but the audio sometimes cut (matter of some milliseconds of silence between here and there).

It is worth noting that: 

1. The videos are not all shot with the same camera, so they have different properties
2. Not all the clips have the same problem in the final MP4 file.

Thanks in advance guys, If you want any output or logs feel free to ask, I have no Idea yet what should logs I post.

**EDIT**
Turns out this problem happens when two videos have a different audio sample rate, if I Join two videos with the same audio sample rate there are no cuts

**Comment by rosenbjerg** [comment]
In my opinion, the best way to solve this is to first convert the video clips that have a different sampling rate, so all video clips have the same audio sample rate. Then perform the join.
It would require a more complex concat argument, which is not yet supported by this library, for that to be done in one swoop.
Hope this helps you

**Comment by REEDOOX** [comment]
Hello,

I managed to clone the repo and edit the code of the library, I added the argument -ar 48000 in the AudioCodecArgument class when converting to the ts files. it works perfectly.

I think the problem is solved if you want you can close the issue for now, or I can add a pull request if this functionality can be interesting to you.

Thanks for your time.

**Comment by rosenbjerg** [comment]
Ah perfect. I'll make sample rate configurable for AudioCodecArgument

**Comment by rosenbjerg** [comment]
I decided to add it as a separate argument, called AudioSamplingRateArgument
I have just updated the nuget package, so I'll close this issue :)
