### ISSUE TITLE
How to write video from in memory images using less ram?

### ISSUE THREAD

**Issue by Juff-Ma** [rosenbjerg/FFMpegCore#454]
While there is the RawVideo pipe that can use unencoded images there isn't one that would use less ram. In my usecase i would have to write a video file thats 1 hour long (propably longer). 

I don't think it would work as it would propably be more than 100gb per hour of footage. Is there a better way to do this? The Frames are being generated live with 25-60fps and i have them in jpeg format.

**Comment by rosenbjerg** [comment]
You can give FromDemuxConcatInput a try, but other than that I don't have any suggestions
