### ISSUE TITLE
Decouple ffprobe call from result parsing

### ISSUE THREAD

**Issue by pavel-zybenkov** [rosenbjerg/FFMpegCore#459]
Hello, 
in our project ([StaticSharp](https://github.com/StaticSharp/StaticSharp)) we came across a necessity to cache video metadata in a file so that we could reuse it later or compare with updated data and detect changes in a video. It looks like for this purpose we need to get metadata e.g. with `FFProbe.Analyse()` and then serialize it and save to file. 

But in fact, this data had just been deserialized. So it would be great if there was some extension point giving a chance to decouple obtaining a raw ffprobe result from parsing it. 
Also, if raw output is cached, then the cache would remain valid even if `FFProbe.Analyse()` methods result type `MediaAnalysis` changed.

By the way, under the hood such segregation already exists, there is `FFProbe.ParseOutput()` method which is called in the last line of each `FFProbe.Analyse()`/`FFProbe.AnalyseAsync()` overload, but `FFProbe.ParseOutput()` is private. So basically to cover this caching case there would be enough just to make `FFProbe.ParseOutput()` public, and introduce some `FFProbe.AnalyseWithoutParsing()` public method - same as `Analyse` but without `ParseOutput` call.

Would it be possible to do something like this, please?

**Comment by rosenbjerg** [comment]
Thanks for the suggestion, but it sounds like too much of a corner-case to add more code to handle. It sounds like you have a JSON serializer at hand, so it doesn't sound like an issue
