### ISSUE TITLE
Allow usage of docker image for ffmpeg, ffprobe, etc.

### ISSUE THREAD

**Issue by JamieJamesJamie** [rosenbjerg/FFMpegCore#460]
I am using `ffmpeg` and `ffprobe` for a project that runs both on a Windows and Linux machine. However, it's hard to get consistent behaviour between the 2 OSs. As the packaging systems differ for each OS, it's difficult to keep track of 2 different version numbers and keep them consistent.

So, I would like to suggest a feature to be able to optionally use a docker image (e.g. https://hub.docker.com/r/linuxserver/ffmpeg ) under the hood within FFMpegCore. Using this either through docker or docker desktop on Linux or Windows would allow consistent behaviour between the 2 OSs.

**Comment by jakoss** [comment]
I just created a asp docker image and run this:
```
FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app

RUN apt-get update && apt-get install -y curl ffmpeg libgdiplus
``` 

works great. No need for any actions from the library side
