### ISSUE TITLE
How to run vidstabdetect

### ISSUE THREAD

**Issue by slemvs** [rosenbjerg/FFMpegCore#469]
Hi, thanks for good library!
Could you please help with vidstabdetect:
Need ti run this command
`ffmpeg -hwaccel cuda -y -i 'source' -vf vidstabdetect=stepsize="6":shakiness="10":accuracy="15":mincontrast="0.4" -f null -`

Main command is content for `.WithCustomArgument(...)` and the problem is how to set last `-f null -`?

**Comment by rosenbjerg** [comment]
Include '-f null' in WithCustomArgument and use OutputToFile("-", ..)
