### ISSUE TITLE
stream/byte array support

### ISSUE THREAD

**Issue by WeihanLi** [rosenbjerg/FFMpegCore#47]
could we get video info from stream/bytes  or output result into stream/ bytes?

**Comment by max619** [comment]
#46 
Hi!
First part of your request i have already implemented in my pull request. And i'm planning to add support of output piping

**Comment by WeihanLi** [comment]
sounds great 👍

**Comment by amunim** [comment]
Nice, having Bitmaps/Byte array as input and  byte array as output would definitely be helpful.

**Comment by rosenbjerg** [comment]
I have just merged the PRs, ensured the unit tests passed, and updated the nuget package :)

**Comment by amunim** [comment]
I've managed to save the bitmap to stream and used `VideoInfo.FromStream(ms)` to get the input file for the encoder but `encoder.Convert()` does not contain an out param of `byte[]` nor a `Stream`.
