### ISSUE TITLE
WithVideoBitrate error

### ISSUE THREAD

**Issue by Enakers** [rosenbjerg/FFMpegCore#472]
I am unable to figure out this problem as I don't see a way to output the command that is generated.

```c#
 await FFMpegArguments.FromFileInput(Path.Combine(Directory.GetCurrentDirectory(), "../video.mkv"), true, opts =>
{
    opts.WithHardwareAcceleration(HardwareAccelerationDevice.QSV);
}).OutputToFile(Path.Combine(Directory.GetCurrentDirectory(), "../out.mp4"), true, args =>
 {
     args.WithVideoCodec("h264_qsv")
     .WithVideoBitrate(2048)
     .WithVideoFilters(opt => opt.Scale(VideoSize.Hd))
     .ForceFormat("mp4")
     .WithFastStart();
 }).ProcessAsynchronously();
```

Throws the error:

`Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height`

I am sure this is to do with WithVideoBitrate but am not sure how to fix it.

Any help greatly appreciated!

**Comment by rosenbjerg** [comment]
You can get the ffmpeg argument string through the `Arguments` property on `FFMpegArgumentProcessor`
