### ISSUE TITLE
ThrowIfInputFileDoesNotExist when HTTP source is used

### ISSUE THREAD

**Issue by MosheL** [rosenbjerg/FFMpegCore#486]
Hi

I am using FFMpeg with S3 storage (not the original, but compatible).

I am receiving

      FFMpegException: No file found at 'https://s3.server/bucket/1.mp4'

The file is readable via simple HTTP and when I am testing with `ffmpeg` commandline its working

   $ ffmpeg -i https://s3.server/bucket/1.mp4 -ss 0:0:05 -frames:v 1 output.jpg

The  ThrowIfInputFileDoesNotExist need to be disabled if the original path taken from the network and not from FileSystem.

Thanks for all

**Comment by ryno1234** [comment]
Having the same issue.

**Comment by rosenbjerg** [comment]
Have you tried using `FromUrlInput` instead of `FromFileInput`?

**Comment by rosenbjerg** [comment]
You could also have solved it be passing false to verifyExists parameter of FromFileInput if you insist on using that one

**Comment by MosheL** [comment]
@rosenbjerg  Its working in the last version (in the past I tried and it was broken). Nice.

Thanks !!
