### ISSUE TITLE
The type initializer for 'FFMpegCore.Enums.FileExtension' threw an exception

### ISSUE THREAD

**Issue by yangbocheng** [rosenbjerg/FFMpegCore#493]
i got this exception when testing `var z = FileExtension.Png` 

while i have set the ffmpeg bin path then `FFProbe.Analyse(mp4)` work well.

please give some sugguestions about solving this exception!

here is my console-test setting
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FFMpegCore" Version="5.1.0" />
    <PackageReference Include="FFMpegCore.Extensions.SkiaSharp" Version="5.0.0" />
  </ItemGroup>

</Project>

```

ffmepg is from `https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-n6.1-latest-win64-gpl-6.1.zip`

**Comment by tiesont** [comment]
Would probably be helpful to have an example of your unit test - `FFMpegCore.Enums.FileExtension.Png` is just a static pseudo-constant, so that's not going to throw an exception. 

The `Extension()` method _will_ throw an exception if you pass it a Codec which this library doesn't recognize. That could be the case if the MP4 you're analyzing was encoded using H.265 rather than H.264, for instance.

**Comment by yangbocheng** [comment]
thanks .
with sourcecode debug, i found that it's my fault:  i have set the FFOptions with `ExtensionOverrides = null`, so this `if (GlobalFFOptions.Current.ExtensionOverrides.ContainsKey(Name))` will get exception.

after i remove this ` ExtensionOverrides = null`, the `FFMpeg.Snapshot`(which has called `FileExtension.Png`) method work well 
![image](https://github.com/rosenbjerg/FFMpegCore/assets/32633109/ba1dac66-b271-417f-8558-9a62c98e397d)

**Comment by tiesont** [comment]
If you for some reason still wanted to set ExtensionOverrides to `null`, your conditional could be updated to

```c#
if (GlobalFFOptions.Current.ExtensionOverrides?.ContainsKey(Name) == true)
```

**Comment by tiesont** [comment]
Ah, I see, that's a check by this library, here: https://github.com/rosenbjerg/FFMpegCore/blob/eb221c3e49ce6013b164bad0fc88bf0879da95c3/FFMpegCore/FFMpeg/Enums/ContainerFormat.cs#L18

Might be worth a PR
