### ISSUE TITLE
Audio Filters

### ISSUE THREAD

**Issue by double-dubs** [rosenbjerg/FFMpegCore#500]
Is it possible to pass a string of audio filters like this?

silenceremove=start_periods=1:start_duration=1:start_threshold=-60dB:detection=peak,aformat=dblp,areverse,silenceremove=start_periods=1:start_duration=1:start_threshold=-60dB:detection=peak,aformat=dblp,areverse

What seems to work is this:

ffmpeg -i input.mp3 -af "silenceremove=start_periods=1:start_duration=1:start_threshold=-60dB:detection=peak,aformat=dblp,areverse,silenceremove=start_periods=1:start_duration=1:start_threshold=-60dB:detection=peak,aformat=dblp,areverse"

I have tried all sorts of things with custom arguments, but keep getting errors.

**Comment by lnodaba** [comment]
@double-dubs I want to build a similar command with `[FFMpegCore](https://github.com/rosenbjerg/FFMpegCore)` how do you do that? I find it hard to come up with the C# version of the ffmpeg command I figured out for the specific case.

**Comment by rosenbjerg** [comment]
Sure, just use `.WithCustomArgument`
