### ISSUE TITLE
No .MultiOutput in FFMpegArguments in current (5.1.0) version from nuget

### ISSUE THREAD

**Issue by pakdanan** [rosenbjerg/FFMpegCore#503]
There is no .MultiOutput in FFMpegArguments class in 5.1.0 version from nuget, eventhough I see it in [test code](https://github.com/rosenbjerg/FFMpegCore/blob/main/FFMpegCore.Test/ArgumentBuilderTest.cs)  . 
Thanks.

**Comment by rosenbjerg** [comment]
Code merged after the release of v 5.1.0 is not included in the nuget package. Next version will soon release, containing a number of fixes and improvements
