### ISSUE TITLE
How to Join Images Async with Progression Tracking?

### ISSUE THREAD

**Issue by ProgrammerGithub** [rosenbjerg/FFMpegCore#504]
I'm trying to create a video from a bunch of images. I was able to accomplish that using "FFMpeg.JoinImageSequence".

This works fine but I have a couple of issues:

1. I can't run the function async and the code hangs until it finishes. And the function takes forever if it's greater than 1000 images.

2. I would like a way to track the progress of the function. So if I'm merging 10,000 images, I want a way to find out how many frames are completed so far or the completion percentage.

After looking around this github repo, it appears I need to use FFMpegArguments, ProcessAsynchronously, and notifyonprogress. But I'm having trouble finding an example that combines all of these together. And all combinations I tried create corrupted videos.

**Comment by rosenbjerg** [comment]
The github issues are for tracking code issues in this library, not general support.
