### ISSUE TITLE
FFMpeg snapshot for inmemory

### ISSUE THREAD

**Issue by ybkamath** [rosenbjerg/FFMpegCore#508]
Hello,

I am trying to use FFMpeg.Snapshot(inputPath, new Size(200, 400), TimeSpan.FromMinutes(1)) in the latest version of the nuget but i see that we need to provide the output file as the second param. Please let me know that creating the snapshot inmemory exists in the latest build

**Comment by rosenbjerg** [comment]
You would need to use either the `FFMpegCore.Extensions.System.Drawing.Common` or `FFMpegCore.Extensions.SkiaSharp`
