### ISSUE TITLE
Is it possible to apply transitions when joining videos

### ISSUE THREAD

**Issue by CreamWerx** [rosenbjerg/FFMpegCore#516]
I apologize if help questions are not allowed.
I'm new to both ffmpeg and FFMpegCore.
I've managed to add it to my winforms app .net8, and accomplish some simple tasks like extract audio and join a list of mp4 files. And I'm really impressed with it. So thanks for creating and sharing.

But I'd really like to add a simple crossfade transition between files when joining them.

My join code

```
public static bool VideoJoinVideos(string[] filePaths, string outPath)
{
	try
	{
		return FFMpeg.Join(outPath, filePaths);
	}
	catch (Exception ex)
	{
		MessageBox.Show(ex.Message);
		return false;
	}
}
```

I have carried out searches both here and web, but cannot find any info.

Thank you for reading my question

**Comment by rosenbjerg** [comment]
Currently not with this library, and I'm unsure if even possible with ffmpeg at all
