### ISSUE TITLE
(Question) Cookbook and Other Docs

### ISSUE THREAD

**Issue by sp00ky** [rosenbjerg/FFMpegCore#517]
Hopefully this isn't a silly question, but I'm wondering if there are some formal docs or at least a set of examples for doing common ops.  Maybe even a guide to translating how you'd do something from the command line to how to do it using FFMpegCore.

For example, say I wanted to take a bunch of videos off my GoPro and join them all.  In the process I'd like to zoom (crop/resize?) the whole video and I'd like to use hardware acceleration for the whole thing.  Where would I look if I wanted to see how to accomplish that using FFMpegCore.  FYI, ChatGPT hallucinates the whole thing :)

Thanks!

**Comment by tiesont** [comment]
There are no official docs beyond the examples shown in the README and in the Examples project (https://github.com/rosenbjerg/FFMpegCore/blob/main/FFMpegCore.Examples/Program.cs). There _are_, however, a lot of unit tests which as a side effect demonstrate how to accomplish some tasks: https://github.com/rosenbjerg/FFMpegCore/tree/main/FFMpegCore.Test
