### ISSUE TITLE
Is it possible to save processed media in memory instead of file using this library?

### ISSUE THREAD

**Issue by MarioPL98** [rosenbjerg/FFMpegCore#521]
Hello. I'd like to store some processed media in a variable (in memory) instead of file. Let's say I opened an image from disk and scaled it to desired resolution. I need to have the processed image stored in memory as a variable for further processing. This is the simplest example and a starting point as my target is to capture some stream (be it network stream or desktop capture) and process it in c#. Is it possible using this library?

Something like output pipe.

**Comment by rosenbjerg** [comment]
See OutputToPipe
