### ISSUE TITLE
Will it work in mobile and web platform?

### ISSUE THREAD

**Issue by Barshan-Mandal** [rosenbjerg/FFMpegCore#524]
will it work in latest .net maui platforms and blazor web applications?If yes,show me an example

**Comment by rosenbjerg** [comment]
I do not work with those frameworks, but depending on how it is integrated it should be possible

**Comment by Barshan-Mandal** [comment]
But it doesn't work on mobile and web

**Comment by tiesont** [comment]
> But it doesn't work on mobile and web

Not entirely sure what you're asking for or what "doesn't work" means - I use FFMpegCore in a few web applications just fine. You're going to need to elaborate quite a bit if you expect any meaningful response, here.
