### ISSUE TITLE
Linux pipe input cuts 2 seconds of audio after convertion. (2 seconds audio loss \ linux issue)

### ISSUE THREAD

**Issue by ValeriiInshyn** [rosenbjerg/FFMpegCore#532]
First of all, thank you for doing such a great library people coulde use.

I use this sample of code:

```
 var result = new MemoryStream();
input.Position = 0;
await FFMpegArguments
.FromPipeInput(new StreamPipeSource(input))
.OutputToPipe(new StreamPipeSink(result),
options => options.ForceFormat("wav"))
.ProcessAsynchronously();

result.Position = 0;

return result;
```

If I use this sample of code on windows - everything is good. If i do the same on linux - I lose part of my audio. But my problem that I should only Linux, so I need to find a solution. I tried different codecs, and custom arguments. 

Any ideas why it is happening and how it could be fixed?

**Comment by BronsonZ** [comment]
I'm experiencing the exact same issue. When run on Linux, the first ~2 seconds of the audio is cut off after encoding from `.wav` to `.mp3`. On windows the entire audio is preserved. 

I've narrowed it down to only occurring when the input is a pipe input. If I set the input to a file, the entire audio is preserved no matter what I use for the output (pipe or file).

**Comment by ValeriiInshyn** [comment]
Thank you for your answer, found out this solution as well. Here is the code example:

```
  MemoryStream input = new MemoryStream();
  var resultStream = new MemoryStream();

  string tempInputFilePath = Path.GetTempFileName();
  using (var fileStream = new FileStream(tempInputFilePath, FileMode.Create, FileAccess.Write))
  {
      input.CopyTo(fileStream);
      fileStream.Flush();
  }
  input.Position = 0;

  string tempOutputFilePath = Path.GetTempFileName();

  await FFMpegArguments
      .FromFileInput(tempInputFilePath, true, options => options.ForceFormat("wav"))
      .OutputToFile(tempOutputFilePath, true,
          options => options
              .WithAudioBitrate(AudioQuality.Normal)
              .ForceFormat("mp3"))
      .ProcessAsynchronously(false, _ffOptions);

  // Read the output file to the result stream
  using (var fileStream = new FileStream(tempOutputFilePath, FileMode.Open, FileAccess.Read))
  {
      await fileStream.CopyToAsync(resultStream);
  }

  // Clean up temporary files
  File.Delete(tempInputFilePath);
  File.Delete(tempOutputFilePath);

  resultStream.Position = 0;
  return resultStream;

```

**Comment by ValeriiInshyn** [comment]
Closing issue. If you have sam issue with pipe input, check out the code in the example.
