### ISSUE TITLE
Enhancement: allow to save video snapshot as jpg

### ISSUE THREAD

**Issue by Scal-Human** [rosenbjerg/FFMpegCore#536]
Currently, the FFMpeg.Snapshot method only saves png file while FFMpeg allows to export jpg also.
It would be great to allow both formats as snapshot output.

**Comment by rosenbjerg** [comment]
Snapshot is a convenience method and you can easily do something similar. See Snapshot impl

**Comment by Scal-Human** [comment]
It is a convenience method that could easily be modified to allow either png or jpg as parameter instead of forcing every person needing it to rewrite this convenience method.

**Comment by tiesont** [comment]
> It is a convenience method that could easily be modified to allow either png or jpg as parameter instead of forcing every person needing it to rewrite this convenience method.

Sounds like a great idea for a pull-request! Looking forward to it!
