### ISSUE TITLE
VideoInfo (The system cannot find the file specified)

### ISSUE THREAD

**Issue by irajeevks** [rosenbjerg/FFMpegCore#54]
var videoInfo = VideoInfo.FromFileInfo(new FileInfo(Path.Combine(basePath, fileName)));

I am using above line of code. The path of my video file is perfect. But this line throws an exception "The system cannot find the file specified"

I am using .netCore 3.0 web app

**Comment by WeihanLi** [comment]
you may need to set the ffmpeg dir

``` csharp
FFMpegOptions.Configure(new FFMpegOptions { RootDirectory = "dir of ffmpeg" });
```

**Comment by BartBr** [comment]
the error message is unclear though. "The system cannot find the file specified" 
it would be an improvement to replace this with: "FFMpeg binaries not found in RootDirectory: {RootDirectory}"
