### ISSUE TITLE
NuGet Package missing FFProbe.AnalyseAsync method parameter

### ISSUE THREAD

**Issue by belius** [rosenbjerg/FFMpegCore#540]
Hi,

I've seen that the source code in main for version 5.1.0 has this method

https://github.com/rosenbjerg/FFMpegCore/blob/main/FFMpegCore/FFProbe/FFProbe.cs#L116-L123

that contains the customArguments optional parameter.

Using the package 5.1.0 from NuGet is missing that parameter.

Is it possible to publish a fixed version?

**To confirm the mismatch of code between Github Main branch (v5.1.0) and the Nuget published version (v5.1.0):**

**The Nuget Package 5.1.0 has been published on March 15th 2023, while the customArguments parameter has been added to the Github main branch on April 12 2023**

Thanks

**Comment by kaybi-gh** [comment]
The CI/CD seems to be failing so we'd have to fix it first

**Comment by rosenbjerg** [comment]
That is a fix that was merged after nuget pkg was released, thus it is not included of course

**Comment by belius** [comment]
> That is a fix that was merged after nuget pkg was released, thus it is not included of course

are you going to deploy the fix soon?
