### ISSUE TITLE
Report Error 'Input file not found'

### ISSUE THREAD

**Issue by Windyskys** [rosenbjerg/FFMpegCore#545]
I have use 
`var arguments = FFMpegArguments
                    .FromFileInput(inputfile)
                    .OutputToFile(outputPath, true, options => options
                        .WithVideoCodec(VideoCodec.LibX264)
                        .WithFramerate(30)
                        .WithSpeedPreset(Speed.UltraFast)
                        .ForcePixelFormat("yuv420p"));
arguments.ProcessSynchronously();
` 
always report input file not found, the report stack is:

Exception: Input file not found
StackTrace:    at FFMpegCore.Arguments.InputArgument.Pre()
   at FFMpegCore.FFMpegArguments.Pre()
   at FFMpegCore.FFMpegArgumentProcessor.Process(ProcessArguments processArguments, CancellationTokenSource cancellationTokenSource)
   at FFMpegCore.FFMpegArgumentProcessor.ProcessSynchronously(Boolean throwOnError, FFOptions ffMpegOptions)
   at ScreenRecorder.Services.ScreenRecorder.StopRecording(String outputPath)

the log file shows that the generate command is -i "D:\temp\frame_%06d.png" -c:v libx264 -r 30 -preset ultrafast -pix_fmt yuv420p "D:\temp\recording_20241029_162515.mp4" -y
And I use the command in terminal directly works well

I check double the path about exe and file, it is absolutely correct, how to fix it

**Comment by rosenbjerg** [comment]
You should probably set `verifyExists` to `false` (FromFileInput 2nd parameter)
