### ISSUE TITLE
Quite Trivial to set Up Live Video Streaming

### ISSUE THREAD

**Issue by amunim** [rosenbjerg/FFMpegCore#56]
Hi,
I need to encode live Webcam footage, which has become quite trivial to me and the docs also didn't help :(
`private void FinalVideo_NewFrame(object sender, NewFrameEventArgs eventArgs)
        {
            Bitmap Video = (Bitmap)eventArgs.Frame.Clone();
            _pictureBox.Image = Video;

            BitmapVideoFrameWrapper wrapper = new BitmapVideoFrameWrapper((Bitmap)eventArgs.Frame.Clone());
            _videoFrames.Add(wrapper);
            _ffmpeg.OnProgress += (progress) => Debug.WriteLine("Encode Progress: {0}", progress);

            if (_videoFrames.Count == 30)
            {
                StreamPipeDataReader output = new StreamPipeDataReader(new MemoryStream());
                RawVideoPipeDataWriter _rawVideo = new RawVideoPipeDataWriter(CreateFrames(30))
                {
                    FrameRate = 15
                };

                ArgumentContainer _codecArgs = new ArgumentContainer()
                {
                    new InputPipeArgument(_rawVideo),
                    new OutputPipeArgument(output)

                };

                var Result = _ffmpeg.Convert(_codecArgs);
                Debug.WriteLine("RESUTL: " + Result.Size);
            }
        }`
This Action is called when a new Frame arrives from AForgeManager camera.

           `private IEnumerable<IVideoFrame> CreateFrames(int count)
        {
            for (int i = 0; i < count; i++)
            {
                yield return _videoFrames[i];
            }
            _videoFrames.Clear();
        }
         `
This is how the 'docs' in ReadMe implements it and is how is implemented them but sadly no positive result.
I create a List of 'IVideoFrame' and Append every new frame to it then wait for it to reach at least 30 frames then encode them, clear the list and restart the procedure I don't know if this is the right way but any help is appreciated 👍

**Comment by max619** [comment]
Hi. Can you please provide an example project?

**Comment by amunim** [comment]
[Example Project](https://we.tl/t-QfEynbVjLO), I have commented out my implementation of FFMPEG. What I want to do is encode 1 second of footage OR 30 Frames to send it over the network. Right now each Frame is like ~120K bytes(depending on the resolution) obviously, which is too much to send.

**Comment by amunim** [comment]
**Update**: I forgot to mention that it isn't even logging any progress conversion either, so I think conversion is not happening at all but I may be wrong you have the example project you can check it from your end too.

**Comment by amunim** [comment]
**UPDATE:** I've managed to get Input Piping to work BUT
If I provide `OutputArgument("temporary.mp4")` The Colors are Broken I think this has to do with `BitmapVideoFrameWrapper` tampering with Bitmap's Colors.
If I provide output piping to get bytes (Which is what I want) like this `OutputPipeArgument(new StreamPipeDataReader(my_outputMemoryStream))` It throws an `IOException` broken piping.

**Comment by rosenbjerg** [comment]
That is good to hear. Let's continue in that issue instead

**Comment by amunim** [comment]
I think this issue has its own purpose. This issue is related to input and output piping which hasn't been resolved.
The problem is that the `ReadMe docs` doesn't provide enough information for output piping, however input piping was easily implemented by the docs but still no progress about output piping.
here is the code for that 
        `MemoryStream outStream = new MemoryStream();
                RawVideoPipeDataWriter _rawVideo = new RawVideoPipeDataWriter(_notEncodedFrames);

                ArgumentContainer _codecArgs = new ArgumentContainer()
                {
                    new InputPipeArgument(_rawVideo),
                    new OutputPipeArgument(new StreamPipeDataReader(outStream)),
                    new VideoCodecArgument(VideoCodec.LibX264),
                    new ScaleArgument(VideoSize.Ed),
                    new SpeedArgument(Speed.UltraFast)
                };

                _ffmpeg.Convert(_codecArgs);
                Debug.WriteLine("RESUTL: " + "|||" + outStream.ToArray().Length);
`
This throws `IOException: bad piping` so output piping doesn't work, if the moderator can shed  light on that would be great. :)

**Comment by max619** [comment]
Well, first of all output and input piping supports only codecs/containers without seeking. H264 requires seeking support. Secondly, when you are using output piping you need to explicitly define output container and codec, because usually ffmpeg can guess you container from extension of your file, but not when you are using pipes.

Try this:

```csharp
ArgumentContainer _codecArgs = new ArgumentContainer()
{
    new InputPipeArgument(_rawVideo),
    new ScaleArgument(VideoSize.Ed),
    new VideoCodecArgument("vp9"), //for Google VP9 codec (supports streaming),
    new ForceFormatArgument("webm"), //explicitly defined container
    new OutputPipeArgument(new StreamPipeDataReader(outStream)),
 };
```
This [how](https://github.com/rosenbjerg/FFMpegCore/blob/b8fc8e574226e93b45e47d0f62845c684513b611/FFMpegCore.Test/VideoTest.cs#L611) it is done in tests 

And also if you want to implement streaming of your webcam maybe it would me much easier if you will use streaming features provided by ffmpeg.

https://stackoverflow.com/questions/26999595/what-steps-are-needed-to-stream-rtsp-from-ffmpeg

Also, for real streaming it would be quite painful to use portions of frames, encode them to different files and so on. That is why i would advise you to use [`BlockingCollection`](https://docs.microsoft.com/dotnet/api/system.collections.concurrent.blockingcollection-1?view=netcore-3.1) and implement [Producer-Consumer](https://en.wikipedia.org/wiki/Producer%E2%80%93consumer_problem) pattern. Then you could pass frames to `RawVideoPipeDataWriter` like this:

```csharp
BlockingCollection<IVideoFrame> _frames; //initialized somewhere else

void OnFrameArrived(object sender, Bitmap frame)
{
   //First thread, may be UI thread or any other
    _frames.Add(new BitmapVideoFrameWrapper(frame.Clone));
}

void StartEncoding()
{
    
   //Background thread
    RawVideoPipeDataWriter _rawVideo = new RawVideoPipeDataWriter(_frames.GetConsumingEnumerable());
    //Here you would create Argument container start ffmpeg process and so on
}
```

**Comment by max619** [comment]
> **UPDATE:** I've managed to get Input Piping to work BUT
> If I provide `OutputArgument("temporary.mp4")` The Colors are Broken I think this has to do with `BitmapVideoFrameWrapper` tampering with Bitmap's Colors.
> If I provide output piping to get bytes (Which is what I want) like this `OutputPipeArgument(new StreamPipeDataReader(my_outputMemoryStream))` It throws an `IOException` broken piping.

@rosenbjerg Also i think we sould catch any exception thrown if [`ProcessSynchronously`](https://github.com/rosenbjerg/FFMpegCore/blob/b8fc8e574226e93b45e47d0f62845c684513b611/FFMpegCore/FFMpeg/FFMpegArgumentProcessor.cs#L39) and [`ProcessAsynchronously`](https://github.com/rosenbjerg/FFMpegCore/blob/b8fc8e574226e93b45e47d0f62845c684513b611/FFMpegCore/FFMpeg/FFMpegArgumentProcessor.cs#L60) and rethrow it with output of ffmpeg, it usually contains some usefull information about exception occured

**Comment by amunim** [comment]
@max619 Thank you very much it worked, there is an order bug which I think you should fix 
if you assign output pipe first it throws bad piping error about the output format
This throws an error
         
              `ArgumentContainer _codecArgs = new ArgumentContainer()
                {
                    new InputPipeArgument(_rawVideo),
                    new OutputPipeArgument(new StreamPipeDataReader(outStream)),
                    new ScaleArgument(VideoSize.Ed),
                    new VideoCodecArgument("vp9"),
                    new ForceFormatArgument("webm")
                };`

and if you put the output pipe in the end it **does not** throw the error
This does **not** throw the error
     
              `ArgumentContainer _codecArgs = new ArgumentContainer()
                {
                    new InputPipeArgument(_rawVideo),
                    new ScaleArgument(VideoSize.Ed),
                    new VideoCodecArgument("vp9"),
                    new ForceFormatArgument("webm"),
                    new OutputPipeArgument(new StreamPipeDataReader(outStream))
                };`

This bug should also be fixed

**Comment by max619** [comment]
> @max619 Thank you very much it worked, there is an order bug which I think you should fix
> if you assign output pipe first it throws bad piping error about the output format
> This throws an error
> 
> ```
>           `ArgumentContainer _codecArgs = new ArgumentContainer()
>             {
>                 new InputPipeArgument(_rawVideo),
>                 new OutputPipeArgument(new StreamPipeDataReader(outStream)),
>                 new ScaleArgument(VideoSize.Ed),
>                 new VideoCodecArgument("vp9"),
>                 new ForceFormatArgument("webm")
>             };`
> ```
> 
> and if you put the output pipe in the end it **does not** throw the error
> This does **not** throw the error
> 
> ```
>           `ArgumentContainer _codecArgs = new ArgumentContainer()
>             {
>                 new InputPipeArgument(_rawVideo),
>                 new ScaleArgument(VideoSize.Ed),
>                 new VideoCodecArgument("vp9"),
>                 new ForceFormatArgument("webm"),
>                 new OutputPipeArgument(new StreamPipeDataReader(outStream))
>             };`
> ```
> 
> This bug should also be fixed

This is currently [fixed](https://github.com/rosenbjerg/FFMpegCore/blob/b8fc8e574226e93b45e47d0f62845c684513b611/FFMpegCore.Test/VideoTest.cs#L314), if you take a look at current state of master branch it is not possible initialize argument container the way you do it. With fluent design it is only possible to add arguments in correct order

**Comment by amunim** [comment]
Nice :)
