### ISSUE TITLE
How to pass the NamedPipeServerStream to the continuous edited picture data through the named pipe

### ISSUE THREAD

**Issue by feelsyt** [rosenbjerg/FFMpegCore#61]
How to pass the NamedPipeServerStream to the continuous edited picture data through the named pipe

**Comment by rosenbjerg** [comment]
I'm not sure what you mean

**Comment by feelsyt** [comment]
code: p_to_ffmpeg = new NamedPipeServerStream("to_ffmpeg", PipeDirection.InOut, 1, PipeTransmissionMode.Byte, PipeOptions.Asynchronous, 1000000, 1000000);
            p_from_ffmpeg = new NamedPipeServerStream("from_ffmpeg", PipeDirection.In, 1, PipeTransmissionMode.Byte, PipeOptions.WriteThrough, 1000000, 1000000);
            //  -y -f rawvideo - vcodec rawvideo - video_size 656x492 - r 10 - pix_fmt rgb24 - i \\.\pipe\to_ffmpeg - c:v libvpx - f webm output.webm
            process = new System.Diagnostics.Process();
            process.StartInfo.FileName = "ffmpeg.exe";
            process.EnableRaisingEvents = false;

            process.StartInfo.Arguments = @"-y -f rawvideo -vcodec rawvideo -video_size 656x492 -r 10 -pix_fmt yuv420p -i \\.\pipe\to_ffmpeg -c:v libvpx -f flv rtmp://localhost:1935/hls/cctv";
        
            process.Start();
            process.StartInfo.RedirectStandardInput = true;
            process.StartInfo.UseShellExecute = false;
            process.StartInfo.CreateNoWindow = false;
           p_to_ffmpeg.WaitForConnection();




2.
p_to_ffmpeg.Write(gray.Data, 0, 1000);
Dynamic pictures can be modified and streamed to RTMP streaming server in real time through named pipeline writing








------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Malte Rosenbjerg"<notifications@github.com&gt;; 
发送时间: 2020年5月15日(星期五) 凌晨0:00
收件人: "rosenbjerg/FFMpegCore"<FFMpegCore@noreply.github.com&gt;; 
抄送: "水依亭"<44169350@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [rosenbjerg/FFMpegCore] How to pass the NamedPipeServerStream to the continuous edited picture data through the named pipe (#61)





 
我不确定你是什么意思
 
— 
您收到此消息是因为您创建了线程。
直接回复此电子邮件，在GitHub上查看，或取消订阅。

**Comment by feelsyt** [comment]
python:
 rtmpUrl =parameters
   # "rtmp://localhost:1935/hls/cctv"
    camera_path =camerip
  #"rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov"
    cap = cv2.VideoCapture(camera_path)
    fps = int(cap.get(cv2.CAP_PROP_FPS))
    width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))

# ffmpeg command
    command = ['ffmpeg',
        '-y','-an',
        '-f', 'rawvideo',
        '-vcodec','rawvideo',
        '-pix_fmt', 'bgr24',
        '-s', "{}x{}".format(width, height),
        '-r', '15',
        '-i', '-',
        '-c:v', 'libx264',
        '-pix_fmt', 'yuv420p',
        '-preset', 'ultrafast',
        '-hls_list_size', '3',
       '-hls_wrap', '3',
       '-hls_time', '1',
        '-f', 'flv', 
        rtmpUrl]

# 管道配置
    p = sp.Popen(command, stdin=sp.PIPE)
    while(cap.isOpened()):
       ret, frame = cap.read()
       if not ret:
        print("Opening error11111")
        break
      
 # 矩形左上角和右上角的坐标，绘制一个绿色矩形
       ptLeftTop = (10, 10)
       ptRightBottom = (100, 100)
       point_color = (0, 255, 0) # BGR
       thickness = 1 
       lineType = 4
       cv2.rectangle(frame, ptLeftTop, ptRightBottom, point_color, thickness, lineType)
       cv2.imshow("1235",frame)
       p.stdin.write(frame.tostring())

**Comment by feelsyt** [comment]
The two pythons above can run the real-time dynamic push modified graph to RTMP. If I don't succeed in doing so,.net I always disconnect the pipeline. I don't know if there is any processing in your package

**Comment by max619** [comment]
@feelsyt Hi, there is `InputPipeArgument` is made for this kind of processing.

You can check the test implementation [here](https://github.com/rosenbjerg/FFMpegCore/blob/59ca76cdfa2312a020aa5d18ba280feb0739a8d1/FFMpegCore.Test/VideoTest.cs#L217) with `System.IO.Bitmap` as a video frame, or you can implement you own type of Image with `IVideoFrame` interface

**Comment by max619** [comment]
Also, in this #56 issue i explained how to use piping for streaming

**Comment by rosenbjerg** [comment]
I hope Max' answers has helped you. I'm closing this issue
