### ISSUE TITLE
Cannot find file issue

### ISSUE THREAD

**Issue by smccloud** [rosenbjerg/FFMpegCore#63]
Hello,

I'm trying to use FFMpegCore to help me determine what movies I have in an MKV container that aren't HEVC.  All movies are stored on my home server, and I can access them just fine from any machine on my network.  However, when I try to use var video = new VideoInfo(file.FullName); (where file is a FileInfo object) I get an error saying "The system cannot find the file specified".  Is there an issue using FFMpegCore to access files over a network?

**Comment by smccloud** [comment]
Figured it out, had to add 
`FFMpegOptions.Configure(new FFMpegOptions { RootDirectory = "dir of ffmpeg" });`
A better error message would help though.

**Comment by PylotLight** [comment]
Had the same issue, this helped me I suppose.
