### ISSUE TITLE
How to convert mkv to mp4 with FFMpegCore?

### ISSUE THREAD

**Issue by dev-ptdi** [rosenbjerg/FFMpegCore#64]
Hi,

Thanks for the latest update!.

I need info, how to convert mkl to mp4 with FFMpegCore?

many thanks

**Comment by dev-ptdi** [comment]
> d



> d

**Comment by dev-ptdi** [comment]
I use manual ffmpeg (installed on linux) and run below:

var processInfo = new ProcessStartInfo();
                                processInfo.FileName = "/usr/bin/ffmpeg";
                                processInfo.Arguments = "-i " + _mkv + " -ar 44100 -ab 96 -f mp4 " + _output.FullName;
                                processInfo.CreateNoWindow = true;
                                processInfo.UseShellExecute = false;

it works properly, I don't know how to apply the above command with FFMpegCore?

**Comment by rosenbjerg** [comment]
It seems you are not transcoding the streams, and just rely on the mkv containing x264 and aac or ac3.
I have modified that first example in the README to fit your use case:

```csharp
FFMpegArguments
    .FromInputFiles(_mkv)
    .WithVideoCodec(VideoCodec.LibX264) // omit if you don't want to encode the video stream
    .WithAudioCodec(AudioCodec.Aac) // omit if you don't want to encode the audio stream
    .WithAudioSamplingRate(44100)
    .WithAudioBitrate(96)
    .WithFastStart() // optional, but I will recommend it if you intend to play it remotely
    .OutputToFile(_output.FullName) // should have the extension .mp4, unless you add .ForceFormat("mp4") before .OutputToFile(..)
    .ProcessSynchronously() // or async
```
You could use `FFProbe.Analyse(_mkv)` to analyse the input file and determine if video or audio stream encoding is necessary
