### ISSUE TITLE
VideoInfo removed in 2.0?

### ISSUE THREAD

**Issue by tiesont** [rosenbjerg/FFMpegCore#65]
Apologies if I missed something, but was [VideoInfo](https://github.com/rosenbjerg/FFMpegCore/blob/legacy/FFMpegCore/VideoInfo.cs) purposefully removed in version 2.0? If so, could that be noted somewhere in the README?

**Comment by rosenbjerg** [comment]
The functionality has changed a bit, but is still there. Now, you can use `FFProbe.Analyse(<file>)` to get a `MediaAnalysis` instance containing the same (and more) information about the analysed media file. 
It is the first section in the readme btw

**Comment by tiesont** [comment]
Yes, I can eventually get the same functionality, although not directly from FFProbe. I think the point I was trying to make was that the class `VideoInfo` went away completely without any mention anywhere, nor any reason as to why it was removed.

Does that mean that `ImageInfo` will be removed at some point?

Closing, since I've been able to recreate what I was using VideoInfo for. Thanks.

**Comment by rosenbjerg** [comment]
Yeah, it is likely that ImageInfo will be removed as well at some point, as that has nothing to do with FFMpeg or FFProbe. I think there are much better libraries available for images, and I would like to keep this library focused on media analysis and conversion, which is what FFMpeg and FFProbe is for. If you need something for proper image manipulation, I'd suggest something based on ImageMagick

**Comment by rosenbjerg** [comment]
But yeah, it might have been useful with an upgrade guide

**Comment by tiesont** [comment]
I actually use ImageSharp for images. If you haven't heard of it, I'd suggest taking a gander, when/if you're bored: https://github.com/SixLabors/ImageSharp - I have nothing but good things to say about my experience so far.

I only use FFMpegCore for the info that VideoInfo gave me (and that FFProbe still yields, eventually). Well, it's also used in a fallback library I built for transcoding, but we use AWS's Elastic Transcoder for the most part.

Hope none of this comes across as negative or in any way as complaining - I've had no issues when using this project (aside from the mild surprise (as noted here) when updating to 2.0, and that wasn't really a big deal).
