### ISSUE TITLE
How can I cut video down to smaller length?

### ISSUE THREAD

**Issue by masum-ahammed** [rosenbjerg/FFMpegCore#66]
I need to split the video in to several parts and merge them along with some additional images. How can I do that?

**Comment by rosenbjerg** [comment]
That sort of question are better to ask on [StackOverflow](https://stackoverflow.com/).
Issues are for issues, not so much for questions :)

But it sounds like something that can be done by first splitting the video using `.Seek(..)` and `.Duration(..)` in the argument builder. Then transform the images into videoclips of the length you wish, fx. using `FFMpeg.PosterWithAudio(..)` where you could also add some sound to the "image video clip", so it isn't just silent while showing the images. Then you just `FFMpeg.Join(...)` all the parts together in the order you wish.

**Comment by masum-ahammed** [comment]
Thank you @rosenbjerg . Sorry for creating issue here. I will ask question on StackOverflow next time.

**Comment by masum-ahammed** [comment]
Hi @rosenbjerg 
How can I set a delay during join multiple video pieces together?

Thanks,
Masum

**Comment by InfriaAB** [comment]
I'm also wondering this and this is the first hit on google.
