### ISSUE TITLE
Why I got a warning after I installed FFMpegCore from nuget?

### ISSUE THREAD

**Issue by dev-ptdi** [rosenbjerg/FFMpegCore#69]
Hi

Why I got a warning after I installed FFMpegCore from nuget? (VS2019, Net Core 3.1)

![Capture](https://user-images.githubusercontent.com/62099183/84143002-01be3580-aa80-11ea-947a-5b5ae4f751ad.PNG)

**Comment by rosenbjerg** [comment]
I am unable to replicate this. I have just created a fresh .NET Core 3.1 console app in VS2019 and installed FFMpegCore v.2.0.1 and no warning is shown
![image](https://user-images.githubusercontent.com/11181960/84178581-f28db680-aa84-11ea-86b6-eec0e436a4d4.png)
You should be able to see the warning printed in the console/log.
If you missed the warning, you can try removing and then reinstalling the package so the warning will get printed again. But it is possibly also printed as a warning in the build log during build.

**Comment by rosenbjerg** [comment]
Did you discover what the culprit was?

**Comment by dev-ptdi** [comment]
please ignore this.. I remove and install it again then it disappear..

thank you
