### ISSUE TITLE
Transcode in Memory

### ISSUE THREAD

**Issue by Agrejus** [rosenbjerg/FFMpegCore#71]
I am having an issue attempting to transcode a video in memory.  AIl I get for an error is "Pipe is broken".  I have tried debugging the project with no luck.  I followed the example I found in the tests, but I suspect I am missing something.

Test Followed: https://github.com/rosenbjerg/FFMpegCore/blob/b8fc8e574226e93b45e47d0f62845c684513b611/FFMpegCore.Test/VideoTest.cs#L611

Do I need to inherit from `IPipeSink` in order to output properly?

Here is the code I have.  I am trying to convert an AVI to MP4 in memory,
```
                var path = @"path_to_my_video.avi";
                var input = FFProbe.Analyse(path);
                using (FileStream fs = new FileStream(input.Path, FileMode.Open, FileAccess.Read, FileShare.ReadWrite))
                using (var output = new MemoryStream())
                {
                    try
                    {
                        var pipeSource = new StreamPipeSource(fs);
                        var arguments = FFMpegArguments.FromPipe(pipeSource)
                            .WithVideoCodec(VideoCodec.LibX264)
                            .ForceFormat("mp4");

                         var processor = arguments.OutputToPipe(new StreamPipeSink(output)); // Doesn't Work
                         // This Works var processor = arguments.OutputToFile(@"output_test.mp4");

                        var success = processor.ProcessSynchronously();
                    }
                    catch (Exception ex)
                    {

                        throw;
                    }
                }
```

Version: 2.0.1

**Comment by Agrejus** [comment]
The weird thing is, the code works with this line and no changes `var processor = arguments.OutputToFile(@"output_test.mp4");` but `var processor = arguments.OutputToPipe(new StreamPipeSink(output));` does not work.

**Comment by Agrejus** [comment]
Also, when I run FFMpeg using the command line I can convert my files without issue.

Command: `ffmpeg -i "input.avi" "output.mp4"`

**Comment by rosenbjerg** [comment]
Is there a reason for not using `.FromInputFiles(..).ToOutputFile(..)` ?

**Comment by Agrejus** [comment]
@rosenbjerg I was trying to do everything in memory, reading from a file stream and writing to a memory stream.  I do not want to save the output file, I want to send the output stream to another destination, that's why I am opting for a memory stream.

**Comment by rosenbjerg** [comment]
Okay. What sort of stream are you outputting to?
Have you tried from file to pipe? It seems you are using an input file, from your example

**Comment by max619** [comment]
@Agrejus Hi, this might be an issue with `mp4` container cause it requires seeking when encoding. Try different container, for example `mov` or `webm`, as i remember it works with them

**Comment by Agrejus** [comment]
@rosenbjerg I am trying to output to a MemoryStream.  I tried from file to pipe and I get a different error, this time with FFMpeg.  I suspect that would work if I could get my parameters correct.  Error is:

```
[mp4 @ 00000234cf5120c0] muxer does not support non seekable output
Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
Error initializing output stream 0:0 -- 
[aac @ 00000234cefa7980] Qavg: 10458.081
[aac @ 00000234cefa7980] 2 frames left in the queue on closing
```

@max619 `webm` does work!  Thank you

**Comment by Agrejus** [comment]
@rosenbjerg It does work in memory if I output to a `webm` instead of `mp4`.  I believe we can consider this resolved.  Not sure why it says `pipe broken` for an `mp4`, but `webm` works.

**Comment by rosenbjerg** [comment]
That might be because FFMpeg tries to seek in the stream when using mp4, as Max explains.
From the FFMpeg output you posted, it seems Max was spot on :)
Max is the expert on the piping support in this library. He implemented it

I'll close this issue now that your problem is solved :)

**Comment by dev-fatih-erol** [comment]
Sorry for raising the issue.
My research took a lot of time. I hope it helps someone.

           
```
var source = await _fileService.UploadAsync("videos", request.Video);

            var startTime = TimeSpan.FromSeconds(20);
            var duration = TimeSpan.FromSeconds(10);

            using var outputStream = new MemoryStream();

            await FFMpegArguments.FromUrlInput(new Uri(source), options => options
                    .WithCustomArgument("-ss " + startTime.ToString(@"hh\:mm\:ss"))
                    .WithDuration(duration))
                    .OutputToPipe(new StreamPipeSink(outputStream), options => options
                    .ForceFormat(VideoType.Mp4)
                    .WithCustomArgument("-movflags frag_keyframe+empty_moov"))
                    .ProcessAsynchronously();

            var outputData = outputStream.ToArray();
```

**In detail, the code consists of the following steps:**

- The first line calls the "_fileService.UploadAsync" method to upload the video file and assigns the result to the "source" variable.

- The second line assigns the starting time of the segment to the "startTime" variable and the duration of the cut to the "duration" variable.

- The third line creates a "MemoryStream" object which will be used as a memory stream to write the cut video data to.

- On the fourth line, an argument is created using the FFMpegArguments library to mark the video to be cut during the specified start time and duration.

- On the fifth line, the cut video with the specified settings is written to the memory stream using the "OutputToPipe" method.

- On the sixth line, the "ForceFormat" method is called to save the video in the MP4 format, with the "frag_keyframe+empty_moov" properties.

- Finally, the "ProcessAsynchronously" method is used to start the process asynchronously, and the cut video is returned as a byte array using the "outputStream.ToArray()" method.
