### ISSUE TITLE
Target netstandard2.0 instead of netstandard 2.1

### ISSUE THREAD

**Issue by vpenades** [rosenbjerg/FFMpegCore#72]
Is there any reason why NetStandard 2.1 is needed?

NetStandard 2.1 cannot be consumed from Net Framework 4.71, even Net Framework 4.8 still uses NetStandard 2.0.

From the [documentation](https://devblogs.microsoft.com/dotnet/announcing-net-standard-2-1/):

> Library authors who need to support .NET Framework customers should stay on .NET Standard 2.0. In fact, most libraries should be able to stay on .NET Standard 2.0, as the API additions are largely for advanced scenarios. However, this doesn’t mean that library authors cannot take advantage of these APIs even if they have to support .NET Framework. In those cases they can use multi-targeting to compile for both .NET Standard 2.0 as well as .NET Standard 2.1. This allows writing code that can expose more features or provide a more efficient implementation on runtimes that support .NET Standard 2.1 while not giving up on the bigger reach that .NET Standard 2.0 offers.

So, could you lower the version requirement to 2.0? or at least, multitarget 2.0 and 2.1?

**Comment by rosenbjerg** [comment]
I think supporting .NET Standard 2.0 is a good idea, as you suggest, even though that means losing some of the nice languages features. So I have released a new version that targets 2.0 instead of 2.1 (and a few other fixes)

**Comment by vpenades** [comment]
Thanks!
