### ISSUE TITLE
Metadata

### ISSUE THREAD

**Issue by jbrozek** [rosenbjerg/FFMpegCore#73]
Would be useful to capture some metadata from the ffprobe data.

**rotate** - is my main need, looks like this shows up on the video stream tags also
**creation_time**
**com.apple.quicktime.make**
**com.apple.quicktime.model**
**com.apple.quicktime.software**
**com.android.version**

**Comment by jbrozek** [comment]
Maybe a generic container for all meta data (dictionary), then it could be searched.

**Comment by rosenbjerg** [comment]
When you say metadata, you mean the Tags on Streams and on Format?

**Comment by jbrozek** [comment]
I was originally talking about the following you get from ffprobe on a file (example)

> Metadata:
    major_brand     : qt
    minor_version   : 0
    compatible_brands: qt
    creation_time   : 2020-05-14T20:12:55.000000Z
    com.apple.quicktime.make: Apple
    com.apple.quicktime.model: iPhone 8
    com.apple.quicktime.software: 13.4.1
    com.apple.quicktime.creationdate: 2020-05-14T15:12:01-0500
  Duration: 00:00:35.23, start: 0.000000, bitrate: 2711 kb/s
    Stream #0:0(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, mono, fltp, 93 kb/s (default)
    Metadata:
      creation_time   : 2020-05-14T20:12:59.000000Z
      handler_name    : Core Media Audio
    Stream #0:1(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709), 1280x720, 2612 kb/s, 30 fps, 30 tbr, 600 tbn, 1200 tbc (default)
    Metadata:
      rotate          : 90
      creation_time   : 2020-05-14T20:12:59.000000Z
      handler_name    : Core Media Video
      encoder         : H.264
    Side data:
      displaymatrix: rotation of -90.00 degrees

But yes it looks like most of the data I'm talking about is also on the tags and format, although the format would change fields per input file.

**Comment by rosenbjerg** [comment]
I would think that the metadata displayed in the output is exactly the same as what is output to Tags when using the json output format. 
But yeah, enabling the use of these "varying" properties could be done through a dictionary<string,string> interface.
Then getter properties that use the same dictionary can be added for the most common use-cases.
Does that sound like something that would solve this problem? And can you verify that it is the exact same data that is output both places, just using different formatting? (-print_format json)

**Comment by jbrozek** [comment]
Yes this would solve the problem.  It looks like the the following

**rotate** - tags on the video stream
**creation_time** - tags on format
**com.apple.quicktime.make** - tags on format
**com.apple.quicktime.model** - tags on format
**com.apple.quicktime.software** - tags on format
**com.android.version** - tags on format

**Comment by rosenbjerg** [comment]
I have just uploaded version 2.2.6 which changes Tags to a dictionary, so any tag can be used. 
I have added rotate, because it was needed for something else. The rest will possibly come in next version.
But now that it is a dictionary, you should be able to pull out all of those you mentioned.
So I'm closing this issue now that the features is implemented :)
