### ISSUE TITLE
How to get video width and height size?

### ISSUE THREAD

**Issue by dev-ptdi** [rosenbjerg/FFMpegCore#74]
I am trying to snapshot a video on certain timespan using code below:

on code:
 Bitmap _bmp = FFMpeg.Snapshot(_video, new Size(200, 400), TimeSpan.FromSeconds(_point));
I need to follow the original video width and height, how to do this?

MemoryStream _ms_mp4 = new MemoryStream(Convert.FromBase64String(_base64_mp4.Substring(_base64_mp4.IndexOf('/') + 1, 4)));

                MediaAnalysis _video = await FFProbe.AnalyseAsync(_ms_mp4);
                
                try
                {
             
                    for (int _i = 1; _i <= _ja_snappoints.Count; _i++)
                    {
                        int _point = (int)_ja_snappoints[_i];

                        Bitmap _bmp = FFMpeg.Snapshot(_video, new Size(200, 400), TimeSpan.FromSeconds(_point));
                        
                        using (MemoryStream _ms = new MemoryStream())
                        {
                            _bmp.Save(_ms, System.Drawing.Imaging.ImageFormat.Jpeg);
                            string _base64 = "data:image/jpeg;base64," + Convert.ToBase64String(_ms.ToArray());

                                _lsnapshot.Add(new { snappoint = _point, base64 = _base64 });
                           
                        }
                    }
                }

**Comment by rosenbjerg** [comment]
If I understand you correcly, you want the height and width of the original video?
I'd analyse the video using FFProbe first and then use the the height and width from the analysis

**Comment by rosenbjerg** [comment]
See readme for example of analysis
