### ISSUE TITLE
Problems with AnalyseAsync

### ISSUE THREAD

**Issue by dev-ptdi** [rosenbjerg/FFMpegCore#75]
string _mp4 = @"D:\Project\PTDigital\PrimeAI\tmp\test.mp4";
MediaAnalysis _video = await FFProbe.AnalyseAsync(@_mp4);

The system cannot find the file specified.

I try to load it as MemoryStream
MediaAnalysis _video = await FFProbe.AnalyseAsync(new MemoryStream(_bytes));   // THIS NEVER ENDING PROCESS

**Comment by rosenbjerg** [comment]
Are you sure that it is the video file that cannot be found?
Same exception is thrown if ffprobe couldn't be found.

**Comment by dev-ptdi** [comment]
please ignore file not found .. that's my fault .. sorry..
but for below, is still happening.. what I missed?

MediaAnalysis _video = await FFProbe.AnalyseAsync(new MemoryStream(_bytes)); // THIS NEVER ENDING PROCESS

**Comment by rosenbjerg** [comment]
What OS are you on? It seems there are some problems with using pipes on Ubuntu (from what I've seen) when FFMpeg or FFProbe fails. Still looking into that one

**Comment by ghost** [comment]
I have the same problem with FFProbe.Analyse, both using Filename and MemoryStream. I have double-checked the file names and the files exist. Perhaps although the error is FileNotFound, this may be referring to some library or internal file, and not the movie file itself. 
I am working with Windows 10, .net framework 4.7.2, vb.net, WPF desktop application. After receiving this error I was a little creative and tried to set RootDirectory and Temp to the application's bin/debug directory (the application's runtime directory) and c:\temp respectively. I also set all DLLs imported in my application to CopyLocal = True.

![Issue](https://user-images.githubusercontent.com/25200374/89768969-adc1e280-dafc-11ea-97b2-e7476c6e86d1.png)

**Comment by rosenbjerg** [comment]
@gouderadrian your problems sounds like it may be caused by ffmpeg not being installed, or at least not added to environment path. If that is the case; make sure ffmpeg is installed and that it is added to environment path, or specify the correct path to the folder containing ffmpeg.exe and ffprobe.exe:
`FFMpegOptions.Configure(new FFMpegOptions { RootDirectory = "./bin", TempDirectory = "/tmp" });`

**Comment by rosenbjerg** [comment]
I will add some check to the library that verifies the ffmpeg and ffprobe existence and version. That way, no confusion around which file is missing should be possible

**Comment by ghost** [comment]
That would be great.

**Comment by BenjayLin** [comment]
Hello, my code is as follows:
`var result=Client.GetStreamAsync(url).Result;
var mediaInfo = FFProbe.Analyse(result);`
Read network audio and video files and execute them normally under window. Video files cannot be executed normally under linux. The error is as follows:
`[mov,mp4,m4a,3gp,3g2,mj2 @ 0x26383e0] moov atom not found unix:/tmp/CoreFxPipe_FFMpegCore_1cad9593-a4dd-4e1f-8435-fd92f36a9269: Invalid data found when processing input at FFMpegCore.FFStreamProbe,Analyse( 
Int32 outputCapacity)`
Excuse me, what is this question?

**Comment by rosenbjerg** [comment]
I have added a check that throws a more clear exception telling if ffmpeg or ffprobe is missing
