### ISSUE TITLE
GPU Acceleration

### ISSUE THREAD

**Issue by curlyfro** [rosenbjerg/FFMpegCore#77]
is there a way to enable GPU acceleration?  if not, is it something you're considering?

**Comment by rosenbjerg** [comment]
afaik ffmpeg will automatically use hardware acceleration if [these prerequisites](https://stackoverflow.com/a/44518572) are met.
so this library does not have to consider this problem, since ffmpeg will handle it itself.

I might have misunderstood, so please reopen if that is the case

**Comment by curlyfro** [comment]
i don't think your prerequisites are [accurate](https://developer.nvidia.com/ffmpeg).  i think this depends on the input codec.  I'll run some tests but I don't think your software is gpu enabled.
