### ISSUE TITLE
i did look at the readme and your test code.  i'm not asking about joining videos.   given a specific timecode and duration, i have videos i want to grab clips from and i want to concatenate those clips into one video.

### ISSUE THREAD

**Issue by curlyfro** [rosenbjerg/FFMpegCore#79]
i did look at the readme and your test code.  i'm not asking about joining videos.   given a specific timecode and duration, i have videos i want to grab clips from and i want to concatenate those clips into one video.

_Originally posted by @curlyfro in https://github.com/rosenbjerg/FFMpegCore/issues/76#issuecomment-648099776_

**Comment by rosenbjerg** [comment]
Simply pull out all the parts you need using multiple conversions with .Seek(..) and .WithDuration(..) and then joining all those clips together.
This is an issue tracker. Please keep questions on stackoverflow.
