### ISSUE TITLE
OutputToFile should Throw appropriate error

### ISSUE THREAD

**Issue by amunim** [rosenbjerg/FFMpegCore#82]
when using `OutputToFile("temp.webm")`, I think overwrite **should** be default to true.
If it is set to false and file already exists it throws `Object Reference set to null` Exception. Which does not help in any way to find the problem. Hope I solve someone's 30 mins :)

**Comment by rosenbjerg** [comment]
Where does it throw a Object Reference set to null Exception?

**Comment by amunim** [comment]
On the line `FFMPEGARGUMENTS.etc etc` during runtime.

**Comment by rosenbjerg** [comment]
I've not seen this. Could you give a minimal example that shows this problem?

**Comment by amunim** [comment]
I dont have my laptop so here's some untested code
`await FFMPEGArguments.FromFile("sample.mp4").Scale(VideoMode.Ed).OutputToFile("temporary.mp4").ProcessAsynchronously()`
Run the code twice to get the error. Ofcource there are some types in the code but hopefully you get the idea

**Comment by rosenbjerg** [comment]
In version 2.2.3 of the library, overwrite defaults to true.
So in closing this issue :)
