### ISSUE TITLE
Snapshot image looks scaled down, if video was recorded in portrait mode.

### ISSUE THREAD

**Issue by nfjdu** [rosenbjerg/FFMpegCore#84]
![db57a477-b8ae-421f-b030-c52a635db755](https://user-images.githubusercontent.com/43147143/86598827-6056d080-bfa6-11ea-9b2b-086bf744cea0.png) - example. This is snap from video, I recorded on my mobile phone(portrait mode).

Is there an opportunity to get any info about is video recorded in landscape or portrait mode? Then I could at least set Size for Snapshot function. I investigated MediaAnalysis object, but all I see useful for me are width and height( Thank you.

**Comment by dev-ptdi** [comment]
I am facing the same problem.. 
looks like the size has wrong value

  MediaAnalysis _video = FFProbe.Analyse(_mp4_filename);

int _vw = _video.PrimaryVideoStream.Width;
int _vh = _video.PrimaryVideoStream.Height;

Bitmap _bmp = FFMpeg.Snapshot(_video, new Size(_vw, _vh), TimeSpan.FromSeconds(_seconds));

![202007_ini_device_id_14e56c82-d9df-4b98-9dd3-670fdeb7c471_view01](https://user-images.githubusercontent.com/62099183/86723183-dcf2b900-c051-11ea-931c-3cdcab20071b.jpg)


below result is make sense:

Bitmap _bmp = FFMpeg.Snapshot(_video, new Size(_vh, _vw), TimeSpan.FromSeconds(_seconds));

![202007_ini_device_id_7e1c38fc-fd8d-41a2-a48e-60c611704f66_view01](https://user-images.githubusercontent.com/62099183/86723640-496db800-c052-11ea-8f61-697bc88fb665.jpg)

**Comment by nfjdu** [comment]
> I am facing the same problem..
> looks like the size has wrong value
> 
> MediaAnalysis _video = FFProbe.Analyse(_mp4_filename);
> 
> int _vw = _video.PrimaryVideoStream.Width;
> int _vh = _video.PrimaryVideoStream.Height;
> 
> Bitmap _bmp = FFMpeg.Snapshot(_video, new Size(_vw, _vh), TimeSpan.FromSeconds(_seconds));
> 
> ![202007_ini_device_id_14e56c82-d9df-4b98-9dd3-670fdeb7c471_view01](https://user-images.githubusercontent.com/62099183/86723183-dcf2b900-c051-11ea-931c-3cdcab20071b.jpg)
> 
> below result is make sense:
> 
> Bitmap _bmp = FFMpeg.Snapshot(_video, new Size(_vh, _vw), TimeSpan.FromSeconds(_seconds));
> 
> ![202007_ini_device_id_7e1c38fc-fd8d-41a2-a48e-60c611704f66_view01](https://user-images.githubusercontent.com/62099183/86723640-496db800-c052-11ea-8f61-697bc88fb665.jpg)

I resolved it by using all functions for taking snapshot manually, without Resize() function call (as in the Snapshot method). Here is an example:

 var videoInfo = FFProbe.Analyse(video.AbsolutePath);

 using (var stream = new MemoryStream())
            {
                FFMpegArguments
                    .FromInputFiles(videoInfo.Path)
                    .WithVideoCodec(VideoCodec.Png)
                    .WithFrameOutputCount(1)
                    .Seek(TimeSpan.FromSeconds(0))
                    .ForceFormat("rawvideo")
                    .OutputToPipe(new StreamPipeSink(stream))
                    .ProcessSynchronously();
               ...

Seems like the problem is in Resize config function call in the Snapshot() method. It is overriding the Scale argument. Look here https://github.com/rosenbjerg/FFMpegCore/blob/master/FFMpegCore/FFMpeg/Arguments/SizeArgument.cs

**Comment by rosenbjerg** [comment]
If you don't want any resizing, you can pass null as size. It is nullable

**Comment by nfjdu** [comment]
> If you don't want any resizing, you can pass null as size. It is nullable

Yeah, I know. And there is the result - snapshot looks scaled down. Sorry that I didn't point that Size param was null.

**Comment by rosenbjerg** [comment]
Okay, that seems weird. I use the Snapshot functionality in another project (nxplx) where I always pass null for size, since I just want the original size. But I haven't had problems with the snapshot image quality.
Could you give attach a sample video and the code you used, which shows the problem?
That would make it much easier to find the culprit, since I haven't had this problem in other projects.
I take it that you guessed that you can determine the image orientation using height and width?
(`var portraitOrientation = height > width;`)

**Comment by nfjdu** [comment]
Are you sure, that videos are recorded in mobile portrait mode? If so, it's really strange 😕

**Comment by rosenbjerg** [comment]
No, the videos I've have tested on for that project has all been ~4:3 or ~16:9. I don't remember seeing a portrait mode snapshot.
I would like to look more into what could cause that problem, but I'd like a code and video sample from you so I'm sure to replicate your problem properly.

**Comment by nfjdu** [comment]
```csharp
var snapshot = FFMpeg.Snapshot(
                video,
                null,
                TimeSpan.FromSeconds(0)
            );
```

and any video recorded in portrait mode. I could send you a video from my snapshot example on email or somewhere else if needed

**Comment by rosenbjerg** [comment]
It should be possible to attach files to these issue comments. It says you can drag and drop files in the bottom of the text input panel

**Comment by nfjdu** [comment]
I know, just wanted send it to any direct.

**Comment by manhoodofhumanity** [comment]
This is video from my example

**Comment by nfjdu** [comment]
seems like here is no opportunity to attach a video file

**Comment by rosenbjerg** [comment]
I have just uploaded version 2.2.6, which contains the fix for this.
Turns out the problem was that the video frame had rotation, so the width and height from ffprobe were actually switched around.
I used a sample video made with my phone in portrait mode to debug it.
