### ISSUE TITLE
real-time h264 encoding

### ISSUE THREAD

**Issue by JiXiaoYao** [rosenbjerg/FFMpegCore#85]
My video source is a bytes stream in real-time h264 encoding format. How can I transcode to pictures in real time?

**Comment by rosenbjerg** [comment]
What do you mean with _real-time h264 encoding format_?

**Comment by JiXiaoYao** [comment]
maybe name is live stream.
That is, I continue to receive the h264 encoded stream from the remote end from the network.  I need to continue decoding.

**Comment by rosenbjerg** [comment]
I would think you could something similar to FFMpeg.Snapsnot(..) continously with some specified interval, using the remote video stream as input:

```csharp
FFMpegArguments
    .FromPipe(new StreamPipeSource(inputStream))
    .WithVideoCodec(VideoCodec.Png)
    .WithFrameOutputCount(1)
    .OutputToFile(output)
    .ProcessAsynchronously();
```

**Comment by JiXiaoYao** [comment]
If I want to get the output of each frame.
How do I configure OutPut?

**Comment by JiXiaoYao** [comment]
emmm 
I find a method to output to stream is:
```C#
.OutputToPipe(new StreamPipeSink(output))
```
but is don't know ffmpeg will put what kind of data into the stream

**Comment by rosenbjerg** [comment]
I don't know if/how that would be possible with ffmpeg

**Comment by rosenbjerg** [comment]
Closing this since it is not an issue.
Please keep questions on stackoverflow

**Comment by alllucky1996** [comment]
I have used it to solve this problem hopefully work for you
ffmpeg -i "rtsp://[camera-ip/url-address]" -pix_fmt yuv420p -deinterlace -vf "scale=640:360" -vsync 1 -threads 0 -vcodec libx264 -r 29.970 -g 60 -sc_threshold 0 -b:v 1024k -bufsize 1216k -maxrate 1280k -preset medium -profile: v main -tune film -acodec aac -b:a 128k -ac 2 -ar 48000 -af "aresample=async=1:min_hard_comp=0.100000:first_pts=0" -vbsf h264_mp4toannexb -f mpegts udp://127.0.0.1:10000
