### ISSUE TITLE
Why compressed file size bigger than the original ones?

### ISSUE THREAD

**Issue by dev-ptdi** [rosenbjerg/FFMpegCore#87]
I am trying to compress an MP4 file using code below:

FFMpegArguments
                   .FromInputFiles(_mp4_filename)
                   .WithVideoCodec(VideoCodec.LibX264)
                   .WithAudioCodec(AudioCodec.Aac)
                   .WithFastStart()
                   .OutputToFile(_compressed_filename, true)
                   .ProcessSynchronously();

The original file size is: 3.6MB, why the output size is bigger than the original? (6.5MB)

**Comment by rosenbjerg** [comment]
It depends on the bitrate and the transcode speed.
Bitrate can be set to a constant value, or you can use CRF (` .WithConstantRateFactor(20)`) with a value around 22-26 depending on how much smaller it should get. Lower CRF means less compression.
Slower processing means smaller size.
