### ISSUE TITLE
How to add text (single or multiline) on an mp4?

### ISSUE THREAD

**Issue by dev-ptdi** [rosenbjerg/FFMpegCore#89]
How to add text (single or multiline) on an mp4?

**Comment by dev-ptdi** [comment]
I try below: but it does not show

string _arg =  " -i " + _logo + " -filter_complex \"[0:v][1:v]overlay=W-w-5:H-h-5,drawtext=fontfile=arial.ttf:text='" + _info.Replace(":", ".") + "':fontcolor=white@1.0:fontsize=15\" -c:a copy -movflags +faststart " ;

                FFMpegArguments
                   .FromInputFiles(_mp4_filename)
                   .WithCustomArgument(_arg)
                   .OutputToFile(_watermarked, true)
                   .ProcessSynchronously();

**Comment by dev-ptdi** [comment]
solved!.. arial.ttf by copying arial.ttf

**Comment by rosenbjerg** [comment]
Good to hear.
Btw DrawText is supported though `.DrawText(..)` and faststart with `.WithFastStart()`
