### ISSUE TITLE
Creating Real-Time Streaming Server

### ISSUE THREAD

**Issue by tensarflow** [rosenbjerg/FFMpegCore#93]
Hello everyone!
First of all, thank you all for the great work! 

I have a minor question about using the FFMpegCore API for a specific application.
So I am using Unity to simulate a non specific industrial automation process. I have multiple cameras set up that are going to be the sources of an image processing pipeline. The image processing is going to be developed on other platforms. That's why I decided to stream these camera renderings with a protocol like rtp, rtsp, http or similar to another PC. I have found out that in general the FFMpeg library is pretty powerful (cheers to everyone involved!) and could handle this task. Therefore I successfully installed the FFMpeg library to my unity project. And just when I wanted to start programming the server application, **I couldn't find any resources neither in the test files nor in the API documentation that states how program a streaming server or what the functions are.** The only thing I found was this issue and I think there this API is not really used (?), but an external `ffmpeg.exe` is used.
The receiver side is going to use opencv for image processing and I was hoping that we can use a simple "videocapture("rtp:/...")"-like interface to get the images. I used to do it that way with gstreamer.

This is what I have 

```c#
    void Start()
    {
        var videoFramesSource = new RawVideoPipeSource(CreateFrames(64)) 
        {
            FrameRate = 30 //set source frame rate
        };
        FFMpegArguments
            .FromPipe(videoFramesSource)
            // ... other encoding arguments
            .OutputToFile("temporary.mp4")
            .ProcessSynchronously();
    }

    void Update()
    {
        
    }

    IEnumerable<IVideoFrame> CreateFrames(int count)
    {
        for (int i = 0; i < count; i++)
        {
            yield return GetNextFrame(); //method of generating new frames
        }
    }
```

 I would really appreciate any input to that. Thanks for your time..

**Comment by rosenbjerg** [comment]
Hi, sounds like an interesting use-case. This library doesn't (attempt to) support streaming of transcoded mediafiles to remote clients. ffserver was deprecated in 2018, which seems like it would have been fitting for your use-case.
Have you considered using gstreamer, or perhaps output to a pipe that streams to remote clients?

**Comment by tensarflow** [comment]
Okay thank you it is kind of a reliefe that I didn't spent too much time for it :)
Gstreamer brings its own complications since its not natively compatible with C# on Windows.
I think I found a possible solution, where someone implemented a native socket communication application for Unity. Gonna leave it here in case someone is on the hunt like me :).

https://github.com/BarakChamo/uTextureSendReceive

 You definitely have to draw a line between when searching for external tools instead of doing a little work yourself is worth it..

**Comment by lucaheft** [comment]
Hi sorry for the off the topic question, but im currently trying to get ffmpegcore working in Unity and it seems like you managed to do this. Can you lead me in the right direction?
I tried with the nuget dll which references some namespaces which are not available in Unity.
I also tried to move the ffmpeg code folder directly into my project, which results in tons of errors.

**Comment by tensarflow** [comment]
Hey! After 2 days of struggle with the file system of Unity I was able to use the namespaces within the Unity-VS environment. Turns out the dlls have to be in the right folder (within Assets/Plugins). But like I said it didn't help me very much and I ended up using the repo I mentioned. 

I'm sharing the tree of the project folder. Maybe it helps you :)

[tree.txt](https://github.com/rosenbjerg/FFMpegCore/files/5062072/tree.txt)
(Ignore the meta files)

**Comment by lucaheft** [comment]
Thanks for sharing your directory tree. Basically you referenced all the missing parts manually. Quite a hustle :/

After fiddleing around a bit i now use the ffmpeg.exe and spawn a process which handles the conversion. Here some sample code for future reference.

```
public void GeneratePreviews(string ffmpegPath, string videoPath, string outputPath, int width, int height, float length)
{
    // Preview thumbnails in low resolution -> preview-xxx
    System.Diagnostics.Process process = new System.Diagnostics.Process
    {
        StartInfo = new System.Diagnostics.ProcessStartInfo
        {
            FileName = ffmpegPath,
            Arguments = $"-y -loglevel quiet -stats -i \"{videoPath}\" -vf fps=1/{Mathf.Clamp(length / 30f, 1, float.MaxValue).ToString(CultureInfo.InvariantCulture)} -s {width}x{height} \"{outputPath}preview-%d.jpg\"",
            UseShellExecute = false,
            CreateNoWindow = true,
            RedirectStandardOutput = true,
            RedirectStandardError = true
        }
    };
    process.Start();
    string stderr = null;
    while ((stderr = process.StandardError.ReadLine()) != null)
    {
        float percentage = int.Parse(Regex.Match(stderr, @"\d+").ToString()) / Mathf.Round(length >= 30f ? 30f : length);
        EditorUtility.DisplayProgressBar("Generating previews...", $"{(int)(percentage * 100f)}%", percentage);
    }
}
```

Keep in mind that this will block the main thread! For editor scripts this should not be a problem. If you want to do something like this at runtime, spawn a new Thread which does the work.
