### ISSUE TITLE
Would you be open to improving progress events?

### ISSUE THREAD

**Issue by faldor20** [rosenbjerg/FFMpegCore#99]
The project https://github.com/cmxl/FFmpeg.NET has far better progress information but much poorer support for things like streams and less active development. 
I was wondering if you would be open to integrating some of the regex used to get more extensive progress information, from his project into your own?
If so i would be happy to take a crack at it. I just don't want to do that work if you aren't interested.

Thanks

**Comment by rosenbjerg** [comment]
I would definitely be open to merging a PR that makes progress events richer. However, I do think that the way this is handled in the library you mention is a bit clumsy, so I'm hoping for something better than a copy-paste of their implementation.
I do see the uses of some of those additional properties, such as fps, bitrate and size, so I'll support adding functionality that makes such information available :)

**Comment by rosenbjerg** [comment]
A PR is welcome any time :)
Closing this issue
